import crypto from "node:crypto";
import type { Principal, ReviewGateStore } from "./store.js";

// Identity, owned by the gate.
//
// THE DEFECT THIS REPLACES. For several rounds the gate took a `SessionAuthenticator` that the
// APPLICATION implemented, so identity and reviewer authority were whatever the caller said they were.
// Before that it took `actorIdentity: string`, so a caller could name both the actor and the reviewer and
// have string equality "authenticate" an assertion against itself. Neither is a boundary; both were
// described as one.
//
// Here the gate resolves a credential against its own `principals` collection. A caller cannot name
// itself, name a reviewer, or claim a reviewer class. What a principal may do is a fact in the gate's
// database, written by an operator, not a field in a request.

/**
 * KDF for stored credentials.
 *
 * DEVIATION FROM THE DESIGN, STATED RATHER THAN SLIPPED IN: the design says Argon2id. That needs a native
 * dependency, and adding one to a service that must build reproducibly in CI is a decision worth making
 * deliberately rather than incidentally. This uses scrypt from Node's standard library, which is
 * memory-hard and adequate for high-entropy machine credentials. If the owner wants Argon2id, it is a
 * dependency addition and a re-hash of stored credentials, not a redesign.
 *
 * Cost parameters chosen for machine-to-machine credentials that are verified on every request.
 */
const SCRYPT = Object.freeze({ N: 1 << 15, r: 8, p: 1, keylen: 32, maxmem: 64 * 1024 * 1024 });

/** Credentials are high-entropy and generated by the operator CLI, never by request handling. */
export function generateCredential(): string {
  return `rgc_${crypto.randomBytes(32).toString("base64url")}`;
}

export function hashCredential(credential: string, saltB64?: string): string {
  const salt = saltB64 ? Buffer.from(saltB64, "base64") : crypto.randomBytes(16);
  const derived = crypto.scryptSync(credential, salt, SCRYPT.keylen, {
    N: SCRYPT.N, r: SCRYPT.r, p: SCRYPT.p, maxmem: SCRYPT.maxmem,
  });
  return `scrypt$${SCRYPT.N}$${SCRYPT.r}$${SCRYPT.p}$${salt.toString("base64")}$${derived.toString("base64")}`;
}

export function verifyCredential(credential: string, stored: string): boolean {
  const parts = stored.split("$");
  if (parts.length !== 6 || parts[0] !== "scrypt") return false;
  const [, n, r, p, salt, expected] = parts;
  let derived: Buffer;
  try {
    derived = crypto.scryptSync(credential, Buffer.from(salt, "base64"), SCRYPT.keylen, {
      N: Number(n), r: Number(r), p: Number(p), maxmem: SCRYPT.maxmem,
    });
  } catch {
    return false;
  }
  const expectedBuffer = Buffer.from(expected, "base64");
  // Length-checked before timingSafeEqual, which throws on a mismatch rather than returning false.
  if (expectedBuffer.length !== derived.length) return false;
  return crypto.timingSafeEqual(expectedBuffer, derived);
}

/**
 * A lookup index over the credential.
 *
 * The stored hash is salted, so it cannot be used to find the principal. This unsalted index exists ONLY
 * to locate a candidate row; the salted hash above is what actually authenticates. Both are required:
 * without the index, authentication would have to scan every principal and verify each one.
 */
export function credentialIndex(credential: string): string {
  return crypto.createHash("sha256").update(`review-gate-index-v1|${credential}`).digest("hex");
}

/**
 * An authenticated caller. There is no constructor a route can reach: the only way to obtain one is
 * `authenticate`, and the only way that returns one is a credential the gate's own database recognises.
 */
const PRINCIPAL_KEY: unique symbol = Symbol("review-gate.authenticated-principal");

export class AuthenticatedPrincipal {
  /**
   * The brand. A CLASS FIELD, not a flag, not a symbol on the object.
   *
   * This is the fourth expression of one defect. Erased `private constructor`; then a public factory
   * beside the guard; then an unfrozen object; and now `Object.create(AuthenticatedPrincipal.prototype)`
   * — which inherits every method, satisfies `instanceof`, and satisfied the `isIssued` check I had just
   * written out of `instanceof` plus `Object.isFrozen`. Each previous fix was real and the next door was
   * open.
   *
   * `#issued` cannot be inherited, assigned, copied by `Object.assign`, or produced by `structuredClone`.
   * It exists only on an object this constructor actually ran for, which is what "issued" has to mean.
   */
  readonly #issued = true;

  /**
   * NOT `private constructor`. TypeScript privacy is erased, so `new AuthenticatedPrincipal(...)`
   * would succeed at runtime and a route could mint an owner. My own test caught that here, which is
   * the fifth time in this workstream that compile-time visibility stood in for a runtime boundary --
   * the key makes the throw real.
   */
  constructor(
    key: symbol,
    readonly principalId: string,
    readonly roles: readonly string[],
    readonly reviewerClasses: readonly string[],
    readonly credentialEpoch: number,
    readonly targetScopes: ReadonlyArray<{ orgId: string; serverId: string }>,
  ) {
    if (key !== PRINCIPAL_KEY) {
      throw new Error("AuthenticatedPrincipal cannot be constructed; it is issued by authenticate()");
    }
    // FROZEN, because `readonly` is erased. An independent review found that closing the construction
    // and factory routes still left the OBJECT mutable: any code holding a legitimately authenticated
    // principal could assign `roles = ["owner"]` and `hasRole("owner")` would then succeed. The defect
    // had moved from construction to mutation, which is precisely the "have I moved it rather than
    // closed it" question I had asked the reviewer to check.
    //
    // The arrays are frozen at construction; this freezes the object that holds them, so neither the
    // fields nor their contents can be reassigned.
    Object.freeze(this);
  }

  /**
   * INTERNAL. The key is required for the same reason the constructor demands one, and for a reason the
   * constructor guard alone did not cover.
   *
   * An independent review found that this factory was public and took an ordinary caller-built
   * `Principal`, supplying the private symbol itself — so any module importing AuthenticatedPrincipal
   * could mint an owner, a reviewer holding any class, or an executor. The constructor guard was real and
   * the factory defeated it. My own tests used exactly that route, which is why the suite did not notice.
   *
   * Only `authenticate()` holds the key, so the only way to obtain a principal is a credential the
   * gate's own database recognises.
   */
  static of(key: symbol, principal: Principal): AuthenticatedPrincipal {
    if (key !== PRINCIPAL_KEY) {
      throw new Error("AuthenticatedPrincipal.of is internal; principals come from authenticate()");
    }
    return new AuthenticatedPrincipal(
      PRINCIPAL_KEY,
      principal.principalId,
      Object.freeze([...principal.roles]),
      Object.freeze([...principal.reviewerClasses]),
      principal.credentialEpoch,
      // DEEP. Freezing the array left its ELEMENTS writable, so code holding a legitimate principal
      // could reassign targetScopes[0].serverId and mayActOn would then grant a substituted target. The
      // comment above claimed the contents could not be changed; it was true of the array and false of
      // what the array held.
      Object.freeze((principal.targetScopes ?? principal.audienceFor ?? []).map((target) =>
        Object.freeze({ orgId: target.orgId, serverId: target.serverId }))),
    );
  }

  /**
   * True only for an object this class's constructor actually ran for.
   *
   * `#issued in value` is the brand check: it cannot be satisfied by inheritance, assignment, cloning, or
   * a prototype trick, which is exactly what `instanceof` and `Object.isFrozen` could not distinguish.
   */
  static isIssued(value: unknown): value is AuthenticatedPrincipal {
    return typeof value === "object" && value !== null && #issued in (value as AuthenticatedPrincipal);
  }

  hasRole(role: string): boolean {
    return this.roles.includes(role);
  }

  holdsReviewerClass(reviewerClass: string): boolean {
    return this.reviewerClasses.includes(reviewerClass);
  }

  /** An executor may only act on targets it was provisioned for. */
  mayActOn(orgId: string, serverId: string): boolean {
    return this.targetScopes.some((t) => t.orgId === orgId && t.serverId === serverId);
  }
}

// The prototype is frozen too, so imported code cannot replace `hasRole` and change what every
// principal in the process reports. The class object is frozen for the same reason.
Object.freeze(AuthenticatedPrincipal.prototype);
Object.freeze(AuthenticatedPrincipal);

export type AuthOutcome =
  | { ok: true; principal: AuthenticatedPrincipal }
  | { ok: false; code: "missing_credential" | "unknown_credential" | "principal_disabled" };

/**
 * Resolve a bearer credential to a principal.
 *
 * Failure codes deliberately do not distinguish "no such credential" from "wrong credential" to a caller;
 * the distinction is available in the gate's own logs, not in the response.
 */
export async function authenticate(
  store: ReviewGateStore, header: string | undefined,
): Promise<AuthOutcome> {
  const credential = parseBearer(header);
  if (!credential) return { ok: false, code: "missing_credential" };
  const principal = await store.loadPrincipalByCredentialHash(credentialIndex(credential));
  if (!principal) return { ok: false, code: "unknown_credential" };
  if (!verifyCredential(credential, principal.credentialHash)) {
    return { ok: false, code: "unknown_credential" };
  }
  if (principal.disabledAt) return { ok: false, code: "principal_disabled" };
  return { ok: true, principal: AuthenticatedPrincipal.of(PRINCIPAL_KEY, principal) };
}

function parseBearer(header: string | undefined): string | null {
  if (!header) return null;
  const match = /^Bearer\s+(\S+)$/i.exec(header.trim());
  return match ? match[1] : null;
}
