import assert from "node:assert/strict";
import crypto from "node:crypto";
import test from "node:test";
import { assertApproverSeparation, assertDeploymentPolicy, encryptDeploymentValues } from "../src/configurationDeployment.js";
import { isConfigurationMutationTask, safeTaskSummary } from "../src/tasks.js";
import { deploymentCapabilities, hasPermission } from "@control-center/shared";

const target = { environmentKind: "staging", protected: false, repositoryRoot: "/srv/app", environmentFilePath: "/srv/app/.env.staging", composePath: "/srv/app/compose.yml", statelessServices: ["web"], protectedServices: ["mongo"] };
test("API accepts complete non-production deployment target", () => assert.doesNotThrow(() => assertDeploymentPolicy(target, [...deploymentCapabilities], "0.1.0")));
test("API rejects production and protected targets", () => { assert.throws(() => assertDeploymentPolicy({ ...target, environmentKind: "production" }, [...deploymentCapabilities], "0.1.0")); assert.throws(() => assertDeploymentPolicy({ ...target, protected: true }, [...deploymentCapabilities], "0.1.0")); });
test("API rejects incompatible version and incomplete capabilities independently", () => { for (const version of [undefined, "bad", "0.0.9", "0.1.0-beta.1"]) assert.throws(() => assertDeploymentPolicy(target, [...deploymentCapabilities], version)); assert.doesNotThrow(() => assertDeploymentPolicy(target, [...deploymentCapabilities], "0.1.0")); assert.doesNotThrow(() => assertDeploymentPolicy(target, [...deploymentCapabilities], "1.0.0")); assert.throws(() => assertDeploymentPolicy(target, ["environmentFileWrite"], "0.1.0")); });
test("API rejects escaping and stateful targets", () => { assert.throws(() => assertDeploymentPolicy({ ...target, environmentFilePath: "/etc/environment" }, [...deploymentCapabilities], "0.1.0")); assert.throws(() => assertDeploymentPolicy({ ...target, statelessServices: ["mongo"] }, [...deploymentCapabilities], "0.1.0")); });
test("approver separation is mandatory", () => { assert.throws(() => assertApproverSeparation("same", "same")); assert.doesNotThrow(() => assertApproverSeparation("creator", "approver")); });
test("deployment encryption contains no plaintext", () => { const fixtureValue = ["runtime", "generated", crypto.randomUUID()].join("-"); const result = encryptDeploymentValues({ TOKEN: fixtureValue }, "agent-key"); assert.equal(JSON.stringify(result).includes(fixtureValue), false); });
test("a tasks:run-only role cannot submit either configuration mutation type", () => { assert.equal(hasPermission("Developer", "tasks:run"), true); assert.equal(hasPermission("Developer", "configuration:deploy-non-production"), false); assert.equal(isConfigurationMutationTask("configuration.apply"), true); assert.equal(isConfigurationMutationTask("configuration.rollback"), true); assert.equal(isConfigurationMutationTask("collect.system"), false); });
test("deployment failure summaries never persist raw agent messages", () => { const secret = `synthetic-${crypto.randomUUID()}`; const raw = `Authorization: Bearer token\nhttps://user:pass@example.test/?secret=${secret}\nENV=${secret}\u0000${"x".repeat(2000)}`; const summary = safeTaskSummary("configuration.apply", raw, { errorCategory: "health" }); assert.equal(summary, "Configuration deployment failed (health)"); assert.equal(summary.includes(secret), false); assert.ok(summary.length < 100); });
test("ordinary task summaries redact URLs, query values, environment values, controls, and oversized text", () => { const secret = crypto.randomUUID(); const summary = safeTaskSummary("collect.system", `https://user:pass@example.test/path?token=${secret}\nAPI_KEY=${secret}\u0000${"x".repeat(2000)}`, {}); assert.equal(summary.includes(secret), false); assert.equal(summary.includes("user:pass"), false); assert.equal([...summary].some((character) => character.charCodeAt(0) < 32), false); assert.ok(summary.length <= 500); });
