import assert from "node:assert/strict";
import test from "node:test";
import { analyzeCiRun, analyzeDeployment, buildOperationalSnapshot, classifyFreshness, deterministicRecommendations, findSimilarIncidents, generateTimeline, normalizeSection, OperationalContextCache, rankRootCauses, scoreConfidence, snapshotEvidence, summarizeLogs } from "../src/operationalIntelligence.js";

const now = new Date("2026-07-18T12:00:00.000Z");
test("context builder normalizes metadata and rejects stale or incomplete sections", () => { const fresh = normalizeSection({ key: "server", timestamp: new Date(now.getTime() - 1000), source: "test", data: { status: "online" } }, now); const stale = normalizeSection({ key: "metrics", timestamp: new Date(now.getTime() - 60 * 60_000), source: "test", data: {} }, now); const incomplete = normalizeSection({ key: "git", source: "test", data: null }, now); const snapshot = buildOperationalSnapshot({ type: "server", id: "s1", label: "Server" }, [fresh, stale, incomplete], now); assert.equal(snapshot.sections.length, 1); assert.deepEqual(snapshot.rejectedSections.map((item) => item.reason), ["stale", "incomplete"]); assert.equal(fresh.confidence, "high"); });
test("freshness handles future, missing, fresh, aging, and stale timestamps", () => { assert.equal(classifyFreshness(undefined, now), "unavailable"); assert.equal(classifyFreshness(new Date(now.getTime() + 120_000), now), "unavailable"); assert.equal(classifyFreshness(now, now), "fresh"); assert.equal(classifyFreshness(new Date(now.getTime() - 5 * 60_000), now), "aging"); assert.equal(classifyFreshness(new Date(now.getTime() - 20 * 60_000), now), "stale"); });
test("evidence engine emits normalized metrics, discovery, git, and health evidence", () => { const sections = [normalizeSection({ key: "metrics", timestamp: now, source: "telemetry", data: { cpu: { usagePercent: 24 }, memory: { usedBytes: 48, totalBytes: 100 }, disk: [{}], network: {} } }, now), normalizeSection({ key: "discovery", timestamp: now, source: "telemetry", data: { applications: [1, 2, 3], repositories: [1], composeProjects: [1, 2] } }, now), normalizeSection({ key: "git", timestamp: now, source: "telemetry", data: [{ branch: "main", commit: "abc", dirty: false }] }, now), normalizeSection({ key: "health", timestamp: now, source: "checks", data: { health: [{ name: "Backend", lastResult: { success: false, errorCategory: "timeout" } }] } }, now)]; const evidence = snapshotEvidence(buildOperationalSnapshot({ type: "server", id: "s", label: "s" }, sections, now)); assert.ok(evidence.some((item) => item.value === "24%")); assert.ok(evidence.some((item) => item.label === "Working tree" && item.value === "clean")); assert.ok(evidence.some((item) => /unhealthy/.test(item.value))); });
test("root-cause scoring is deterministic and evidence backed", () => { const evidence: any[] = [{ sourceType: "health_check", label: "Backend", value: "unhealthy (timeout)", timestamp: now.toISOString(), freshness: "fresh", source: "test", confidence: "high" }, { sourceType: "logs", label: "Log", value: "missing environment variable DB_URL", timestamp: now.toISOString(), freshness: "fresh", source: "test", confidence: "high" }]; const causes = rankRootCauses(evidence); assert.equal(causes[0].title, "Missing environment variable"); assert.equal(causes[0].score, 0.92); assert.ok(causes.every((cause) => cause.evidence.length)); });
test("recommendations require and cite evidence", () => { assert.deepEqual(deterministicRecommendations([], []), []); const evidence: any[] = [{ sourceType: "server", label: "Status", value: "offline", timestamp: now.toISOString(), freshness: "fresh", source: "test", confidence: "high" }]; const steps = deterministicRecommendations([], evidence); assert.equal(steps[0].classification, "low_risk_diagnostic"); assert.ok(steps[0].evidence.length); });
test("timeline generation sorts and bounds events", () => { const timeline = generateTimeline([{ id: "2", type: "alert", timestamp: "2026-07-18T08:05:00Z", summary: "alert" }, { id: "1", type: "deployment", timestamp: "2026-07-18T08:01:00Z", summary: "deploy" }]); assert.deepEqual(timeline.map((item) => item.event), ["deploy", "alert"]); });
test("incident similarity is organization isolated", () => { const current: any = { id: "c", type: "failure", timestamp: now, summary: "backend health timeout", errorCategory: "timeout", orgId: "a" }; const matches = findSimilarIncidents(current, [{ id: "a1", type: "failure", timestamp: now, summary: "backend timeout after deploy", orgId: "a" }, { id: "b1", type: "failure", timestamp: now, summary: "backend health timeout", orgId: "b" }], "a"); assert.deepEqual(matches.map((item) => item.id), ["a1"]); });
test("confidence scoring uses freshness, corroboration, and conflicts", () => { const item = (sourceType: string, label: string, value: string) => ({ sourceType, label, value, timestamp: now.toISOString(), freshness: "fresh", source: "test", confidence: "high" }); assert.equal(scoreConfidence([item("server", "A", "1") as any]), "low"); assert.equal(scoreConfidence([item("server", "A", "1"), item("metrics", "B", "2"), item("health_check", "C", "3")] as any), "high"); assert.equal(scoreConfidence([item("server", "A", "1"), item("metrics", "A", "2"), item("health_check", "C", "3")] as any), "low"); });
test("cache returns values until invalidated or expired", () => { const cache = new OperationalContextCache<string>(100); cache.set("org:server:s1", "value", 0); assert.equal(cache.get("org:server:s1", 50), "value"); cache.invalidate("s1"); assert.equal(cache.get("org:server:s1", 60), undefined); cache.set("other", "value", 0); assert.equal(cache.get("other", 101), undefined); });
test("deployment impact identifies services, dependencies, databases and rollback", () => { assert.deepEqual(analyzeDeployment({ serviceNames: ["api"], dependencies: ["redis"], databases: ["mongo"], expectedDowntime: "30s", previousVersion: "v1", knownRisks: ["migration"] }), { affectedServices: ["api"], dependencies: ["redis"], databases: ["mongo"], expectedDowntime: "30s", rollbackAvailable: true, knownRisks: ["migration"] }); });
test("CI analysis groups failed jobs and infrastructure categories", () => { const result = analyzeCiRun({ conclusion: "failure", jobs: [{ name: "tests", conclusion: "failure", failingTests: ["one"], warnings: ["deprecated"] }, { name: "upload", conclusion: "failure", error: "artifact upload failed" }, { name: "build", conclusion: "failure", error: "hosted runner unavailable" }, { name: "cache", conclusion: "failure", error: "cache restore failed" }] }); assert.deepEqual(result.failedJobs, ["tests", "upload", "build", "cache"]); assert.deepEqual(result.failingTests, ["one"]); assert.equal(result.artifactFailures.length, 1); assert.equal(result.runnerIssues.length, 1); assert.equal(result.cacheProblems.length, 1); });
test("log summaries deduplicate, collapse stack frames, categorize, and bound output", () => { const result = summarizeLogs(["ERROR timeout 123", "ERROR timeout 456", "    at stack.ts:1", "WARN missing environment variable DB_URL"], 2); assert.equal(result.length, 2); assert.equal(result[0].count, 2); assert.equal(result[0].category, "timeout"); assert.equal(result[1].category, "configuration"); });
