import assert from "node:assert/strict";
import test from "node:test";
import { agentReleaseManifestDigest, agentUpgradePlanDigest, bootstrapReleaseManifestSchema, compareAgentVersions, evaluateAgentCompatibility, fleetRolloutDigest, fleetRolloutSchema, nextRolloutAction, type AgentInventory, type AgentRelease } from "../src/agentUpgrades.js";

const baseServer: AgentInventory = { serverId: "server-123456", name: "Synthetic host", protected: false, online: true, agentVersion: "1.0.0", protocolVersion: "task-v1", capabilities: ["agentUpgrade", "environmentDiscovery"], os: "linux", architecture: "x64", packageType: "tar", releaseChannel: "stable" };
function release(overrides: Partial<AgentRelease> = {}): AgentRelease { const value = { id: "release-110", version: "1.1.0", protocolVersion: "task-v1", minimumSourceVersion: "1.0.0", supportedOperatingSystems: ["linux"], supportedArchitectures: ["x64"], packageType: "tar" as const, channel: "stable" as const, artifactUrl: "https://releases.example.test/agent.tar.gz", artifactSha256: "a".repeat(64), artifactSizeBytes: 100, artifactSignature: "s".repeat(80), signatureKeyId: "key-1", manifestDigest: "b".repeat(64), manifestSignature: "m".repeat(80), requiredCapabilities: ["environmentDiscovery"], upgradeFrom: ["1.0.0"], rollbackTo: ["1.0.0"], publicationStatus: "published" as const, revoked: false, classification: "optional" as const, ...overrides }; return value; }

test("fleet compatibility evaluates optional, mandatory, current, offline, and legacy agents", () => {
  assert.equal(evaluateAgentCompatibility(baseServer, [release()], ["environmentDiscovery"]).state, "upgrade_available");
  assert.equal(evaluateAgentCompatibility(baseServer, [release({ classification: "mandatory" })], ["environmentDiscovery"]).state, "upgrade_required");
  assert.equal(evaluateAgentCompatibility({ ...baseServer, agentVersion: "1.1.0" }, [release({ upgradeFrom: [] })], ["environmentDiscovery"]).state, "up_to_date");
  assert.equal(evaluateAgentCompatibility({ ...baseServer, online: false }, [release()], ["environmentDiscovery"]).state, "offline");
  const legacy = evaluateAgentCompatibility({ ...baseServer, capabilities: [] }, [release()], ["environmentDiscovery"]); assert.equal(legacy.state, "manual_bootstrap_required"); assert.deepEqual(legacy.missingCapabilities, ["environmentDiscovery"]);
});

test("platform, architecture, channel, revocation, and intermediate paths fail closed", () => {
  assert.equal(evaluateAgentCompatibility({ ...baseServer, architecture: "arm64" }, [release()], []).state, "incompatible");
  assert.equal(evaluateAgentCompatibility({ ...baseServer, os: "freebsd" }, [release()], []).state, "incompatible");
  assert.equal(evaluateAgentCompatibility(baseServer, [release({ revoked: true })], []).state, "incompatible");
  assert.equal(evaluateAgentCompatibility(baseServer, [release({ publicationStatus: "draft" })], []).state, "incompatible");
  const intermediate = evaluateAgentCompatibility(baseServer, [release({ minimumSourceVersion: "1.1.0", version: "2.0.0", upgradeFrom: ["1.1.0"] })], []); assert.equal(intermediate.state, "manual_bootstrap_required"); assert.equal(intermediate.requiresIntermediateVersion, true);
});

test("future servers are evaluated from inventory rather than identifiers", () => { const future = { ...baseServer, serverId: "server-future-999", name: "Future synthetic", architecture: "arm64" }; assert.equal(evaluateAgentCompatibility(future, [release({ supportedArchitectures: ["x64", "arm64"] })], []).state, "upgrade_available"); });

test("release and plan digests bind all immutable inputs", () => { const item = release(); const digest = agentReleaseManifestDigest(item); assert.notEqual(digest, agentReleaseManifestDigest({ ...item, artifactUrl: "https://releases.example.test/changed.tar.gz" })); const unsigned = { schemaVersion: "agent-upgrade-v1" as const, upgradeId: "upgrade-123456", serverId: "server-123456", expectedAgentId: "agent-123456", expectedCurrentVersion: "1.0.0", targetVersion: "1.1.0", releaseId: item.id, artifactSha256: item.artifactSha256, artifactSignature: item.artifactSignature, signatureKeyId: item.signatureKeyId, releaseManifestDigest: digest, operatingSystem: "linux", architecture: "x64", packageType: "tar" as const, requiredCapabilities: [], expiresAt: "2030-01-01T00:00:00.000Z", nonce: "nonce-1234567890123456" }; assert.notEqual(agentUpgradePlanDigest(unsigned), agentUpgradePlanDigest({ ...unsigned, serverId: "server-654321" })); assert.notEqual(agentUpgradePlanDigest(unsigned), agentUpgradePlanDigest({ ...unsigned, nonce: "nonce-6543210987654321" })); });

test("rollout digest binds exact set, strategy, thresholds, and environment", () => { const base = { releaseId: "release-110", serverIds: ["server-123456", "server-654321"], perServerPlanDigests: { "server-123456": "a".repeat(64), "server-654321": "b".repeat(64) }, strategy: "canary" as const, failureThreshold: 0, allowedEnvironments: ["staging"], expiresAt: "2030-01-01T00:00:00.000Z" }; const digest = fleetRolloutDigest(base); assert.notEqual(digest, fleetRolloutDigest({ ...base, failureThreshold: 1 })); assert.throws(() => fleetRolloutSchema.parse({ ...base, serverIds: ["server-123456", "server-123456"] })); assert.equal(nextRolloutAction({ state: "running", completed: 0, failed: 1, total: 3, failureThreshold: 0, canaryComplete: false }), "paused"); assert.equal(nextRolloutAction({ state: "running", completed: 3, failed: 0, total: 3, failureThreshold: 0, canaryComplete: true }), "complete"); });

test("semantic version comparison supports repository prerelease conventions", () => { assert.equal(compareAgentVersions("0.10.0-beta.1", "0.10.0-beta.2"), -1); assert.equal(compareAgentVersions("0.10.0-beta.2", "0.10.0"), -1); assert.equal(compareAgentVersions("0.10.0", "0.10.0-beta.2"), 1); assert.equal(compareAgentVersions("0.10.0-beta.10", "0.10.0-beta.2"), 1); });

test("bootstrap manifest rejects unknown fields, unsupported schemas, and incomplete artifact sets", () => { const artifacts = ["agent_package", "bootstrap_installer", "rollback_script", "release_catalog", "sbom"].map((role, index) => ({ role, filename: `artifact-${index}.bin`, sizeBytes: 1, sha256: "a".repeat(64) })); const manifest = { schemaVersion: "opsworkbench-agent-bootstrap-v1", releaseId: "agent-010-beta1", version: "0.10.0-beta.1", protocolVersion: "task-v1", buildTimestamp: "2026-07-19T00:00:00.000Z", sourceCommit: "b".repeat(40), supportedOperatingSystems: ["linux"], supportedDistributions: ["debian", "ubuntu"], supportedArchitectures: ["x64"], packageType: "tar", minimumSourceVersion: "0.1.0", maximumSourceVersion: "0.1.0", artifacts, requiredCapabilities: ["environmentDiscovery", "agentUpgrade", "upgradeManifestHandoff"], channel: "candidate", upgradeFrom: ["0.1.0"], rollbackTo: ["0.1.0"], publicationStatus: "draft", revoked: false, signingKeyId: "ed25519-synthetic", nonProductionOnly: true }; assert.equal(bootstrapReleaseManifestSchema.safeParse(manifest).success, true); assert.equal(bootstrapReleaseManifestSchema.safeParse({ ...manifest, schemaVersion: "future-v2" }).success, false); assert.equal(bootstrapReleaseManifestSchema.safeParse({ ...manifest, command: "sh" }).success, false); assert.equal(bootstrapReleaseManifestSchema.safeParse({ ...manifest, artifacts: artifacts.slice(1) }).success, false); });
