import assert from "node:assert/strict";
import test from "node:test";
import { configurationChangeDigest, configurationDeploymentPayloadSchema, deploymentProgressSchema, hasPermission, isCompatibleAgentVersion, isSafeHttpCheckUrl, redactedConfigurationDiff, taskPayloadSchema } from "../src/index.js";

const base = { schemaVersion: "configuration-deployment-v1", action: "configuration.apply.v1", planId: "123456789012", planRevision: 1, deploymentId: "123456789013", environmentId: "123456789014", environmentKind: "staging", protected: false, targetProfileId: "123456789015", targetProfileRevision: 1, repositoryRoot: "/tmp/app", environmentFilePath: "/tmp/app/.env.staging", composePath: "/tmp/app/compose.yml", composeProject: "fixture", statelessServices: ["web"], protectedServices: ["mongo"], healthChecks: [{ id: "web", url: "http://127.0.0.1:3000/healthz", timeoutMs: 1000 }], mutations: [{ name: "EXAMPLE", versionId: "123456789016", secret: true, operation: "rotate", valueRef: "v:1" }], encryptedValues: { algorithm: "aes-256-gcm", ciphertext: "AA==", nonce: "AA==", authTag: "AA==", keyVersion: "v1" }, expectedConfigurationDigest: "a".repeat(64), automaticRollback: true };

test("deployment schema permits typed non-production action", () => assert.equal(configurationDeploymentPayloadSchema.parse(base).environmentKind, "staging"));
test("deployment schema rejects production independently", () => assert.throws(() => configurationDeploymentPayloadSchema.parse({ ...base, environmentKind: "production" })));
test("deployment schema rejects protected targets", () => assert.throws(() => configurationDeploymentPayloadSchema.parse({ ...base, protected: true })));
test("deployment schema rejects stateful service overlap", () => assert.throws(() => configurationDeploymentPayloadSchema.parse({ ...base, statelessServices: ["mongo"] })));
test("deployment schema permits value-free remove and disable operations", () => { for (const operation of ["remove", "disable"]) assert.equal(configurationDeploymentPayloadSchema.parse({ ...base, mutations: [{ name: "EXAMPLE", versionId: "123456789016", secret: true, operation }] }).mutations[0].operation, operation); });
test("change approval digest is value-free, deterministic, and mutation-bound", () => { const first = configurationChangeDigest([{ name: "B", operation: "remove", secret: false, versionId: "v-123456789012" }, { name: "A", operation: "rotate", secret: true, versionId: "v-123456789013" }]); const reordered = configurationChangeDigest([{ name: "A", operation: "rotate", secret: true, versionId: "v-123456789013" }, { name: "B", operation: "remove", secret: false, versionId: "v-123456789012" }]); assert.equal(first, reordered); assert.notEqual(first, configurationChangeDigest([{ name: "A", operation: "remove", secret: true, versionId: "v-123456789013" }])); assert.doesNotMatch(first, /secret|rotate|remove/); });
test("proposed diffs contain no configuration values", () => { const diff = redactedConfigurationDiff([{ name: "API_SECRET", operation: "rotate", secret: true }, { name: "FEATURE", operation: "update", secret: false }]); assert.deepEqual(diff, [{ name: "API_SECRET", operation: "rotate", classification: "secret", proposedValue: "[redacted]" }, { name: "FEATURE", operation: "update", classification: "non-secret", proposedValue: "[pending value]" }]); });
test("task payload rejects unknown fields", () => assert.throws(() => taskPayloadSchema.parse({ unknown: true })));
test("progress schema prevents secret-shaped extra fields", () => assert.throws(() => deploymentProgressSchema.parse({ phase: "failed", progress: 1, changedVariables: 0, services: [], healthChecksPassed: 0, secret: "bad" })));
test("only owners and administrators may deploy and approve", () => { assert.equal(hasPermission("Owner", "configuration:deploy-non-production"), true); assert.equal(hasPermission("Administrator", "configuration:approve-non-production"), true); assert.equal(hasPermission("Developer", "configuration:deploy-non-production"), false); });
test("deployment agent versions use stable semantic comparison", () => { assert.equal(isCompatibleAgentVersion("0.1.0"), true); assert.equal(isCompatibleAgentVersion("0.1.1"), true); assert.equal(isCompatibleAgentVersion("1.0.0"), true); for (const value of [undefined, "", "0.0.9", "0.1", "0.1.0-beta.1", "v0.1.0", "00.1.0"]) assert.equal(isCompatibleAgentVersion(value), false); });
test("health URL validation rejects SSRF and credential-bearing targets", () => { for (const value of ["ftp://example.com", "http://user:pass@example.com", "https://example.com/health?token=secret", "https://example.com/health#secret", "http://localhost", "http://api.localhost", "http://127.0.0.1", "http://2130706433", "http://10.0.0.1", "http://172.16.0.1", "http://192.168.1.1", "http://169.254.169.254/latest/meta-data", "http://metadata.google.internal", "http://[::1]", "http://[fc00::1]", "http://[fe80::1]", "http://[::ffff:127.0.0.1]"]) assert.equal(isSafeHttpCheckUrl(value), false, value); assert.equal(isSafeHttpCheckUrl("https://health.example.com/status"), true); });
