import test from "node:test";
import assert from "node:assert/strict";
import {
  payloadDigest, taskPayloadForSigning, taskPayloadSchema,
} from "../src/tasks.js";
import {
  privilegedActionDigest, privilegedSubPayload, privilegedSubPayloadForSigning,
} from "../src/ownerAuthorization.js";

// ─────────────────────────────────────────────────────────────────────────────────────────────────
// CONFORMANCE VECTORS FOR THE PAYLOAD SERIALIZATION CONTRACT.
//
// `payloadDigest` is sha256(JSON.stringify(x)) with no canonicalisation, so KEY ORDER decides it, and
// everything downstream digests the zod-PARSED payload. That is a live trap for any offline owner
// signing tool or binder: build the object by hand with the same fields in a different order and every
// correct authorization is refused, reporting only "Owner authorization invalid" or
// `action_digest_mismatch`. It fails closed, so it is not a hole; it is an unusable protocol for anyone
// who has not been told the rule.
//
// These vectors say the rule in a form another implementation can check itself against WITHOUT running
// this code: a fixed payload, the exact digest it must produce, and a proof that a differently-ordered
// build of the same fields produces a different one. If a change to a schema's DECLARATION ORDER moves
// a digest here, that is a protocol change and this file is where it shows up — which is the second
// reason these are pinned constants rather than round-trips.
// ─────────────────────────────────────────────────────────────────────────────────────────────────

/** The mutations, in the order the schema declares their fields. */
const MUTATIONS = [
  { name: "DATABASE_URL", versionId: "v-000000000001", secret: true, operation: "update" as const, valueRef: "ref-1" },
];

/**
 * A configuration.apply task payload, written in SCHEMA-DECLARATION ORDER at every level.
 *
 * Deliberately hand-ordered rather than produced by the parser: a vector generated by the thing it
 * describes tests nothing. The assertions below check that parsing does not move it.
 */
const VECTOR = {
  projects: [],
  httpHealthChecks: [],
  mongoChecks: [],
  configurationDeployment: {
    schemaVersion: "configuration-deployment-v1",
    action: "configuration.apply.v1",
    planId: "plan-00000000001",
    planRevision: 1,
    deploymentId: "deploy-000000001",
    environmentId: "env-000000000001",
    environmentKind: "staging",
    protected: false,
    targetProfileId: "profile-00000001",
    targetProfileRevision: 3,
    repositoryRoot: "/srv/app",
    environmentFilePath: "/srv/app/.env",
    composePath: "/srv/app/docker-compose.yml",
    composeProject: "app",
    statelessServices: ["web"],
    protectedServices: [],
    healthChecks: [{ id: "web", url: "https://health.example.test/healthz", timeoutMs: 1000 }],
    mutations: MUTATIONS,
    encryptedValues: {
      algorithm: "aes-256-gcm", ciphertext: "Y2lwaGVy", nonce: "bm9uY2U=",
      authTag: "dGFn", keyVersion: "agent-signing-v1",
    },
    expectedConfigurationDigest: "e".repeat(64),
    // BEFORE `automaticRollback`, and this is not a stylistic choice. The first draft of this vector
    // had the two the other way round -- the order they read naturally in -- and the parser silently
    // moved them, changing the digest. That is the whole trap, and it caught the person writing the
    // file about it. `parsing does not reorder` below is what noticed.
    reviewAuthorization: { attestationId: "att-000000000001", leaseId: "lease-00000000001" },
    automaticRollback: true,
  },
};

// THE VECTORS. Any implementation that produces different bytes for this payload is not speaking this
// protocol, whatever its fields say.
const TASK_PAYLOAD_DIGEST = "6639cafaca5dd798ab78e362a912aa1977d1da46c1636bfc79bee3f17729403d";
const SUB_PAYLOAD_DIGEST = "4654c49236e571b4755a6193912a74776f48bd89ff8214adb39a8fe19998cb39";

test("the task payload vector digests to a fixed value", () => {
  const parsed = taskPayloadForSigning(VECTOR);
  assert.equal(payloadDigest(parsed), TASK_PAYLOAD_DIGEST);
  // The owner signs the ACTION digest, which is the payload minus its own signature block. With no
  // ownerAuthorization present the two coincide, and that is worth stating: it is why an owner tool can
  // sign before the field it will fill in exists.
  assert.equal(privilegedActionDigest(parsed), TASK_PAYLOAD_DIGEST);
});

test("the privileged sub-payload vector digests to a different fixed value", () => {
  // TWO SCOPES FOR ONE ACTION, and they are not interchangeable. Layer 2 signs
  // `privilegedActionDigest(taskPayload)`; the review gate binds
  // `privilegedActionDigest(subPayload)`. An executor that digests the wrong one is refused every
  // privileged task, which fails closed and makes enforcement unusable -- and the way that gets "fixed"
  // in a hurry is by turning enforcement off.
  const sub = privilegedSubPayloadForSigning("configuration.apply", taskPayloadForSigning(VECTOR));
  assert.equal(privilegedActionDigest(sub), SUB_PAYLOAD_DIGEST);
  assert.notEqual(SUB_PAYLOAD_DIGEST, TASK_PAYLOAD_DIGEST);
});

test("parsing does not reorder a payload that was already in schema order", () => {
  // The vector above is the normative form. If this fails, the vector is wrong, not the parser.
  assert.equal(JSON.stringify(taskPayloadForSigning(VECTOR)), JSON.stringify(VECTOR));
});

test("KEY ORDER DECIDES THE DIGEST, and this is the trap the contract exists for", () => {
  // The same fields, the same values, one pair swapped near the top of the sub-payload.
  const reordered = {
    ...VECTOR,
    configurationDeployment: {
      action: VECTOR.configurationDeployment.action,
      schemaVersion: VECTOR.configurationDeployment.schemaVersion,
      ...Object.fromEntries(Object.entries(VECTOR.configurationDeployment)
        .filter(([key]) => key !== "action" && key !== "schemaVersion")),
    },
  };
  assert.deepEqual(reordered, VECTOR, "identical as objects -- deepEqual cannot see the difference");
  assert.notEqual(payloadDigest(reordered), TASK_PAYLOAD_DIGEST,
    "and yet a different digest, which is the whole problem");

  // AND THE FIX IS THE ONE SENTENCE IN THE CONTRACT: parse, then digest. The parser emits schema order
  // whatever order it was handed, so a tool that parses first cannot get this wrong.
  assert.equal(payloadDigest(taskPayloadForSigning(reordered)), TASK_PAYLOAD_DIGEST);
  assert.equal(
    privilegedActionDigest(privilegedSubPayloadForSigning("configuration.apply", reordered)),
    SUB_PAYLOAD_DIGEST);
});

test("the signing helpers refuse a payload that could never be dispatched", () => {
  // Validation is not incidental here. Signing an unparseable payload produces an authorization that
  // nothing will ever accept, and the owner finds out at the far end of an offline ceremony.
  assert.throws(() => taskPayloadForSigning({ ...VECTOR, projects: "not an array" }));
  assert.throws(() => privilegedSubPayloadForSigning("configuration.apply", {
    configurationDeployment: { ...VECTOR.configurationDeployment, planRevision: "one" },
  }));
});

test("an unwired task type yields no sub-payload to sign, rather than an empty one", () => {
  // `payloadDigest(undefined)` is the digest of `{}` -- a perfectly valid-looking hex string for a
  // payload that does not exist. The helper returns undefined so a caller has to notice, and matches
  // `privilegedSubPayload`, which an enforcing executor already treats as a refusal.
  assert.equal(privilegedSubPayloadForSigning("collect.system", VECTOR), undefined);
  assert.equal(privilegedSubPayload("collect.system", VECTOR), undefined);
  assert.equal(privilegedSubPayloadForSigning("configuration.apply", { projects: [] }), undefined);
});

test("the vector is a payload the schema actually accepts", () => {
  // Otherwise these vectors would pin the digest of something that can never be dispatched.
  assert.doesNotThrow(() => taskPayloadSchema.parse(VECTOR));
});
