import React, { useEffect, useState } from "react";
import { toast } from "sonner";
import { CheckCircle2, XCircle, ShieldAlert, RefreshCw, PlayCircle, ShieldCheck } from "lucide-react";
import {
  fetchRefundApprovals, approveRefund, denyRefund, adminRefundOrder,
} from "../../lib/api";
import { formatDate } from "./_shared";
import { useConfirm } from "../../hooks/useConfirm";
import { RowsSkeleton } from "../Skeleton";
import EmptyState from "../EmptyState";

/** Refund Approvals tab — surfaces all pending high-stakes refund requests
 *  generated by the two-person rule. The admin who CREATED the request
 *  cannot approve it themselves; a different admin must click Approve, then
 *  the original (or any other) admin can execute the actual refund. */
export default function RefundApprovalsTab({ me }) {
  const [filter, setFilter] = useState("pending");
  const [data, setData] = useState(null);
  const [loading, setLoading] = useState(true);
  const [busy, setBusy] = useState("");
  const [confirm, confirmModal] = useConfirm();

  const load = async () => {
    setLoading(true);
    try {
      setData(await fetchRefundApprovals(filter));
    } catch (e) {
      toast.error(e?.response?.data?.detail || "Couldn't load approvals.");
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => { load(); /* eslint-disable-next-line */ }, [filter]);

  const onApprove = async (id) => {
    const ok = await confirm({
      title: "Approve refund request?",
      body: "The original requester (or any admin) will then be able to execute the refund.",
      confirmLabel: "Approve",
      tone: "primary",
      testId: `confirm-approve-refund-${id}`,
    });
    if (!ok) return;
    setBusy(id);
    try {
      await approveRefund(id);
      toast.success("Approval granted.");
      load();
    } catch (e) {
      toast.error(e?.response?.data?.detail || "Approve failed.");
    } finally { setBusy(""); }
  };

  const onDeny = async (id) => {
    const ok = await confirm({
      title: "Deny this refund request?",
      body: "The requester will need to re-submit if circumstances change.",
      confirmLabel: "Deny",
      tone: "danger",
      testId: `confirm-deny-refund-${id}`,
    });
    if (!ok) return;
    setBusy(id);
    try {
      await denyRefund(id);
      toast.success("Approval denied.");
      load();
    } catch (e) {
      toast.error(e?.response?.data?.detail || "Deny failed.");
    } finally { setBusy(""); }
  };

  const onExecute = async (ap) => {
    const ok = await confirm({
      title: `Execute refund of $${ap.amount.toFixed(2)}?`,
      body: "This reverses the buyer's charge and every maker payout. This cannot be undone.",
      confirmLabel: "Execute refund",
      tone: "danger",
      testId: `confirm-execute-refund-${ap.id}`,
    });
    if (!ok) return;
    setBusy(ap.id);
    try {
      await adminRefundOrder(ap.session_id, ap.id);
      toast.success("Refund executed — buyer + maker reversals fired.");
      load();
    } catch (e) {
      toast.error(e?.response?.data?.detail || "Execution failed.");
    } finally { setBusy(""); }
  };

  return (
    <div className="space-y-8" data-testid="refund-approvals-tab">
      {confirmModal}
      <div className="flex items-end justify-between gap-4 flex-wrap">
        <div>
          <div className="font-mono text-[11px] uppercase tracking-[0.3em] text-brand mb-1">◆ Two-person rule</div>
          <h2 className="font-display text-3xl uppercase">Refund Approvals.</h2>
          <p className="font-mono text-xs text-ink-muted mt-2 max-w-[60ch]">
            Refunds at or above <span className="text-brand">${data?.threshold_usd ?? 500}</span> require
            a second admin to approve before they can be executed. The requester cannot approve their own request.
          </p>
        </div>
        <div className="flex items-center gap-2">
          <select
            value={filter} onChange={(e) => setFilter(e.target.value)}
            className="bg-paper border border-line focus:border-brand outline-none px-3 py-2 font-mono text-xs"
            data-testid="approvals-filter"
          >
            <option value="pending">Pending</option>
            <option value="approved">Approved (awaiting execution)</option>
            <option value="executed">Executed</option>
            <option value="denied">Denied</option>
            <option value="all">All</option>
          </select>
          <button
            onClick={load}
            className="px-3 py-2 border border-line hover:border-brand font-mono text-[10px] uppercase tracking-[0.22em] inline-flex items-center gap-2"
            data-testid="approvals-refresh"
          >
            <RefreshCw size={12} className={loading ? "animate-spin" : ""} /> Refresh
          </button>
        </div>
      </div>

      {loading || !data ? (
        <div data-testid="refund-approvals-loading"><RowsSkeleton count={4} /></div>
      ) : data.approvals.length === 0 ? (
        <EmptyState
          icon={filter === "pending" ? ShieldCheck : ShieldAlert}
          eyebrow="◆ Two-person rule"
          title={filter === "pending" ? "Nothing awaiting approval." : `No ${filter === "all" ? "" : filter} approvals.`}
          body={
            filter === "pending"
              ? `Refunds at or above $${data?.threshold_usd ?? 500} require a second admin to sign off. They'll show up here the moment a request is filed.`
              : "Switch the filter to 'Pending' to see active approval requests."
          }
          testId="approvals-empty"
        />
      ) : (
        <div className="space-y-3">
          {data.approvals.map((ap) => {
            const isMine = me?.email && ap.requested_by?.toLowerCase() === me.email.toLowerCase();
            const canApprove = ap.status === "pending" && !isMine;
            const canExecute = ap.status === "approved";
            return (
              <div key={ap.id} className="border border-line p-4 grid md:grid-cols-[1fr_auto] gap-4 items-start" data-testid={`approval-row-${ap.id}`}>
                <div className="min-w-0">
                  <div className="flex items-center gap-2 flex-wrap">
                    <span className={`font-mono text-[10px] uppercase tracking-[0.22em] px-2 py-0.5 border ${
                      ap.status === "pending" ? "border-amber-500 text-amber-400" :
                      ap.status === "approved" ? "border-cyan-500 text-cyan-400" :
                      ap.status === "executed" ? "border-emerald-500 text-emerald-400" :
                      "border-line text-ink-muted"
                    }`}>
                      {ap.status}
                    </span>
                    <span className="font-display text-3xl text-brand">${ap.amount.toFixed(2)}</span>
                  </div>
                  <div className="font-mono text-xs text-ink mt-2 truncate">
                    Session: <span className="text-ink-muted">{ap.session_id?.slice(0, 32)}…</span>
                  </div>
                  <div className="font-mono text-[11px] text-ink-muted mt-1">
                    {ap.buyer_email || "no buyer email"} · requested by <span className="text-ink-muted">{ap.requested_by}</span>
                    {" · "}{formatDate(ap.requested_at)}
                  </div>
                  {ap.approved_by && (
                    <div className="font-mono text-[10px] text-cyan-300 mt-1">
                      ✓ Approved by {ap.approved_by} · {formatDate(ap.approved_at)}
                    </div>
                  )}
                  {ap.denied_by && (
                    <div className="font-mono text-[10px] text-red-400 mt-1">
                      ⊗ Denied by {ap.denied_by} · {formatDate(ap.denied_at)}
                    </div>
                  )}
                  {ap.executed_at && (
                    <div className="font-mono text-[10px] text-emerald-400 mt-1">
                      ✓ Executed · {formatDate(ap.executed_at)}
                    </div>
                  )}
                  {isMine && ap.status === "pending" && (
                    <div className="font-mono text-[10px] text-amber-300 mt-2">
                      ◆ You requested this refund — a different admin must approve it.
                    </div>
                  )}
                </div>
                <div className="flex items-center gap-2">
                  {canApprove && (
                    <>
                      <button
                        onClick={() => onApprove(ap.id)} disabled={busy === ap.id}
                        className="px-3 py-2 border border-cyan-500 text-cyan-400 hover:bg-cyan-500/10 font-mono text-[10px] uppercase tracking-[0.22em] inline-flex items-center gap-2 disabled:opacity-50"
                        data-testid={`approval-approve-${ap.id}`}
                      >
                        <CheckCircle2 size={12} /> Approve
                      </button>
                      <button
                        onClick={() => onDeny(ap.id)} disabled={busy === ap.id}
                        className="px-3 py-2 border border-line text-red-400 hover:bg-red-500/10 font-mono text-[10px] uppercase tracking-[0.22em] inline-flex items-center gap-2 disabled:opacity-50"
                        data-testid={`approval-deny-${ap.id}`}
                      >
                        <XCircle size={12} /> Deny
                      </button>
                    </>
                  )}
                  {canExecute && (
                    <button
                      onClick={() => onExecute(ap)} disabled={busy === ap.id}
                      className="btn-industrial btn-primary inline-flex items-center gap-2 disabled:opacity-50"
                      data-testid={`approval-execute-${ap.id}`}
                    >
                      <PlayCircle size={14} /> {busy === ap.id ? "Refunding…" : "Execute Refund"}
                    </button>
                  )}
                </div>
              </div>
            );
          })}
        </div>
      )}
    </div>
  );
}
