import React, { useEffect, useState } from "react";
import { toast } from "sonner";
import { addAdminCaseNote, approveAdminCaseReplacement, approveAdminCaseReturn, closeAdminCase, denyAdminCase, executeAdminCaseRefund, fetchAdminReturnCase, fetchAdminReturnCaseAnalytics, fetchAdminReturnCases, linkAdminProviderDispute, reopenAdminCase, updateAdminCaseDeadline } from "../../lib/api";

const money = (n) => `$${Number(n || 0).toFixed(2)}`;

export default function ReturnsDisputesTab() {
  const [cases, setCases] = useState([]); const [active, setActive] = useState(null); const [detail, setDetail] = useState(null); const [analytics, setAnalytics] = useState(null);
  const [status, setStatus] = useState(""); const [q, setQ] = useState(""); const [amount, setAmount] = useState(""); const [note, setNote] = useState(""); const [reason, setReason] = useState(""); const [busy, setBusy] = useState(false);
  const load = () => { fetchAdminReturnCases({ status: status || undefined, q: q || undefined }).then((r) => setCases(r.cases || [])).catch(() => toast.error("Could not load cases.")); fetchAdminReturnCaseAnalytics().then(setAnalytics).catch(() => {}); };
  // eslint-disable-next-line react-hooks/exhaustive-deps
  useEffect(() => { load(); }, [status]); useEffect(() => { if (active) fetchAdminReturnCase(active).then(setDetail).catch(() => toast.error("Could not load case.")); }, [active]);
  async function act(fn, ok) { if (!detail) return; setBusy(true); try { const r = await fn(); toast.success(ok); setDetail(r.case || r); load(); } catch (e) { toast.error(e?.response?.data?.detail || "Action failed."); } finally { setBusy(false); } }
  return <section data-testid="admin-resolution-center" className="space-y-5">
    <div><h2 className="font-display text-3xl text-ink">Returns & Disputes</h2><p className="font-mono text-xs text-ink-muted">Resolution Center for internal cases and provider dispute placeholders.</p></div>
    {analytics && <div className="grid md:grid-cols-5 gap-3" data-testid="case-analytics"><Stat label="Cases" value={analytics.total_cases}/><Stat label="Case rate" value={`${Math.round((analytics.case_rate || 0) * 1000) / 10}%`}/><Stat label="Refunds" value={analytics.refund_count}/><Stat label="Refund amount" value={money(analytics.refund_amount)}/><Stat label="Escalation" value={`${Math.round((analytics.escalation_rate || 0) * 1000) / 10}%`}/></div>}
    <div className="flex flex-wrap gap-2"><select value={status} onChange={(e) => setStatus(e.target.value)} className="input-industrial w-56"><option value="">All cases</option><option value="waiting_for_maker">Waiting maker</option><option value="waiting_for_buyer">Waiting buyer</option><option value="return_in_transit">Return in transit</option><option value="refund_pending">Refund pending</option><option value="under_admin_review">Admin review</option><option value="payment_dispute_open">Provider disputes</option><option value="closed">Closed</option></select><input value={q} onChange={(e) => setQ(e.target.value)} onKeyDown={(e) => e.key === "Enter" && load()} className="input-industrial w-72" placeholder="Search case, order, buyer, maker"/><button onClick={load} className="btn-industrial">Search</button></div>
    <div className="grid xl:grid-cols-[420px_1fr] gap-4"><div className="border border-line bg-paper divide-y divide-line" data-testid="admin-case-list">{cases.length === 0 && <p className="p-4 font-mono text-xs text-ink-muted">No cases.</p>}{cases.map((c) => <button key={c.id} onClick={() => setActive(c.id)} className={`w-full text-left p-4 hover:bg-surface ${active === c.id ? "bg-brand/10" : ""}`} data-testid={`admin-case-${c.id}`}><div className="font-mono text-xs text-ink">{c.public_case_number} · {c.current_status}</div><div className="font-mono text-[10px] text-ink-muted">{c.buyer_email} · {c.maker_id} · {money(c.amount_at_risk)}</div><div className="font-mono text-[10px] text-ink-muted">{c.payment_provider}{c.payment_provider_dispute_id ? ` · ${c.payment_provider_dispute_id}` : ""}</div></button>)}</div>
      <div className="border border-line bg-paper p-5 min-h-[520px]" data-testid="admin-case-detail">{!detail ? <p className="font-mono text-xs text-ink-muted">Select a case.</p> : <>
        <div className="flex flex-wrap justify-between gap-3 mb-4"><div><h3 className="font-display text-2xl">{detail.public_case_number}</h3><p className="font-mono text-xs text-ink-muted">Order {detail.order_id} · buyer {detail.buyer_email} · maker {detail.maker_id}</p></div><span className="font-mono text-xs border border-line px-2 py-1 h-fit">{detail.current_status}</span></div>
        <div className="grid md:grid-cols-2 gap-3 mb-4">{(detail.items || []).map((i) => <div key={i.id} className="border border-line/70 p-3"><div className="font-mono text-xs text-ink">{i.title}</div><div className="font-mono text-[10px] text-ink-muted">Qty {i.quantity_affected} · {i.is_custom ? "custom" : "standard"} · {i.is_digital ? "digital" : "physical"}</div></div>)}</div>
        {detail.return_authorization && <div className="border border-brand/50 p-3 mb-4" data-testid="admin-return-authorization"><b className="font-mono text-[10px] uppercase text-brand">RA {detail.return_authorization.authorization_number}</b><p className="font-mono text-xs text-ink-muted">{detail.return_authorization.return_instructions}</p></div>}
        <div className="grid md:grid-cols-3 gap-2 mb-4"><button onClick={() => act(() => approveAdminCaseReturn(detail.id, { shipping_paid_by: "buyer" }), "Return approved.")} className="btn-industrial" disabled={busy}>Approve return</button><button onClick={() => act(() => executeAdminCaseRefund(detail.id, { amount: amount ? Number(amount) : undefined, reason: reason || "Admin case refund" }), "Refund executed.")} className="btn-industrial btn-primary" disabled={busy}>Execute refund</button><button onClick={() => act(() => approveAdminCaseReplacement(detail.id, { notes: reason || "Admin replacement" }), "Replacement approved.")} className="btn-industrial" disabled={busy}>Approve replacement</button><button onClick={() => act(() => denyAdminCase(detail.id, { reason: reason || "Admin denied" }), "Case denied.")} className="border border-red-500 text-red-400 px-3 py-2 font-mono text-[10px] uppercase" disabled={busy}>Deny</button><button onClick={() => act(() => closeAdminCase(detail.id, { reason: reason || "Closed by admin" }), "Case closed.")} className="btn-industrial" disabled={busy}>Close</button><button onClick={() => act(() => reopenAdminCase(detail.id, { reason: reason || "Reopened by admin" }), "Case reopened.")} className="btn-industrial" disabled={busy}>Reopen</button></div>
        <div className="grid md:grid-cols-2 gap-2 mb-4"><input value={amount} onChange={(e) => setAmount(e.target.value)} className="input-industrial" placeholder={`Refund amount, max ${money(detail.remaining_refundable_amount)}`}/><input value={reason} onChange={(e) => setReason(e.target.value)} className="input-industrial" placeholder="Reason / decision notes"/></div>
        <div className="border border-line p-3 mb-4"><div className="font-mono text-[10px] uppercase text-ink-muted mb-2">Provider dispute link</div><button onClick={() => { const id = prompt("Provider dispute ID"); if (id) act(() => linkAdminProviderDispute(detail.id, { payment_provider: detail.payment_provider || "stripe", payment_provider_dispute_id: id, amount_at_risk: detail.amount_at_risk }), "Provider dispute linked."); }} className="btn-industrial">Link provider dispute</button></div>
        <div className="border border-line p-3 mb-4"><div className="font-mono text-[10px] uppercase text-ink-muted mb-2">Deadlines</div><button onClick={() => act(() => updateAdminCaseDeadline(detail.id, { field: "maker_response_due_at", value: new Date(Date.now() + 86400000).toISOString(), reason: reason || "Admin extension" }), "Deadline updated.")} className="btn-industrial">Extend maker response 1 day</button></div>
        <div className="grid md:grid-cols-2 gap-4"><div><h4 className="font-mono text-[10px] uppercase text-ink-muted mb-2">Messages</h4>{(detail.messages || []).map((m) => <div key={m.id} className={`mb-2 font-mono text-xs ${m.visibility === "admin_internal" ? "text-yellow-600" : "text-ink-muted"}`}><b>{m.sender_role}</b>: <span dangerouslySetInnerHTML={{ __html: m.message_body }} /></div>)}</div><div><h4 className="font-mono text-[10px] uppercase text-ink-muted mb-2">Internal note</h4><textarea value={note} onChange={(e) => setNote(e.target.value)} className="input-industrial w-full" rows={4}/><button onClick={() => act(() => addAdminCaseNote(detail.id, { message_body: note }), "Internal note added.").then(() => setNote(""))} className="btn-industrial mt-2" disabled={!note.trim()}>Add internal note</button></div></div>
      </>}</div></div>
  </section>;
}
function Stat({ label, value }) { return <div className="border border-line bg-paper p-3"><div className="font-mono text-[9px] uppercase text-ink-muted">{label}</div><div className="font-display text-xl text-ink">{value}</div></div>; }


