import assert from "node:assert/strict";
import crypto from "node:crypto";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { execFileSync } from "node:child_process";
import test from "node:test";
import { fileURLToPath } from "node:url";
import { FORGE_OWNER_PUBLIC_KEY, FORGE_OWNER_PUBLIC_KEY_SHA256 } from "../src/forgeOwnerTrust.js";
import { forgeSecurityIdentityStatement, loadForgeSecurityMaterial, type SecurityPathPolicy } from "../src/forgeSecurityIdentity.js";

// THE OWNER-KEY PIN, WHICH NOTHING TESTED.
//
// `forgeOwnerTrust.ts` says changing its value is a security-boundary change requiring owner-key
// rotation evidence, and until now no test looked at it at all. That matters most at the moment it is
// about to change: custody of the current private half is unconfirmed, a rotation is authorised, and the
// commit that performs it will edit exactly these two constants.
//
// So these tests exist to make that commit safe rather than to check today's value is pretty. They prove
// the pin is enforced, that it is the module's own constants doing the enforcing, that the two constants
// agree with each other, and that every other key is refused fail-closed. After a rotation, the only
// additions are the retired key in the refusal list below and the new expected values.
const here = path.dirname(fileURLToPath(import.meta.url));
const scripts = path.resolve(here, "..", "..", "..", "scripts");
const node = (script: string, args: string[]) => execFileSync(process.execPath, [path.join(scripts, script), ...args], { encoding: "utf8" });
const sha256 = (bytes: Buffer) => crypto.createHash("sha256").update(bytes).digest("hex");

const org = "6a5dab47776e3028ac9b604b";
const server = "6a5f685ff8195a8813879bd7";
const hostname = "Ops-Workbench";
const machineId = "the-machine-id";

// EVERY KEY THIS RELEASE MUST REFUSE, by value. Empty today because there has never been a rotation.
// The rotation commit adds the retired anchor here, so the refusal is proved against the ACTUAL former
// key rather than against a freshly generated stand-in that merely happens to differ. It is a list
// rather than a single value because a second rotation must not retire the first retirement.
const retiredOwnerKeys: Array<{ what: string; publicKey: string }> = [];

/** Build and sign a complete identity with whichever key is given, then install it for the loader. */
function identitySignedBy(privateKeyPem: string, publicKeyBase64Url: string) {
  const root = fs.mkdtempSync(path.join(os.tmpdir(), "forge-pin-"));
  const security = path.join(root, "etc", "opsworkbench-forge");
  fs.mkdirSync(security, { recursive: true, mode: 0o755 });
  for (const directory of [root, path.join(root, "etc"), security]) fs.chmodSync(directory, 0o755);

  const trustedRootPath = path.join(security, "trusted-root.json");
  const reviewGateCaPath = path.join(security, "review-gate-ca.pem");
  fs.writeFileSync(trustedRootPath, `${JSON.stringify({ mediaType: "application/vnd.dev.sigstore.trustedroot+json;version=0.1", tlogs: [] })}\n`, { mode: 0o444 });
  fs.writeFileSync(reviewGateCaPath, "-----BEGIN CERTIFICATE-----\npinned\n-----END CERTIFICATE-----\n", { mode: 0o444 });

  const unsigned = {
    schemaVersion: "forge-security-identity-v1",
    orgId: org,
    serverId: server,
    ownerPublicKey: publicKeyBase64Url,
    trustedRootSha256: sha256(fs.readFileSync(trustedRootPath)),
    reviewGateCaSha256: sha256(fs.readFileSync(reviewGateCaPath)),
    hostname,
    machineIdSha256: sha256(Buffer.from(machineId)),
    validFrom: "2026-09-01T00:00:00.000Z",
    validUntil: "2027-09-01T00:00:00.000Z",
  };
  const ownerSignature = crypto.sign(null, forgeSecurityIdentityStatement(unsigned), crypto.createPrivateKey(privateKeyPem)).toString("base64url");
  const identityPath = path.join(security, "identity.json");
  fs.writeFileSync(identityPath, `${JSON.stringify({ ...unsigned, ownerSignature }, null, 2)}\n`, { mode: 0o444 });

  const policy: SecurityPathPolicy = {
    directory: security, identityPath, trustedRootPath, reviewGateCaPath,
    expectedUid: process.getuid?.() ?? 0, expectedGid: process.getgid?.() ?? 0,
    directoryMode: 0o755, fileMode: 0o444, hostname, machineId,
    ancestorBoundary: root,
  };
  return { root, policy };
}

/** A throwaway key pair, generated by the repository's own tool so the encoding is the real one. */
function throwawayKey() {
  const directory = path.join(fs.mkdtempSync(path.join(os.tmpdir(), "forge-key-")), "k");
  node("generate-forge-owner-key.mjs", [directory]);
  return {
    privateKeyPem: fs.readFileSync(path.join(directory, "forge-owner-private.pem"), "utf8"),
    publicKey: JSON.parse(fs.readFileSync(path.join(directory, "forge-owner-public.json"), "utf8")).publicKey as string,
  };
}

test("the two pinned constants describe the same key", () => {
  // THE ROTATION FOOT-GUN. The pin is two values that must agree, and a rotation edits both by hand.
  // Update one and not the other and the loader refuses every identity, including a correct one, with a
  // message about the trust anchor — which reads like the ceremony went wrong rather than like a typo.
  // Nothing checked this before.
  assert.match(FORGE_OWNER_PUBLIC_KEY, /^[A-Za-z0-9_-]+$/, "base64url, as the loader parses it");
  assert.equal(sha256(Buffer.from(FORGE_OWNER_PUBLIC_KEY, "base64url")), FORGE_OWNER_PUBLIC_KEY_SHA256, "the digest constant is the digest of the key constant");
  const parsed = crypto.createPublicKey({ key: Buffer.from(FORGE_OWNER_PUBLIC_KEY, "base64url"), format: "der", type: "spki" });
  assert.equal(parsed.asymmetricKeyType, "ed25519", "and it is an Ed25519 key");
});

test("an identity signed by the pinned key is accepted", { skip: process.platform === "win32" }, () => {
  // The positive case has to exist or the refusals below prove only that the loader refuses everything.
  // Signing needs the private half, which is offline and unavailable — so this asserts the reachable
  // half: an identity NAMING the pinned key gets past the anchor comparison and fails at the signature,
  // which is the next check. A test that cannot tell those two apart would pass for the wrong reason.
  const stand = throwawayKey();
  const { policy } = identitySignedBy(stand.privateKeyPem, FORGE_OWNER_PUBLIC_KEY);
  assert.throws(() => loadForgeSecurityMaterial(policy), (error: Error) => {
    assert.match(error.message, /owner signature is invalid/, "reached the signature check, so the anchor comparison passed");
    assert.doesNotMatch(error.message, /trust anchor/, "and did not stop at the anchor");
    return true;
  });
});

test("any key that is not the pin is refused, including every key this release has retired", { skip: process.platform === "win32" }, () => {
  // FAIL CLOSED, and fail EARLY. A key that is not the pin must be rejected because it is not the pin,
  // before any signature is checked — otherwise a valid signature by an unauthorised key is doing work.
  //
  // Generated keys and retired ones are the same case and share a loop deliberately. Keeping the retired
  // ones in a separate test meant a test that skipped until the day it mattered, and a rule proved only
  // by a test nobody has ever seen run is not proved.
  const unauthorised = [
    ...Array.from({ length: 3 }, (_unused, index) => {
      const generated = throwawayKey();
      return { what: `a freshly generated key (${index + 1})`, publicKey: generated.publicKey };
    }),
    ...retiredOwnerKeys,
  ];
  for (const candidate of unauthorised) {
    assert.notEqual(candidate.publicKey, FORGE_OWNER_PUBLIC_KEY, `${candidate.what} must not be the current pin`);
    // Signed by a key the loader has never seen, and NAMING the unauthorised key: that is the shape an
    // attacker's document has, and the shape a retired owner's document has after a rotation.
    const signer = throwawayKey();
    const { policy } = identitySignedBy(signer.privateKeyPem, candidate.publicKey);
    assert.throws(
      () => loadForgeSecurityMaterial(policy),
      /owner public key does not match the reviewed release trust anchor/,
      `${candidate.what} is refused at the anchor`,
    );
  }
});

test("STRUCTURAL: the loader defaults to the module's pin rather than to its caller", () => {
  // `expectedOwnerPublicKey` is an override so the ceremony suite can run against a throwaway key. If it
  // ever stopped defaulting to the module constant, every test that passes an override would still pass
  // and production would trust whatever its caller supplied. The tests above cannot see that, because
  // they exercise the override path themselves.
  const source = fs.readFileSync(new URL("../src/forgeSecurityIdentity.ts", import.meta.url), "utf8");
  const compact = source.replace(/\s+/g, "");
  assert.equal(compact.includes("policy.expectedOwnerPublicKey??FORGE_OWNER_PUBLIC_KEY"), true, "the key falls back to the pin");
  assert.equal(compact.includes("policy.expectedOwnerPublicKeySha256??FORGE_OWNER_PUBLIC_KEY_SHA256"), true, "and so does its digest");
  assert.equal(compact.includes("identity.ownerPublicKey!==expectedOwnerPublicKey||sha256(publicKeyBytes)!==expectedOwnerPublicKeySha256"), true, "and both are compared, not just one");
});
