import { useMemo, useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { api, apiError } from "./api";
import { Badge, Button, Card, GhostButton, Select, Table } from "./ui";

type Inventory = { serverId: string; name: string; slug?: string; projectId?: string; projectName?: string; environmentKind?: string; protected: boolean; online: boolean; lastHeartbeatAt?: string; agentVersion?: string; protocolVersion?: string; capabilities: string[]; os?: string; architecture?: string; packageType?: string; releaseChannel?: string; currentUpgradeState?: string; compatibility: { state: string; missingCapabilities: string[]; latestCompatibleVersion?: string; latestCompatibleReleaseId?: string; requiredMinimumVersion?: string; remoteUpgradeSupported: boolean; manualBootstrapRequired: boolean; requiresIntermediateVersion?: boolean } };
type InventoryResponse = { summary: Record<string, number>; inventory: Inventory[] };

export function AgentUpgradesPage({ toast }: { toast: (message: string) => void }) {
  const queryClient = useQueryClient(); const fleet = useQuery<InventoryResponse>({ queryKey: ["agent-upgrade-inventory"], queryFn: () => api.get("/agent-upgrades/inventory").then((response) => response.data) });
  const [project, setProject] = useState(""); const [version, setVersion] = useState(""); const [status, setStatus] = useState(""); const [os, setOs] = useState(""); const [architecture, setArchitecture] = useState(""); const [channel, setChannel] = useState(""); const [environment, setEnvironment] = useState(""); const [protectedFilter, setProtectedFilter] = useState(""); const [selected, setSelected] = useState<Inventory | null>(null); const [plan, setPlan] = useState<any>(null);
  const [selectedIds, setSelectedIds] = useState<string[]>([]); const [rollout, setRollout] = useState<any>(null);
  const values = fleet.data?.inventory || []; const options = (key: keyof Inventory) => [...new Set(values.map((item) => String(item[key] || "")).filter(Boolean))].sort();
  const history = useQuery<{ history: Array<{ _id: string; state: string; createdAt: string; failureCategory?: string }> }>({ queryKey: ["agent-upgrade-history", selected?.serverId], queryFn: () => api.get(`/agent-upgrades/history/${selected!.serverId}`).then((response) => response.data), enabled: Boolean(selected) });
  const filtered = useMemo(() => values.filter((item) => (!project || item.projectId === project) && (!version || item.agentVersion === version) && (!status || (item.currentUpgradeState || item.compatibility.state) === status) && (!os || item.os === os) && (!architecture || item.architecture === architecture) && (!channel || item.releaseChannel === channel) && (!environment || item.environmentKind === environment) && (!protectedFilter || String(item.protected) === protectedFilter)), [values, project, version, status, os, architecture, channel, environment, protectedFilter]);
  const request = useMutation({ mutationFn: (server: Inventory) => api.post("/agent-upgrades/plans", { serverId: server.serverId, releaseId: server.compatibility.latestCompatibleReleaseId, confirm: true }).then((response) => response.data), onSuccess: (data) => { setPlan(data); queryClient.invalidateQueries({ queryKey: ["agent-upgrade-inventory"] }); toast("Server-specific upgrade plan created; a different administrator must approve its exact digest"); } });
  const approve = useMutation({ mutationFn: () => api.post(`/agent-upgrades/plans/${plan.id}/approve`, { planDigest: plan.planDigest, confirm: true }).then((response) => response.data), onSuccess: () => { setPlan(null); queryClient.invalidateQueries({ queryKey: ["agent-upgrade-inventory"] }); toast("Exact upgrade plan approved and queued"); } });
  const requestRollout = useMutation({ mutationFn: async () => { const servers = values.filter((item) => selectedIds.includes(item.serverId)); const releaseIds = [...new Set(servers.map((item) => item.compatibility.latestCompatibleReleaseId).filter(Boolean))]; if (!servers.length || releaseIds.length !== 1) throw new Error("Selected servers must share one compatible approved release"); if (servers.some((item) => item.protected || !item.environmentKind || !item.compatibility.remoteUpgradeSupported)) throw new Error("Selection contains an ineligible server"); const plans = await Promise.all(servers.map((server) => api.post("/agent-upgrades/plans", { serverId: server.serverId, releaseId: releaseIds[0], confirm: true }).then((response) => response.data))); const expiresAt = new Date(Math.min(...plans.map((item) => new Date(item.expiresAt).getTime()))).toISOString(); return api.post("/agent-upgrades/rollouts", { releaseId: releaseIds[0], serverIds: servers.map((item) => item.serverId), perServerPlanDigests: Object.fromEntries(plans.map((item, index) => [servers[index].serverId, item.planDigest])), strategy: "canary", failureThreshold: 0, allowedEnvironments: [...new Set(servers.map((item) => item.environmentKind!))], expiresAt }).then((response) => response.data); }, onSuccess: (data) => { setRollout(data); setSelectedIds([]); toast("Canary rollout planned; a different administrator must approve its exact digest"); } });
  const approveRollout = useMutation({ mutationFn: () => api.post(`/agent-upgrades/rollouts/${rollout.id}/approve`, { rolloutDigest: rollout.rolloutDigest, confirm: true }).then((response) => response.data), onSuccess: () => { setRollout(null); queryClient.invalidateQueries({ queryKey: ["agent-upgrade-inventory"] }); toast("Canary rollout approved and first host queued"); } });
  const summary = fleet.data?.summary || {};
  return <div className="space-y-4">
    <Card><div className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="font-semibold">Fleet agent upgrades</h2><p className="text-sm text-muted">Signed, typed, non-production lifecycle plans. Production and protected servers remain unavailable.</p></div><Badge tone="warning">Approval required</Badge></div><div className="mt-4 grid grid-cols-2 gap-3 md:grid-cols-4 lg:grid-cols-8">{[["Total", summary.total], ["Online", summary.online], ["Offline", summary.offline], ["Up to date", summary.upToDate], ["Available", summary.upgradeAvailable], ["Required", summary.upgradeRequired], ["Bootstrap", summary.manualBootstrap], ["Failed / rollback", (summary.failed || 0) + (summary.rolledBack || 0)]].map(([label, value]) => <div key={String(label)}><div className="text-xs text-muted">{label}</div><div className="font-semibold">{value || 0}</div></div>)}</div></Card>
    <Card><div className="grid gap-2 sm:grid-cols-2 lg:grid-cols-4"><Select aria-label="Project filter" value={project} onChange={(event) => setProject(event.target.value)}><option value="">All projects</option>{[...new Map(values.filter((item) => item.projectId).map((item) => [item.projectId!, item.projectName || item.projectId!])).entries()].map(([id, name]) => <option key={id} value={id}>{name}</option>)}</Select><Select aria-label="Agent version filter" value={version} onChange={(event) => setVersion(event.target.value)}><option value="">All versions</option>{options("agentVersion").map((item) => <option key={item}>{item}</option>)}</Select><Select aria-label="Upgrade status filter" value={status} onChange={(event) => setStatus(event.target.value)}><option value="">All statuses</option>{[...new Set(values.map((item) => item.currentUpgradeState || item.compatibility.state))].sort().map((item) => <option key={item}>{item}</option>)}</Select><Select aria-label="Operating system filter" value={os} onChange={(event) => setOs(event.target.value)}><option value="">All operating systems</option>{options("os").map((item) => <option key={item}>{item}</option>)}</Select><Select aria-label="Architecture filter" value={architecture} onChange={(event) => setArchitecture(event.target.value)}><option value="">All architectures</option>{options("architecture").map((item) => <option key={item}>{item}</option>)}</Select><Select aria-label="Release channel filter" value={channel} onChange={(event) => setChannel(event.target.value)}><option value="">All channels</option>{options("releaseChannel").map((item) => <option key={item}>{item}</option>)}</Select><Select aria-label="Environment filter" value={environment} onChange={(event) => setEnvironment(event.target.value)}><option value="">All environments</option>{options("environmentKind").map((item) => <option key={item}>{item}</option>)}</Select><Select aria-label="Protected filter" value={protectedFilter} onChange={(event) => setProtectedFilter(event.target.value)}><option value="">Protected and unprotected</option><option value="false">Unprotected only</option><option value="true">Protected only</option></Select></div></Card>
    <Card><div className="mb-3 flex flex-wrap items-center justify-between gap-2"><p className="text-sm text-muted">{selectedIds.length} eligible server{selectedIds.length === 1 ? "" : "s"} selected</p><Button disabled={!selectedIds.length || requestRollout.isPending} onClick={() => requestRollout.mutate()}>Plan selected canary rollout</Button></div><Table columns={["Select", "Server", "Environment", "Current", "Required", "Latest", "OS / architecture", "Status", "Actions"]} rows={filtered.map((server) => { const eligible = Boolean(server.compatibility.remoteUpgradeSupported && server.compatibility.latestCompatibleReleaseId && !server.protected && server.environmentKind); return [<input type="checkbox" aria-label={`Select ${server.name} for rollout`} disabled={!eligible} checked={selectedIds.includes(server.serverId)} onChange={(event) => setSelectedIds((current) => event.target.checked ? [...current, server.serverId] : current.filter((id) => id !== server.serverId))} />, <button className="text-left text-primary underline" onClick={() => { setSelected(server); setPlan(null); }}>{server.name}<span className="block text-xs text-muted">{server.slug || "No slug"}</span></button>, `${server.environmentKind || "Unclassified"}${server.protected ? " / protected" : ""}`, server.agentVersion || "Unknown", server.compatibility.requiredMinimumVersion || "Not established", server.compatibility.latestCompatibleVersion || "No approved release", `${server.os || "Unknown"} / ${server.architecture || "Unknown"}`, <Badge tone={server.compatibility.state === "up_to_date" ? "success" : server.compatibility.state === "failed" ? "danger" : "warning"}>{(server.currentUpgradeState || server.compatibility.state).replace(/_/g, " ")}</Badge>, <div className="flex flex-wrap gap-1"><GhostButton onClick={() => setSelected(server)}>View upgrade plan</GhostButton><Button disabled={!eligible || request.isPending} onClick={() => request.mutate(server)}>Request agent upgrade</Button></div>]; })} empty={fleet.isLoading ? "Loading fleet compatibility…" : "No servers match these filters"} />{requestRollout.error && <p role="alert" className="mt-2 text-sm text-danger">{apiError(requestRollout.error)}</p>}</Card>
    {selected && <Card><div className="flex justify-between gap-2"><div><h3 className="font-semibold">{selected.name}: agent lifecycle</h3><p className="text-sm text-muted">Last heartbeat: {selected.lastHeartbeatAt ? new Date(selected.lastHeartbeatAt).toLocaleString() : "Never"}</p></div><GhostButton onClick={() => setSelected(null)}>Close</GhostButton></div><dl className="mt-4 grid gap-3 text-sm sm:grid-cols-2 lg:grid-cols-4"><div><dt className="text-muted">Protocol</dt><dd>{selected.protocolVersion || "Legacy / unreported"}</dd></div><div><dt className="text-muted">Package</dt><dd>{selected.packageType || "Legacy / unreported"}</dd></div><div><dt className="text-muted">Compatibility</dt><dd>{selected.compatibility.remoteUpgradeSupported ? "Remote upgrade supported" : "Manual bootstrap required"}</dd></div><div><dt className="text-muted">Missing capabilities</dt><dd>{selected.compatibility.missingCapabilities.join(", ") || "None"}</dd></div></dl><div className="mt-4 flex flex-wrap gap-2"><GhostButton onClick={() => queryClient.invalidateQueries({ queryKey: ["agent-upgrade-inventory"] })}>Retry discovery</GhostButton><GhostButton onClick={() => toast("Setup help uses a published, signed release; no credentials or shell commands are sent by the browser")}>View setup help</GhostButton>{selected.compatibility.manualBootstrapRequired && <GhostButton onClick={() => toast(selected.compatibility.latestCompatibleReleaseId ? "Open the approved release bootstrap procedure after owner review" : "No signed bootstrap release is published; a command cannot be generated safely")}>View manual bootstrap instructions</GhostButton>}</div></Card>}
    {plan && <Card><h3 className="font-semibold">Immutable upgrade plan</h3><p className="text-sm text-muted">Digest: <code>{plan.planDigest}</code>; expires {new Date(plan.expiresAt).toLocaleString()}.</p><pre className="mt-3 overflow-auto rounded-md bg-background p-3 text-xs">{JSON.stringify(plan.plan, null, 2)}</pre><p className="mt-2 text-sm text-muted">This browser did not send a command. A different recently authenticated administrator must approve this exact digest.</p><Button className="mt-3" disabled={approve.isPending} onClick={() => approve.mutate()}>Approve exact plan</Button>{approve.error && <p role="alert" className="mt-2 text-sm text-danger">{apiError(approve.error)}</p>}</Card>}
    {selected && <Card><h3 className="font-semibold">Upgrade history</h3>{history.isLoading ? <p className="text-sm text-muted">Loading history...</p> : history.data?.history.length ? <ul className="mt-2 space-y-1 text-sm">{history.data.history.map((item) => <li key={item._id}>{new Date(item.createdAt).toLocaleString()}: {item.state.replace(/_/g, " ")}{item.failureCategory ? ` (${item.failureCategory})` : ""}</li>)}</ul> : <p className="text-sm text-muted">No prior upgrade plans.</p>}</Card>}
    {rollout && <Card><h3 className="font-semibold">Immutable canary rollout</h3><p className="text-sm text-muted">Digest: <code>{rollout.rolloutDigest}</code>. The exact server set, per-server plans, release, environments, zero-failure threshold, and expiry are bound.</p><Button className="mt-3" disabled={approveRollout.isPending} onClick={() => approveRollout.mutate()}>Approve exact rollout</Button>{approveRollout.error && <p role="alert" className="mt-2 text-sm text-danger">{apiError(approveRollout.error)}</p>}</Card>}
    {request.error && <p role="alert" className="text-sm text-danger">{apiError(request.error)}</p>}
  </div>;
}
