import { useState } from "react";
import { useMutation, useQuery } from "@tanstack/react-query";
import { api } from "./api";
import { Badge, Button, Card, Field } from "./ui";

type Scope = { type: "server" | "application"; id: string };
const suggestions = ["Explain the current health evidence.", "What changed before the latest failure?", "Which low-risk diagnostic should I run next?", "Is this similar to a previous incident?"];
const tone = (value: string) => value === "high" || value === "fresh" || value === "healthy" ? "success" : value === "critical" || value === "stale" ? "danger" : "warning";
const title = (value: string) => value.replace(/_/g, " ").replace(/\b\w/g, (letter: string) => letter.toUpperCase());

export function AiAssistantPanel({ scope }: { scope: Scope }) {
  const [question, setQuestion] = useState("");
  const status = useQuery({ queryKey: ["ai-assistant-status"], queryFn: () => api.get("/ai-assistant/status").then((r) => r.data), retry: false });
  const analysis = useMutation({ mutationFn: () => api.post("/ai-assistant/analyze", { scope, question, contextOptions: { includeHealth: true, includeDiscovery: true, includeRecentLogs: true, includeDeployments: true, includeCiSummary: true } }).then((r) => r.data) });
  const result = analysis.data?.result; const metadata = analysis.data?.metadata; const operational = analysis.data?.operational; const errorCode = (analysis.error as any)?.response?.data?.code;
  const disabled = status.data && (!status.data.enabled || !status.data.configured);
  const healthEvidence = result?.evidence?.filter((item: any) => item.sourceType === "health_check" || item.sourceType === "server") || [];
  const deploymentEvidence = result?.evidence?.filter((item: any) => item.sourceType === "deployment" || item.sourceType === "rollback") || [];
  return <Card><div className="min-w-0 space-y-4" aria-live="polite">
    <div className="flex flex-wrap items-start justify-between gap-2"><div><h3 className="font-semibold">AI Assistant — Operations Intelligence</h3><p className="text-sm text-muted">Evidence-backed, read-only analysis from authorized OpsWorkbench data.</p></div><Badge tone="success">Read only</Badge></div>
    {status.isLoading && <p className="text-sm text-muted">Checking assistant availability…</p>}
    {disabled && <div className="rounded-md border border-warning/40 p-3 text-sm"><strong>{status.data.enabled ? "Assistant is not configured" : "Assistant is disabled"}</strong><p className="text-muted">Operational data remains available. No provider is enabled by this panel.</p></div>}
    {!disabled && <><label className="block text-sm" htmlFor={`ai-question-${scope.type}-${scope.id}`}>Ask about this {scope.type}<Field id={`ai-question-${scope.type}-${scope.id}`} className="mt-1" value={question} maxLength={1000} onChange={(e) => setQuestion(e.target.value)} placeholder="What changed before the latest failure?" /></label>
      <div className="flex flex-wrap gap-2" aria-label="Suggested follow-up questions">{suggestions.map((item) => <button key={item} type="button" className="max-w-full rounded-full border border-border px-3 py-1 text-left text-xs" onClick={() => setQuestion(item)}>{item}</button>)}</div>
      <Button disabled={question.trim().length < 3 || analysis.isPending} onClick={() => analysis.mutate()}>{analysis.isPending ? "Analyzing…" : "Analyze evidence"}</Button></>}
    {analysis.isError && <div className="rounded-md border border-danger/40 p-3 text-sm" role="alert"><strong>{errorCode === "provider_timeout" ? "Assistant timed out" : errorCode === "resource_not_found" ? "You cannot access this resource" : "Assistant could not complete the analysis"}</strong><p className="text-muted">No infrastructure changes were attempted.</p></div>}
    {metadata && Object.values(metadata.redactions || {}).some(Boolean) && <p className="rounded-md border border-warning/40 p-2 text-sm">Sensitive values were redacted before analysis.</p>}
    {result && <div className="min-w-0 space-y-5">
      <section><div className="flex flex-wrap gap-2"><Badge tone={tone(result.status)}>{result.status}</Badge><Badge tone={tone(result.confidence)}>{result.confidence} confidence</Badge><Badge>{result.risk} risk</Badge>{result.evidence[0] && <Badge tone={tone(result.evidence[0].freshness)}>{result.evidence[0].freshness}</Badge>}</div><h4 className="mt-3 font-medium">Summary</h4><p className="mt-1 break-words">{result.summary}</p></section>
      <div className="grid min-w-0 gap-3 sm:grid-cols-2"><EvidenceCard title="Health summary" items={healthEvidence} empty="No fresh health evidence." /><EvidenceCard title="Recent deployments" items={deploymentEvidence} empty="No recent deployment evidence." /></div>
      <section><h4 className="font-medium">Root-cause ranking</h4>{result.likelyCauses.length ? <ol className="mt-2 space-y-2">{result.likelyCauses.map((cause: any) => <li className="rounded-md border border-border p-3" key={cause.title}><div className="flex flex-wrap justify-between gap-2"><strong>{cause.title}</strong><Badge>{Math.round(cause.score * 100)}%</Badge></div><ul className="mt-1 list-disc pl-5 text-sm text-muted">{cause.evidence.map((item: string) => <li className="break-words" key={item}>{item}</li>)}</ul></li>)}</ol> : <p className="mt-1 text-sm text-muted">No evidence-backed root cause could be ranked.</p>}</section>
      <section><h4 className="font-medium">Recommended diagnostics</h4>{result.recommendedSteps.length ? <ol className="mt-2 space-y-2">{result.recommendedSteps.map((step: any) => <li className="rounded-md border border-border p-3" key={step.order}><div className="flex flex-wrap items-center gap-2"><strong>{step.order}. {step.title}</strong><Badge>{title(step.classification)}</Badge></div><p className="mt-1 break-words text-sm text-muted">{step.description}</p><p className="mt-1 text-xs text-muted">Evidence: {step.evidence.join("; ")}</p></li>)}</ol> : <p className="mt-1 text-sm text-muted">No recommendation was produced because no supporting evidence is available.</p>}</section>
      <section><h4 className="font-medium">Change timeline</h4>{result.timeline.length ? <ol className="mt-2 border-l border-border pl-4">{result.timeline.map((item: any) => <li className="mb-3 min-w-0 text-sm" key={`${item.timestamp}-${item.event}`}><time className="text-xs text-muted">{new Date(item.timestamp).toLocaleString()}</time><p className="break-words">{item.event}</p></li>)}</ol> : <p className="text-sm text-muted">No timeline events available.</p>}</section>
      <section><h4 className="font-medium">Related incidents</h4>{result.relatedIncidents.length ? <ul className="mt-2 space-y-2 text-sm">{result.relatedIncidents.map((item: any) => <li className="rounded-md border border-border p-2" key={item.id}>This resembles {item.summary}. <Badge>{Math.round(item.similarity * 100)}% similar</Badge></li>)}</ul> : <p className="text-sm text-muted">No similar incident found.</p>}</section>
      <details><summary className="cursor-pointer font-medium">Evidence used ({result.evidence.length})</summary><ul className="mt-2 grid gap-2 sm:grid-cols-2">{result.evidence.map((item: any) => <li className="min-w-0 rounded-md border border-border p-2 text-sm" key={`${item.sourceType}-${item.label}-${item.timestamp}`}><div className="flex flex-wrap gap-1"><Badge>{title(item.sourceType)}</Badge><Badge tone={tone(item.freshness)}>{item.freshness}</Badge></div><strong className="mt-1 block break-words">{item.label}</strong><p className="break-words">{item.value}</p><p className="mt-1 text-xs text-muted">{item.source} · {new Date(item.timestamp).toLocaleString()} · {item.confidence} confidence</p></li>)}</ul></details>
      <details><summary className="cursor-pointer font-medium">Alternative possibilities and limitations</summary><div className="mt-2 grid gap-3 sm:grid-cols-2"><List title="Alternative possibilities" items={result.alternativePossibilities} /><List title="Limitations" items={[...result.limitations, ...(operational?.rejectedSections || []).map((item: any) => `${title(item.key)} was rejected: ${item.reason}.`)]} /></div></details>
      <p className="text-xs text-muted">Generated {new Date(result.generatedAt).toLocaleString()} · Context cache {metadata?.contextCache || "unknown"}</p>
    </div>}
    <div className="rounded-md border border-success/40 bg-background p-3 text-sm font-semibold">No actions were executed</div>
  </div></Card>;
}

function EvidenceCard({ title: heading, items, empty }: { title: string; items: any[]; empty: string }) { return <section className="min-w-0 rounded-md border border-border p-3"><h4 className="font-medium">{heading}</h4>{items.length ? <ul className="mt-2 space-y-1 text-sm">{items.slice(0, 6).map((item) => <li className="break-words" key={`${item.label}-${item.timestamp}`}><strong>{item.label}:</strong> {item.value}</li>)}</ul> : <p className="mt-1 text-sm text-muted">{empty}</p>}</section>; }
function List({ title: heading, items }: { title: string; items: string[] }) { return <section><h5 className="text-sm font-medium">{heading}</h5><ul className="mt-1 list-disc space-y-1 pl-5 text-sm text-muted">{items.map((item) => <li className="break-words" key={item}>{item}</li>)}</ul></section>; }
