import { useEffect, useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { api } from "./api";
import { Badge, Button, Card, Field } from "./ui";

export function AiSettingsCard({ toast }: { toast: (message: string) => void }) {
  const qc = useQueryClient(); const query = useQuery({ queryKey: ["ai-settings"], queryFn: () => api.get("/org/ai-assistant").then((r) => r.data), retry: false });
  const [form, setForm] = useState<any>(null); useEffect(() => { if (query.data) setForm({ ...query.data.settings, provider: query.data.settings.provider || "", model: query.data.settings.model || "", monthlyRequestLimit: query.data.settings.monthlyRequestLimit || "", monthlyTokenLimit: query.data.settings.monthlyTokenLimit || "", retentionAcknowledged: Boolean(query.data.settings.providerDataRetentionAcknowledgedAt) }); }, [query.data]);
  const probe = useMutation({ mutationFn: () => api.post("/org/ai-workforce/provider-probe").then((r) => r.data), onSuccess: (result) => toast(`${result.provider} provider is ready (${result.durationMs} ms)`) });
  const save = useMutation({ mutationFn: () => api.put("/org/ai-assistant", { ...form, provider: form.provider || null, model: form.model || null, monthlyRequestLimit: form.monthlyRequestLimit ? Number(form.monthlyRequestLimit) : null, monthlyTokenLimit: form.monthlyTokenLimit ? Number(form.monthlyTokenLimit) : null }), onSuccess: () => { qc.invalidateQueries({ queryKey: ["ai-settings"] }); qc.invalidateQueries({ queryKey: ["ai-assistant-status"] }); toast("AI Assistant settings updated"); } });
  if ((query.error as any)?.response?.status === 403) return <Card><h3 className="font-semibold">AI Assistant administration</h3><p className="mt-2 text-sm text-muted">You do not have permission to administer AI settings.</p></Card>;
  if (query.isLoading || !form) return <Card><p className="text-sm text-muted">Loading AI Assistant settings…</p></Card>;
  const set = (key: string, value: unknown) => setForm((current: any) => ({ ...current, [key]: value }));
  return <Card><div className="min-w-0 space-y-4"><div className="flex flex-wrap items-center justify-between gap-2"><div><h3 className="font-semibold">AI Assistant administration</h3><p className="text-sm text-muted">Organization controls for the read-only assistant.</p></div><Badge tone="success">No actions can be executed</Badge></div>
    {!query.data.globalEnabled && <p className="rounded-md border border-warning/40 p-3 text-sm">The global feature is disabled. Saving settings will not activate provider requests.</p>}
    <label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={form.enabled} onChange={(e) => set("enabled", e.target.checked)} />Enable for this organization</label>
    <div className="grid min-w-0 gap-3 md:grid-cols-2"><label className="text-sm">Provider<select className="mt-1 w-full rounded-md border border-border bg-background p-2" value={form.provider} onChange={(e) => set("provider", e.target.value)}><option value="">Select provider</option>{query.data.allowlists.providers.map((value: string) => <option key={value}>{value}</option>)}</select></label><label className="text-sm">Model<select className="mt-1 w-full rounded-md border border-border bg-background p-2" value={form.model} onChange={(e) => set("model", e.target.value)}><option value="">Select model</option>{query.data.allowlists.models.map((value: string) => <option key={value}>{value}</option>)}</select></label>
      {[['maximumRequestsPerUserPerHour','Requests per user/hour'],['maximumRequestsPerOrganizationPerDay','Requests per organization/day'],['maximumConcurrentRequests','Concurrent requests'],['monthlyRequestLimit','Monthly request limit'],['monthlyTokenLimit','Monthly token limit']].map(([key,label]) => <label className="text-sm" key={key}>{label}<Field className="mt-1" type="number" min={1} value={form[key]} onChange={(e) => set(key, e.target.value === "" ? "" : Number(e.target.value))} /></label>)}</div>
    <fieldset><legend className="text-sm font-medium">Allowed analysis scopes</legend><div className="mt-2 flex flex-wrap gap-4">{["server","application"].map((scope) => <label className="flex items-center gap-2 text-sm" key={scope}><input type="checkbox" checked={form.allowedScopeTypes.includes(scope)} onChange={(e) => set("allowedScopeTypes", e.target.checked ? [...form.allowedScopeTypes, scope] : form.allowedScopeTypes.filter((x: string) => x !== scope))} />{scope}</label>)}</div></fieldset>
    <div className="rounded-md border border-warning/40 p-3 text-sm"><strong>Privacy and cost disclosure</strong><p className="mt-1 text-muted">Sanitized, bounded status, telemetry, discovery, health, and operation metadata may be sent to the selected external provider. Secrets, credentials, raw logs, prompts, and responses are excluded from OpsWorkbench audit storage. Provider retention depends on your provider account and contract. Enabling may incur charges.</p><label className="mt-3 flex items-start gap-2"><input className="mt-1" type="checkbox" checked={form.retentionAcknowledged} onChange={(e) => set("retentionAcknowledged", e.target.checked)} />I acknowledge the provider retention and cost disclosure.</label></div>
    <div><div className="flex flex-wrap items-center justify-between gap-2"><h4 className="text-sm font-medium">AI Workforce providers</h4><Button disabled={!form.provider || probe.isPending} onClick={() => probe.mutate()}>{probe.isPending ? "Testing provider..." : "Test selected provider"}</Button></div><p className="mt-1 text-xs text-muted">Manual health tests validate provider authentication without generating content.</p><div className="mt-2 grid gap-2 sm:grid-cols-2">{query.data.workforce?.providers.map((provider: any) => <div key={provider.id} className="flex items-center justify-between rounded border border-border p-2 text-sm"><span>{provider.name}</span><Badge tone={provider.configured ? "success" : "warning"}>{provider.health === "ready" ? "Ready" : provider.health === "models_not_mapped" ? "Models not mapped" : "Credential missing"}</Badge></div>)}</div>{probe.isError && <p role="alert" className="mt-2 text-sm text-danger">Provider health test failed or is cooling down.</p>}<p className="mt-2 text-xs text-muted">{query.data.workforce?.roles.length || 0} read-only workforce roles registered. Credentials remain server-side.</p><div className="mt-2 space-y-1">{query.data.workforce?.assignments.map((assignment: any) => <p className="text-xs text-muted" key={assignment.roleId}>{assignment.roleId}: {assignment.route ? `${assignment.route.provider} / ${assignment.route.model}` : "Unassigned"}</p>)}</div></div>
    <dl className="grid gap-2 text-sm sm:grid-cols-2"><div><dt className="text-muted">Credential configured</dt><dd>{query.data.providerStatus.credentialPresent ? "Yes" : "No"}</dd></div><div><dt className="text-muted">Requests today</dt><dd>{query.data.usage.organizationRequestsToday} / {form.maximumRequestsPerOrganizationPerDay}</dd></div><div><dt className="text-muted">Requests this month</dt><dd>{query.data.usage.organizationRequestsThisMonth}</dd></div><div><dt className="text-muted">Tokens this month</dt><dd>{query.data.usage.tokensThisMonth}</dd></div><div><dt className="text-muted">Last success</dt><dd>{query.data.usage.lastSuccessfulRequestAt ? new Date(query.data.usage.lastSuccessfulRequestAt).toLocaleString() : "Never"}</dd></div><div><dt className="text-muted">Last failure</dt><dd>{query.data.usage.lastFailureCategory || "None"}</dd></div></dl>
    <Button disabled={save.isPending || (form.enabled && !form.retentionAcknowledged)} onClick={() => save.mutate()}>{save.isPending ? "Saving…" : "Save AI settings"}</Button>{save.isError && <p role="alert" className="text-sm text-danger">Settings could not be saved.</p>}</div></Card>;
}
