import { useEffect, useMemo, useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { api, apiError } from "./api";
import { Badge, Button, Card, Field, GhostButton, Select, Skeleton, Table } from "./ui";
import { configurationCategory, parseEnvironmentText, plainLanguageChangeSummary, type ImportedEnvironmentVariable } from "./configurationUx";
import { ConfigurationDeploymentWorkflow } from "./ConfigurationDeploymentWorkflow";

type Project = { _id: string; name: string; slug?: string };
type Environment = { _id: string; projectId: string; name: string; kind: string; protected: boolean };
type Definition = { _id: string; name: string; applicationPath?: string; description?: string; type: string; secret: boolean; required: boolean; provider?: string; usage: string; status: string; sources: string[]; sourcePaths?: string[]; services: string[]; activeVersion?: number; risk?: "low" | "medium" | "high" | "critical"; removalPermitted?: boolean; browserDisplayPermitted?: boolean; restartRequirement?: string };
type Version = { definitionId: string; environmentId: string; version: number; masked: string; state: string; validationState: string; createdAt?: string };

const futureActions = ["Promote Settings", "Validate Website"];
const onboardingSteps = ["Select application", "Detect configuration", "Locate live configuration", "Match variables", "Add missing values", "Validate setup"];

function statusTone(status: string): "neutral" | "success" | "danger" | "warning" { return status === "configured" || status === "active" ? "success" : status === "missing" || status === "invalid" ? "danger" : status === "pending" || status === "drifted" ? "warning" : "neutral"; }

export function ConfigurationPage({ toast, navigate }: { toast: (message: string) => void; navigate?: (path: string) => void }) {
  const queryClient = useQueryClient();
  const projects = useQuery<Project[]>({ queryKey: ["projects"], queryFn: () => api.get("/projects").then((response) => response.data.projects) });
  const [projectId, setProjectId] = useState("");
  useEffect(() => { if (!projectId && projects.data?.[0]) setProjectId(projects.data[0]._id); }, [projectId, projects.data]);
  const selectedProject = projects.data?.find((project) => project._id === projectId);
  const environments = useQuery<Environment[]>({ queryKey: ["configuration-environments"], queryFn: () => api.get("/configuration/environments").then((response) => response.data.environments) });
  const matrix = useQuery<{ definitions: Definition[]; versions: Version[] }>({ queryKey: ["configuration-definitions", projectId], queryFn: () => api.get("/configuration/definitions", { params: { projectId } }).then((response) => response.data), enabled: Boolean(projectId) });
  const projectEnvironments = useMemo(() => (environments.data || []).filter((environment) => environment.projectId === projectId), [environments.data, projectId]);
  const [environmentId, setEnvironmentId] = useState("");
  useEffect(() => { if (!projectEnvironments.some((environment) => environment._id === environmentId)) setEnvironmentId(projectEnvironments[0]?._id || ""); }, [environmentId, projectEnvironments]);
  const selectedEnvironment = projectEnvironments.find((environment) => environment._id === environmentId);

  const [mode, setMode] = useState<"none" | "add" | "import" | "onboarding">("none");
  const [selected, setSelected] = useState<Definition | null>(null);
  const [environmentName, setEnvironmentName] = useState("");
  const createEnvironment = useMutation({ mutationFn: () => api.post("/configuration/environments", { projectId, name: environmentName, kind: "staging", protected: false }), onSuccess: () => { setEnvironmentName(""); queryClient.invalidateQueries({ queryKey: ["configuration-environments"] }); toast("Environment created"); } });
  const [definitionName, setDefinitionName] = useState("");
  const [description, setDescription] = useState("");
  const [definitionSecret, setDefinitionSecret] = useState(false);
  const createDefinition = useMutation({ mutationFn: () => api.post("/configuration/definitions", { projectId, name: definitionName, description: description.trim() || `Configuration definition for ${definitionName}`, type: definitionSecret ? "secret" : "text", secret: definitionSecret, required: false, usage: "runtime", services: [], applicableEnvironments: ["development", "staging"], validation: { type: "text" }, restartRequirement: "restart", removalPermitted: true, browserDisplayPermitted: !definitionSecret, risk: definitionSecret ? "high" : "low" }), onSuccess: () => { setDefinitionName(""); setDescription(""); setMode("none"); queryClient.invalidateQueries({ queryKey: ["configuration-definitions", projectId] }); toast("Variable added as Missing until a value is stored"); } });
  const [editing, setEditing] = useState<Definition | null>(null);
  const [value, setValue] = useState("");
  const [reason, setReason] = useState("");
  const [operation, setOperation] = useState<"update" | "disable" | "remove">("update");
  const createVersion = useMutation({ mutationFn: () => api.post(`/configuration/definitions/${editing?._id}/versions`, { environmentId, operation, ...(["disable", "remove"].includes(operation) ? {} : { value }), changeReason: reason }), onSuccess: () => { setValue(""); setReason(""); setOperation("update"); setEditing(null); queryClient.invalidateQueries({ queryKey: ["configuration-definitions", projectId] }); toast("New version saved as Pending Deployment"); } });

  const [importText, setImportText] = useState("");
  const [imported, setImported] = useState<ImportedEnvironmentVariable[]>([]);
  const [importErrors, setImportErrors] = useState<string[]>([]);
  const clearImport = () => { setImportText(""); setImported([]); setImportErrors([]); };
  const previewImport = (text: string) => { const parsed = parseEnvironmentText(text); setImported(parsed.variables); setImportErrors(parsed.errors); };
  useEffect(() => { if (mode !== "import") { setImportText(""); setImported([]); setImportErrors([]); } }, [mode]);
  const [onboardingStep, setOnboardingStep] = useState(0);
  const definitions = matrix.data?.definitions || [];
  const versions = matrix.data?.versions || [];
  const counts = definitions.reduce<Record<string, number>>((result, definition) => ({ ...result, [definition.status]: (result[definition.status] || 0) + 1 }), {});
  const missingRequired = definitions.filter((definition) => definition.required && definition.status === "missing").length;
  const environmentNeedsAttention = missingRequired > 0 || Boolean(counts.invalid) || Boolean(counts.drifted);
  const pending = definitions.filter((definition) => definition.status === "pending");
  const latestVersion = (definition: Definition) => versions.find((version) => version.definitionId === definition._id && (!environmentId || version.environmentId === environmentId));
  const plan = plainLanguageChangeSummary(pending, selectedEnvironment?.name || "the selected environment");
  const error = createEnvironment.error || createDefinition.error || createVersion.error || matrix.error;
  const go = (path: string) => { if (navigate) navigate(path); else { window.history.pushState({}, "", path); window.dispatchEvent(new PopStateEvent("popstate")); } };

  const rows = definitions.map((definition) => { const version = latestVersion(definition); return [<button className="font-mono text-primary underline" onClick={() => setSelected(definition)}>{definition.name}</button>, configurationCategory(definition.name), <Badge tone={statusTone(definition.status)}>{definition.status.replace(/_/g, " ")}</Badge>, definition.services.join(", ") || "Application", definition.secret ? "Secret" : definition.type, version?.createdAt ? new Date(version.createdAt).toLocaleDateString() : "Not set", version?.state || "Not deployed", <button className="text-primary underline" onClick={() => { setEditing(definition); setValue(""); }}> {definition.secret && definition.activeVersion ? "Rotate" : definition.activeVersion ? "Update" : "Add"}</button>]; });

  return <div className="space-y-4">
    <Card><div className="flex flex-wrap items-start justify-between gap-3"><div><div className="text-xs text-muted">Project workspace</div><h2 className="font-semibold">Environment</h2><p className="mt-1 text-sm text-muted">Manage website settings without editing server files directly. Controlled deployment is limited to reviewed non-production targets.</p></div><Badge tone="warning">Production deployment unavailable</Badge></div><div className="mt-4 grid gap-3 sm:grid-cols-2"><label className="text-sm">Application<Select aria-label="Configuration project" value={projectId} onChange={(event) => setProjectId(event.target.value)}><option value="">Select application</option>{projects.data?.map((project) => <option key={project._id} value={project._id}>{project.name}</option>)}</Select></label><label className="text-sm">Environment<Select aria-label="Configuration environment" value={environmentId} onChange={(event) => setEnvironmentId(event.target.value)}><option value="">Select environment</option>{projectEnvironments.map((environment) => <option key={environment._id} value={environment._id}>{environment.name} ({environment.kind})</option>)}</Select></label></div>
      {selectedProject ? <div className="mt-4 rounded-md border border-border bg-background/50 p-3 text-sm"><div className="flex flex-wrap items-center justify-between gap-3"><div><div className="text-xs text-muted">Selected project</div><strong>{selectedProject.name}</strong>{selectedProject.slug && <span className="ml-2 text-muted">{selectedProject.slug}</span>}</div><nav aria-label="Project environment workspace" className="flex flex-wrap gap-2"><GhostButton onClick={() => go(`/projects/${selectedProject._id}/overview`)}>Overview</GhostButton><GhostButton onClick={() => go(`/projects/${selectedProject._id}/deployments`)}>Deployments</GhostButton><GhostButton onClick={() => go(`/projects/${selectedProject._id}/rollbacks`)}>Rollbacks</GhostButton><GhostButton aria-current="page">Environment</GhostButton></nav></div></div> : <div className="mt-4 rounded-md border border-dashed border-border p-4 text-sm text-muted">No project is selected. Create or select a project before managing environment variables.</div>}
      <div className="mt-4 flex flex-wrap gap-2"><Button onClick={() => setMode("add")}>Add Variable</Button><GhostButton onClick={() => setMode("import")}>Import .env</GhostButton><GhostButton onClick={() => { setMode("onboarding"); setOnboardingStep(0); }}>Guided Onboarding</GhostButton>{futureActions.map((action) => <GhostButton key={action} disabled title="Available in a later reviewed milestone">{action}</GhostButton>)}</div></Card>

    <div className="grid grid-cols-2 gap-3 lg:grid-cols-7">{[["Environment Health", !projectId ? "Select project" : !environmentId ? "Create environment" : environmentNeedsAttention ? "Needs attention" : "Ready"], ["Missing Required", missingRequired], ["Pending Changes", counts.pending || 0], ["Drift Detected", counts.drifted || 0], ["Last Deployment", "Not enabled"], ["Last Validation", "Not run"], ["Rollback Available", "Not yet"]].map(([label, value]) => <Card key={String(label)}><div className="text-xs text-muted">{label}</div><div className="mt-1 font-semibold">{value}</div></Card>)}</div>

    <Card><div className="flex flex-wrap items-center justify-between gap-2"><div><h3 className="font-semibold">Variables</h3><p className="text-sm text-muted">Required, missing, configured, pending, invalid, drifted, and unused settings appear here for the selected project and environment only. Secret values never appear.</p></div><div className="flex gap-2"><GhostButton disabled>Fix Missing Variables</GhostButton><GhostButton disabled>Review Drift</GhostButton></div></div><div className="mt-3 max-w-full overflow-x-auto">{matrix.isLoading ? <Skeleton /> : <Table columns={["Name", "Category", "Status", "Used By", "Type", "Last Updated", "Deployment State", "Action"]} rows={rows} empty={!projectId ? "Select an application" : !environmentId ? "Create an environment before adding values" : "No variables discovered or defined for this project"} />}</div></Card>

    {pending.length > 0 && <Card><h3 className="font-semibold">Plain-language deployment plan</h3><p className="mt-1">{plan.heading}</p><ol className="mt-3 list-decimal space-y-1 pl-5 text-sm text-muted">{plan.steps.map((step) => <li key={step}>{step}</li>)}</ol></Card>}
    <ConfigurationDeploymentWorkflow environmentKind={selectedEnvironment?.kind} protectedEnvironment={selectedEnvironment?.protected} />

    {mode === "add" && <Card><div className="flex justify-between"><div><h3 className="font-semibold">Add Variable</h3><p className="text-sm text-muted">Add the definition first; its value is stored separately as an immutable pending version.</p></div><GhostButton onClick={() => setMode("none")}>Close</GhostButton></div><div className="mt-3 grid gap-2"><Field aria-label="Variable name" placeholder="VARIABLE_NAME" value={definitionName} onChange={(event) => setDefinitionName(event.target.value.toUpperCase())} /><Field aria-label="Variable description" placeholder="Plain-language purpose (optional)" value={description} onChange={(event) => setDescription(event.target.value)} /><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={definitionSecret} onChange={(event) => setDefinitionSecret(event.target.checked)} />This is a secret</label><Button disabled={!projectId || !definitionName || createDefinition.isPending} onClick={() => createDefinition.mutate()}>Add Variable</Button></div></Card>}

    {mode === "import" && <Card><div className="flex justify-between"><div><h3 className="font-semibold">Import .env safely</h3><p className="text-sm text-muted">Parsing and preview happen in this browser only. Nothing is uploaded, logged, or deployed in this foundation milestone.</p></div><GhostButton onClick={() => { clearImport(); setMode("none"); }}>Close and clear</GhostButton></div><div className="mt-3 grid gap-3"><textarea aria-label="Environment text" className="min-h-36 w-full rounded-md border border-border bg-background p-3 font-mono text-sm" value={importText} onChange={(event) => setImportText(event.target.value)} placeholder="Paste VARIABLE=value lines" /><label className="text-sm">Or select a local file<input aria-label="Environment file" className="mt-1 block w-full text-sm" type="file" accept=".env,.example,.sample,.template,text/plain" onChange={async (event) => { const file = event.target.files?.[0]; if (!file || file.size > 256 * 1024) { clearImport(); setImportErrors(["File must be 256 KiB or smaller."]); event.target.value = ""; return; } const text = await file.text(); setImportText(text); previewImport(text); event.target.value = ""; }} /></label><div className="flex gap-2"><Button disabled={!importText} onClick={() => previewImport(importText)}>Preview names</Button><GhostButton onClick={clearImport}>Clear temporary values</GhostButton></div>{importErrors.map((entry) => <p key={entry} className="text-sm text-danger">{entry}</p>)}{imported.length > 0 && <Table columns={["Name", "Category", "Classification", "Review"]} rows={imported.map((variable) => [<code>{variable.name}</code>, configurationCategory(variable.name), variable.secret ? "Likely secret" : "Public", variable.duplicate ? <Badge tone="danger">Duplicate</Badge> : <Badge>Ready to select</Badge>])} />}</div></Card>}

    {mode === "onboarding" && <Card><div className="flex justify-between"><div><h3 className="font-semibold">Guided application onboarding</h3><p className="text-sm text-muted">Step {onboardingStep + 1} of {onboardingSteps.length}: {onboardingSteps[onboardingStep]}</p></div><GhostButton onClick={() => setMode("none")}>Save for later</GhostButton></div><div className="mt-4 grid gap-2 sm:grid-cols-3">{onboardingSteps.map((step, index) => <div key={step} className={`rounded-md border p-3 text-sm ${index === onboardingStep ? "border-primary bg-primary/10" : "border-border"}`}><div className="text-xs text-muted">Step {index + 1}</div>{step}</div>)}</div><div className="mt-4 rounded-md border border-border bg-background p-4 text-sm text-muted">{onboardingStep === 0 && "Choose a discovered application, confirm its name, project, and environment."}{onboardingStep === 1 && "Review value-free names detected from templates, source, Compose, Dockerfiles, workflows, and runtime configuration."}{onboardingStep === 2 && "Confirm suggested server, project directory, environment file, services, and activation method. No changes are made."}{onboardingStep === 3 && "Review Ready, Missing, Needs Review, Invalid, Duplicate, Unused, and Drifted classifications."}{onboardingStep === 4 && "Enter missing values securely. Secrets become encrypted pending versions and are never shown again."}{onboardingStep === 5 && "Review planned health, database, storage, TLS, and service checks. Live validation is not enabled yet."}</div><div className="mt-4 flex justify-between"><GhostButton disabled={onboardingStep === 0} onClick={() => setOnboardingStep((step) => step - 1)}>Back</GhostButton><Button disabled={onboardingStep === onboardingSteps.length - 1} onClick={() => setOnboardingStep((step) => step + 1)}>Next</Button></div></Card>}

    {selected && <Card><div className="flex justify-between"><div><h3 className="font-semibold">{selected.name}</h3><p className="text-sm text-muted">{selected.description || `Configuration used by ${selected.services.join(", ") || "this application"}.`}</p></div><GhostButton onClick={() => setSelected(null)}>Close details</GhostButton></div><dl className="mt-4 grid gap-3 text-sm sm:grid-cols-2 lg:grid-cols-4"><div><dt className="text-muted">Category</dt><dd>{configurationCategory(selected.name)}</dd></div><div><dt className="text-muted">Scope</dt><dd>{selectedEnvironment?.name || "Select environment"}</dd></div><div><dt className="text-muted">Classification</dt><dd>{selected.secret ? "Secret" : "Public"}; {selected.required ? "required" : "optional"}</dd></div><div><dt className="text-muted">Status</dt><dd>{selected.status}</dd></div><div><dt className="text-muted">Source</dt><dd className="break-all">{selected.sourcePaths?.join(", ") || selected.applicationPath || "Manual"}</dd></div><div><dt className="text-muted">Active version</dt><dd>{selected.activeVersion || "None"}</dd></div><div><dt className="text-muted">Validation</dt><dd>{latestVersion(selected)?.validationState || "Not run"}</dd></div><div><dt className="text-muted">Restart/rebuild effect</dt><dd>{selected.usage === "build" ? "Frontend rebuild" : "Affected service restart"}</dd></div></dl><div className="mt-4 flex flex-wrap gap-2"><Button onClick={() => setEditing(selected)}>{selected.secret && selected.activeVersion ? "Rotate Secret" : selected.activeVersion ? "Update Variable" : "Add Value"}</Button><GhostButton disabled>Validate</GhostButton><GhostButton disabled>View History</GhostButton><GhostButton disabled>Roll Back</GhostButton></div></Card>}

    {editing && <Card><div className="flex justify-between"><div><h3 className="font-semibold">Controlled change: {editing.name}</h3><p className="text-sm text-muted">The previous secret is never revealed. Saving creates a pending version and does not deploy it.</p></div><GhostButton onClick={() => { setEditing(null); setValue(""); setReason(""); setOperation("update"); }}>Cancel and clear</GhostButton></div><div className="mt-3 grid gap-2"><label className="text-sm">Operation<Select aria-label="Configuration operation" value={operation} onChange={(event) => setOperation(event.target.value as typeof operation)}><option value="update">Add or replace</option><option value="disable">Disable optional entry</option>{editing.removalPermitted && !editing.required && <option value="remove">Remove obsolete entry</option>}</Select></label>{operation === "update" && <Field aria-label="Configuration value" type={editing.secret ? "password" : "text"} autoComplete="off" value={value} onChange={(event) => setValue(event.target.value)} placeholder={editing.secret ? "Replacement secret" : "Replacement value"} />}<Field aria-label="Change reason" value={reason} onChange={(event) => setReason(event.target.value)} placeholder="Why is this changing?" /><p className="text-sm text-muted">Risk: {editing.risk || "unclassified"}. Affected services: {editing.services.join(", ") || "application service"}. Activation: {editing.restartRequirement || (editing.usage === "build" ? "rebuild" : "restart")}.</p><Button disabled={!environmentId || (operation === "update" && !value) || reason.trim().length < 4 || createVersion.isPending} onClick={() => createVersion.mutate()}>Save as Pending Deployment</Button></div></Card>}

    <Card><h3 className="font-semibold">Add an environment</h3><div className="mt-3 flex gap-2"><Field aria-label="Environment name" placeholder="Staging, Preview, Development…" value={environmentName} onChange={(event) => setEnvironmentName(event.target.value)} /><Button disabled={!projectId || !environmentName || createEnvironment.isPending} onClick={() => createEnvironment.mutate()}>Add</Button></div></Card>
    {error && <p className="text-sm text-danger">{apiError(error)}</p>}
  </div>;
}
