import { useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { api, apiError } from "./api";
import { Badge, Button, Card, Field, Skeleton, Table } from "./ui";

export function CreditsProvidersPage({ isAdmin, toast }: { isAdmin: boolean; toast: (message: string) => void }) {
  const client = useQueryClient(); const [credits, setCredits] = useState(""); const [reason, setReason] = useState("");
  const summary = useQuery({ queryKey: ["credit-summary"], queryFn: () => api.get("/credits/summary").then((r) => r.data) });
  const ledger = useQuery({ queryKey: ["credit-ledger"], queryFn: () => api.get("/credits/ledger?limit=50").then((r) => r.data.items) });
  const usage = useQuery({ queryKey: ["credit-usage"], queryFn: () => api.get("/credits/usage-requests?limit=50").then((r) => r.data.items) });
  const controls = useMutation({ mutationFn: (enabled: boolean) => api.put("/credits/emergency-controls", { globalAiEnabled: enabled, organizationAiEnabled: enabled, providerEnabled: summary.data?.controls?.providerEnabled || {}, modelEnabled: summary.data?.controls?.modelEnabled || {}, projectEnabled: summary.data?.controls?.projectEnabled || {}, reason: enabled ? "Administrator enabled paid AI" : "Administrator emergency shutoff" }), onSuccess: () => { client.invalidateQueries({ queryKey: ["credit-summary"] }); toast("Paid AI controls updated"); } });
  const adjustment = useMutation({ mutationFn: () => api.post("/credits/adjustments", { direction: "credit", credits: Number(credits), reason, idempotencyKey: `manual-${crypto.randomUUID()}` }), onSuccess: () => { setCredits(""); setReason(""); client.invalidateQueries({ queryKey: ["credit-summary"] }); client.invalidateQueries({ queryKey: ["credit-ledger"] }); toast("Credit adjustment recorded"); } });
  if (summary.isLoading) return <Skeleton />; if (summary.isError) return <Card><p role="alert" className="text-sm text-danger">{apiError(summary.error)}</p></Card>;
  const data = summary.data; const monthly = (data.policies || []).filter((p: any) => p.policyType === "monthly").map((p: any) => p.limitCredits).sort((a: number,b: number) => a-b)[0]; const percent = monthly ? Math.min(100, Math.round(data.usedThisMonth / monthly * 100)) : 0;
  return <div className="space-y-5">
    <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Metric label="Available credits" value={data.account.availableCredits} /><Metric label="Reserved credits" value={data.account.reservedCredits} /><Metric label="Used today" value={data.usedToday} /><Metric label="Used this month" value={data.usedThisMonth} detail={monthly ? `${percent}% of ${monthly.toLocaleString()} cap` : "No monthly cap configured"} /></div>
    <Card><div className="flex flex-wrap items-center justify-between gap-4"><div><h2 className="font-semibold">Paid AI status</h2><p className="mt-1 text-sm text-muted">Deterministic Foundry operations remain available when paid AI is off.</p></div><div className="flex items-center gap-3"><Badge tone={data.aiEnabled ? "success" : "warning"}>{data.aiEnabled ? "Enabled" : "Paused"}</Badge>{isAdmin && <Button disabled={controls.isPending} onClick={() => controls.mutate(!data.aiEnabled)}>{data.aiEnabled ? "Emergency shutoff" : "Enable paid AI"}</Button>}</div></div>{controls.isError && <p role="alert" className="mt-3 text-sm text-danger">{apiError(controls.error)}</p>}</Card>
    <Card><h2 className="font-semibold">Budget controls</h2>{(data.policies || []).length ? <div className="mt-3 grid gap-2 md:grid-cols-2">{data.policies.map((p: any) => <div key={p._id} className="rounded border border-border p-3 text-sm"><strong>{p.policyType.replaceAll("_", " ")}</strong><div className="text-muted">{p.limitCredits.toLocaleString()} credits · {p.hardLimit ? "hard limit" : "warning"}</div></div>)}</div> : <p className="mt-2 text-sm text-muted">No paid-AI budget is configured. Paid execution remains disabled by default.</p>}</Card>
    {isAdmin && <Card><h2 className="font-semibold">Administrative adjustment</h2><p className="mt-1 text-sm text-muted">Creates a permanent append-only entry. Historical rows cannot be edited or deleted.</p><div className="mt-3 grid gap-3 md:grid-cols-[180px_1fr_auto]"><Field aria-label="Credits" type="number" min="1" step="1" placeholder="Credits" value={credits} onChange={(e) => setCredits(e.target.value)} /><Field aria-label="Adjustment reason" placeholder="Required reason" value={reason} onChange={(e) => setReason(e.target.value)} /><Button disabled={adjustment.isPending || !Number.isInteger(Number(credits)) || Number(credits) <= 0 || reason.trim().length < 5} onClick={() => adjustment.mutate()}>Add credit</Button></div>{adjustment.isError && <p role="alert" className="mt-3 text-sm text-danger">{apiError(adjustment.error)}</p>}</Card>}
    <Card><h2 className="font-semibold">Usage ledger</h2>{ledger.isLoading ? <Skeleton /> : <div className="mt-3 overflow-x-auto"><Table columns={["Timestamp","Operation","Provider / model","Estimate","Actual","Status","Credit delta"]} rows={(ledger.data || []).map((item: any) => [new Date(item.createdAt).toLocaleString(), item.entryType, `${item.provider || "—"} / ${item.model || "—"}`, item.estimatedCredits ?? "—", item.actualCredits ?? "—", item.status, item.creditDelta])} empty="No credit-changing entries yet." /></div>}</Card>
    <Card><h2 className="font-semibold">Provider cost view</h2>{usage.isLoading ? <Skeleton /> : <div className="mt-3 overflow-x-auto"><Table columns={["Started","Operation","Provider / model","Estimated credits","Actual credits","Variance","Status"]} rows={(usage.data || []).map((item: any) => [new Date(item.startedAt).toLocaleString(), item.operationType, `${item.provider} / ${item.model}`, item.estimatedCredits, item.actualCredits ?? "—", item.actualCredits == null ? "—" : item.actualCredits - item.estimatedCredits, item.status])} empty="No AI usage requests yet." /></div>}</Card>
  </div>;
}
function Metric({ label, value, detail }: { label: string; value: number; detail?: string }) { return <Card><div className="text-sm text-muted">{label}</div><div className="mt-1 text-2xl font-semibold">{Number(value || 0).toLocaleString()}</div>{detail && <div className="mt-1 text-xs text-muted">{detail}</div>}</Card>; }
