import { useState } from "react";
import { useMutation, useQuery, useQueryClient, type UseQueryResult } from "@tanstack/react-query";
import { AlertTriangle, BarChart3, Check, FileUp, Info, LineChart, RefreshCw, Target, TrendingDown, TrendingUp } from "lucide-react";
import { api, apiError } from "./api";
import { Badge, Button, Card, GhostButton, Select, Skeleton, Table } from "./ui";

type CompareMode = "none" | "previous_period" | "previous_year";
type DateRange = { start: string; end: string; compare: CompareMode };
type NullableNumber = number | null;
type MarketingTotals = { spend: NullableNumber; impressions: NullableNumber; reach: NullableNumber; clicks: NullableNumber; landingPageViews: NullableNumber; leads: NullableNumber; applications: NullableNumber; signups: NullableNumber; purchases: NullableNumber; conversions: NullableNumber; revenue: NullableNumber; videoViews: NullableNumber; videoCompletions: NullableNumber };
type MarketingDerived = { ctr: NullableNumber; landingPageViewRate: NullableNumber; leadConversionRate: NullableNumber; conversionRate: NullableNumber; purchaseConversionRate: NullableNumber; cpc: NullableNumber; costPerLead: NullableNumber; costPerConversion: NullableNumber; costPerPurchase: NullableNumber; roas: NullableNumber; averageOrderValue: NullableNumber };
type Overview = { range: DateRange; currency: string | null; totals: MarketingTotals; derived: MarketingDerived; comparison: null | { totals?: MarketingTotals; derived?: MarketingDerived; changes: Record<string, NullableNumber> }; hasData: boolean };

const chartMetricOptions = ["spend", "impressions", "clicks", "leads", "conversions", "revenue", "roas"] as const;
const labels: Record<string, string> = { spend: "Spend", impressions: "Impressions", reach: "Reach", clicks: "Clicks", landingPageViews: "Landing-page views", leads: "Leads", applications: "Maker applications", signups: "Sign-ups", purchases: "Purchases", conversions: "Conversions", revenue: "Revenue", ctr: "Click-through rate", cpc: "Cost per click", conversionRate: "Conversion rate", costPerLead: "Cost per lead", costPerConversion: "Cost per acquisition", roas: "Return on ad spend", averageOrderValue: "Average order value" };
const descriptions: Record<string, string> = { spend: "Total advertising spend supplied for the selected period.", clicks: "Total recorded advertising and attributed channel clicks.", conversions: "Applications, sign-ups, and purchases recorded during this period.", revenue: "Attributed revenue supplied by connected or imported sources.", roas: "Attributed revenue divided by advertising spend. Attribution may be estimated.", ctr: "Clicks divided by impressions.", cpc: "Advertising spend divided by clicks.", conversionRate: "Conversions divided by landing-page views." };

function dateString(date: Date) { return date.toISOString().slice(0, 10); }
function daysAgo(days: number) { const date = new Date(); date.setUTCHours(0, 0, 0, 0); date.setUTCDate(date.getUTCDate() - days); return dateString(date); }
function initialRange(): DateRange { return { start: daysAgo(29), end: daysAgo(0), compare: "previous_period" }; }
function params(range: DateRange) { return new URLSearchParams(range).toString(); }
function currency(value: NullableNumber, code = "USD") { return value === null ? "Not available" : new Intl.NumberFormat("en-US", { style: "currency", currency: code, maximumFractionDigits: 2 }).format(value); }
function number(value: NullableNumber) { return value === null ? "Not available" : new Intl.NumberFormat("en-US", { maximumFractionDigits: 0 }).format(value); }
function percent(value: NullableNumber) { return value === null ? "Not available" : `${value.toFixed(2)}%`; }
function roas(value: NullableNumber) { return value === null ? "Not available" : `${value.toFixed(2)}×`; }
function changeText(value: NullableNumber) { return value === null ? "No comparison available" : `${value > 0 ? "+" : ""}${value.toFixed(1)}% vs comparison`; }
function linePoints(points: Array<Record<string, number | string | null>>, metric: string) {
  const values = points.map((point) => typeof point[metric] === "number" ? point[metric] as number : null); const available = values.filter((value): value is number => value !== null);
  if (!available.length) return ""; const minimum = Math.min(...available); const maximum = Math.max(...available); const span = maximum - minimum || Math.abs(maximum) || 1;
  return values.map((value, index) => value === null ? null : `${10 + (points.length === 1 ? 350 : index / (points.length - 1) * 700)},${210 - (value - minimum) / span * 190}`).filter(Boolean).join(" ");
}

function MetricCard({ label, value, comparison, change, description, lowerIsBetter = false, loading }: { label: string; value: string; comparison?: string; change?: NullableNumber; description?: string; lowerIsBetter?: boolean; loading?: boolean }) {
  if (loading) return <Card><div aria-label={`${label} loading`}><Skeleton /></div></Card>;
  const status = change === null || change === undefined || change === 0 ? "neutral" : (lowerIsBetter ? change < 0 : change > 0) ? "positive" : "negative";
  return <Card><div className="flex items-start justify-between gap-2"><h3 className="text-sm font-medium text-muted">{label}</h3>{description && <button type="button" aria-label={`Explain ${label}`} title={description} className="rounded text-muted focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-primary"><Info className="h-4 w-4" /></button>}</div><div className="mt-2 break-words text-2xl font-semibold">{value}</div>{comparison !== undefined && <div className="mt-1 text-xs text-muted">Comparison: {comparison}</div>}{change !== undefined && <div className={`mt-2 flex items-center gap-1 text-xs ${status === "positive" ? "text-success" : status === "negative" ? "text-danger" : "text-muted"}`} aria-label={`${label}: ${changeText(change)}`}>{change !== null && change > 0 ? <TrendingUp className="h-3.5 w-3.5" /> : change !== null && change < 0 ? <TrendingDown className="h-3.5 w-3.5" /> : null}{changeText(change)}</div>}</Card>;
}

function DateControls({ value, onChange }: { value: DateRange; onChange: (value: DateRange) => void }) {
  const [preset, setPreset] = useState("last_30");
  const applyPreset = (next: string) => {
    setPreset(next); const today = new Date(); today.setUTCHours(0, 0, 0, 0); let start = new Date(today); let end = new Date(today);
    if (next === "today") start = today;
    else if (next === "yesterday") { start.setUTCDate(start.getUTCDate() - 1); end = new Date(start); }
    else if (next === "last_7") start.setUTCDate(start.getUTCDate() - 6);
    else if (next === "last_30") start.setUTCDate(start.getUTCDate() - 29);
    else if (next === "last_90") start.setUTCDate(start.getUTCDate() - 89);
    else if (next === "this_month") start = new Date(Date.UTC(today.getUTCFullYear(), today.getUTCMonth(), 1));
    else if (next === "previous_month") { start = new Date(Date.UTC(today.getUTCFullYear(), today.getUTCMonth() - 1, 1)); end = new Date(Date.UTC(today.getUTCFullYear(), today.getUTCMonth(), 0)); }
    else return;
    onChange({ ...value, start: dateString(start), end: dateString(end) });
  };
  return <fieldset className="grid gap-2 rounded-lg border border-border bg-panel p-3 sm:grid-cols-2 lg:grid-cols-4"><legend className="px-1 text-xs font-semibold uppercase tracking-wide text-muted">Reporting range</legend><label className="text-xs text-muted">Date range<Select aria-label="Marketing date range" value={preset} onChange={(event) => applyPreset(event.target.value)} className="mt-1"><option value="today">Today</option><option value="yesterday">Yesterday</option><option value="last_7">Last 7 days</option><option value="last_30">Last 30 days</option><option value="last_90">Last 90 days</option><option value="this_month">This month</option><option value="previous_month">Previous month</option><option value="custom">Custom</option></Select></label><label className="text-xs text-muted">Start<input aria-label="Marketing start date" type="date" value={value.start} onChange={(event) => { setPreset("custom"); onChange({ ...value, start: event.target.value }); }} className="mt-1 h-10 w-full rounded-md border border-border bg-background px-3 text-sm text-text" /></label><label className="text-xs text-muted">End<input aria-label="Marketing end date" type="date" value={value.end} onChange={(event) => { setPreset("custom"); onChange({ ...value, end: event.target.value }); }} className="mt-1 h-10 w-full rounded-md border border-border bg-background px-3 text-sm text-text" /></label><label className="text-xs text-muted">Compare<Select aria-label="Marketing comparison" value={value.compare} onChange={(event) => onChange({ ...value, compare: event.target.value as CompareMode })} className="mt-1"><option value="previous_period">Previous period</option><option value="previous_year">Previous year</option><option value="none">No comparison</option></Select></label></fieldset>;
}

function PerformanceChart({ range }: { range: DateRange }) {
  const [metrics, setMetrics] = useState<string[]>(["spend", "clicks", "conversions"]);
  const query = useQuery({ queryKey: ["marketing-timeseries", range, metrics], queryFn: () => api.get(`/marketing/timeseries?${params(range)}&metrics=${metrics.join(",")}`).then((response) => response.data) });
  const toggle = (metric: string) => setMetrics((current) => current.includes(metric) ? current.length === 1 ? current : current.filter((value) => value !== metric) : current.length >= 3 ? current : [...current, metric]);
  const points = query.data?.points || [];
  const colors = ["#2dd4bf", "#38bdf8", "#a78bfa"];
  return <Card><div className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="font-semibold">Performance trend</h2><p className="text-xs text-muted">Compare up to three normalized metrics.</p></div><div className="flex flex-wrap gap-2" aria-label="Chart metrics">{chartMetricOptions.map((metric) => <label key={metric} className={`flex items-center gap-1 rounded-full border px-2 py-1 text-xs ${metrics.includes(metric) ? "border-primary text-text" : "border-border text-muted"}`}><input type="checkbox" checked={metrics.includes(metric)} disabled={!metrics.includes(metric) && metrics.length >= 3} onChange={() => toggle(metric)} />{labels[metric]}</label>)}</div></div>{query.isLoading ? <div className="mt-4"><Skeleton /></div> : points.length ? <div className="mt-5"><div className="mb-2 flex flex-wrap gap-3 text-xs text-muted">{metrics.map((metric, index) => <span key={metric} className="flex items-center gap-1"><span className="h-0.5 w-4" style={{ backgroundColor: colors[index] }} />{labels[metric]}</span>)}</div><svg className="h-56 w-full rounded-md border border-border bg-background/30" viewBox="0 0 720 220" role="img" aria-label={`Performance line chart for ${metrics.map((metric) => labels[metric]).join(", ")}. Each metric uses its own normalized scale. A data table follows.`} preserveAspectRatio="none">{[20, 67.5, 115, 162.5, 210].map((y) => <line key={y} x1="10" x2="710" y1={y} y2={y} stroke="currentColor" className="text-border" strokeWidth="1" />)}{metrics.map((metric, index) => <polyline key={metric} points={linePoints(points, metric)} fill="none" stroke={colors[index]} strokeWidth="3" strokeLinecap="round" strokeLinejoin="round" vectorEffect="non-scaling-stroke" />)}</svg><div className="mt-3 max-h-44 overflow-auto"><Table columns={["Date", ...metrics.map((metric) => labels[metric])]} rows={points.map((point: Record<string, number | null>) => [point.date, ...metrics.map((metric) => number(point[metric]))])} /></div></div> : <p className="mt-5 rounded-md border border-dashed border-border p-6 text-center text-sm text-muted">No time-series data is available for this period.</p>}</Card>;
}

function Funnel({ range }: { range: DateRange }) {
  const query = useQuery({ queryKey: ["marketing-funnel", range], queryFn: () => api.get(`/marketing/funnel?${params(range)}`).then((response) => response.data) });
  return <Card><h2 className="font-semibold">Conversion funnel</h2><p className="text-xs text-muted">Stage-to-stage rates use only recorded data.</p>{query.isLoading ? <div className="mt-4"><Skeleton /></div> : <ol className="mt-4 space-y-2">{(query.data?.stages || []).map((stage: { label: string; value: NullableNumber; rateFromPrevious: NullableNumber }, index: number) => <li key={stage.label} className="rounded-md border border-border bg-background/50 p-3"><div className="flex items-center justify-between gap-2"><span className="text-sm">{index + 1}. {stage.label}</span><strong>{number(stage.value)}</strong></div>{index > 0 && <div className="mt-1 text-xs text-muted">{stage.rateFromPrevious === null ? "Rate not available" : `${stage.rateFromPrevious.toFixed(2)}% from previous stage`}</div>}</li>)}</ol>}</Card>;
}

function ChannelTable({ range }: { range: DateRange }) {
  const query = useQuery({ queryKey: ["marketing-channels", range], queryFn: () => api.get(`/marketing/channels?${params(range)}`).then((response) => response.data) });
  return <Card><h2 className="font-semibold">Channel performance</h2><div className="mt-3">{query.isLoading ? <Skeleton /> : <Table columns={["Channel", "Spend", "Clicks", "Conversions", "Conversion rate", "Revenue", "ROAS"]} empty="No channel data is available for this period." rows={(query.data?.channels || []).map((item: { channel: string; currency: string | null; totals: MarketingTotals; derived: MarketingDerived }) => [item.channel, currency(item.totals.spend, item.currency || "USD"), number(item.totals.clicks), number(item.totals.conversions), percent(item.derived.conversionRate), currency(item.totals.revenue, item.currency || "USD"), roas(item.derived.roas)])} />}</div></Card>;
}

function CampaignTable({ range }: { range: DateRange }) {
  const query = useQuery({ queryKey: ["marketing-campaigns", range], queryFn: () => api.get(`/marketing/campaigns?${params(range)}`).then((response) => response.data) });
  return <Card><h2 className="font-semibold">Campaign performance</h2><div className="mt-3">{query.isLoading ? <Skeleton /> : <Table columns={["Campaign", "Provider", "Status", "Spend", "Impressions", "Clicks", "CTR", "Leads", "Conversions", "CPA", "Revenue", "ROAS"]} empty="No campaign data is available for this period." rows={(query.data?.campaigns || []).map((item: { id: string; name: string; provider: string; status: string; currency: string | null; totals: MarketingTotals; derived: MarketingDerived }) => [item.name, item.provider, <Badge tone={item.status === "active" ? "success" : "neutral"}>{item.status}</Badge>, currency(item.totals.spend, item.currency || "USD"), number(item.totals.impressions), number(item.totals.clicks), percent(item.derived.ctr), number(item.totals.leads), number(item.totals.conversions), currency(item.derived.costPerConversion, item.currency || "USD"), currency(item.totals.revenue, item.currency || "USD"), roas(item.derived.roas)])} />}</div></Card>;
}

function CsvImport({ range }: { range: DateRange }) {
  const client = useQueryClient(); const [csv, setCsv] = useState(""); const [fileName, setFileName] = useState(""); const [preview, setPreview] = useState<any>(null); const [summary, setSummary] = useState<any>(null);
  const previewMutation = useMutation({ mutationFn: () => api.post("/marketing/imports/preview", { csv }).then((response) => response.data), onSuccess: (data) => { setPreview(data); setSummary(null); } });
  const importMutation = useMutation({ mutationFn: () => api.post("/marketing/imports", { csv, previewDigest: preview.previewDigest }).then((response) => response.data), onSuccess: (data) => { setSummary(data); setPreview(null); client.invalidateQueries({ queryKey: ["marketing-overview"] }); client.invalidateQueries({ queryKey: ["marketing-campaigns"] }); client.invalidateQueries({ queryKey: ["marketing-channels"] }); client.invalidateQueries({ queryKey: ["marketing-funnel"] }); client.invalidateQueries({ queryKey: ["marketing-timeseries"] }); } });
  return <Card><div className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="font-semibold">Manual CSV import</h2><p className="text-sm text-muted">Upload up to 5,000 normalized daily rows. Preview and validation are required before import.</p></div><FileUp className="h-6 w-6 text-primary" /></div><label className="mt-4 block rounded-md border border-dashed border-border p-4 text-sm">CSV file<input aria-label="Marketing CSV file" type="file" accept=".csv,text/csv" className="mt-2 block w-full text-sm" onChange={async (event) => { const file = event.target.files?.[0]; if (!file) return; setFileName(file.name); setCsv(await file.text()); setPreview(null); setSummary(null); }} /></label>{fileName && <p className="mt-2 text-xs text-muted">Selected: {fileName}</p>}<div className="mt-3 flex flex-wrap gap-2"><Button disabled={!csv || previewMutation.isPending} onClick={() => previewMutation.mutate()}>{previewMutation.isPending ? "Validating…" : "Preview import"}</Button>{preview && <Button disabled={importMutation.isPending} onClick={() => importMutation.mutate()}>{importMutation.isPending ? "Importing…" : `Confirm ${preview.rowCount} rows`}</Button>}</div>{previewMutation.isError && <p role="alert" className="mt-3 text-sm text-danger">{apiError(previewMutation.error)}</p>}{importMutation.isError && <p role="alert" className="mt-3 text-sm text-danger">{apiError(importMutation.error)}</p>}{preview && <div className="mt-4"><h3 className="text-sm font-semibold">Validated preview</h3><Table columns={["Date", "Provider", "Channel", "Campaign", "Spend", "Clicks", "Purchases", "Revenue"]} rows={preview.rows.map((row: any) => [row.date, row.provider, row.channel, row.campaign, currency(row.spend ?? null, row.currency), number(row.clicks ?? null), number(row.purchases ?? null), currency(row.revenue ?? null, row.currency)])} /></div>}{summary && <p role="status" className="mt-4 flex items-center gap-2 text-sm text-success"><Check className="h-4 w-4" />Import complete: {summary.imported} added, {summary.updated} updated, {summary.skipped} unchanged.</p>}<p className="mt-3 text-xs text-muted">Imported rows update the selected reporting period automatically. Current range: {range.start} to {range.end}.</p></Card>;
}

function OverviewContent({ range, overview }: { range: DateRange; overview: UseQueryResult<Overview> }) {
  const data = overview.data; const code = data?.currency || "USD"; const top = [["spend", currency(data?.totals.spend ?? null, code), currency(data?.comparison?.totals?.spend ?? null, code)], ["clicks", number(data?.totals.clicks ?? null), number(data?.comparison?.totals?.clicks ?? null)], ["conversions", number(data?.totals.conversions ?? null), number(data?.comparison?.totals?.conversions ?? null)], ["revenue", currency(data?.totals.revenue ?? null, code), currency(data?.comparison?.totals?.revenue ?? null, code)], ["roas", roas(data?.derived.roas ?? null), roas(data?.comparison?.derived?.roas ?? null)]];
  const secondary = [["impressions", number(data?.totals.impressions ?? null), number(data?.comparison?.totals?.impressions ?? null)], ["reach", number(data?.totals.reach ?? null), number(data?.comparison?.totals?.reach ?? null)], ["ctr", percent(data?.derived.ctr ?? null), percent(data?.comparison?.derived?.ctr ?? null)], ["cpc", currency(data?.derived.cpc ?? null, code), currency(data?.comparison?.derived?.cpc ?? null, code)], ["landingPageViews", number(data?.totals.landingPageViews ?? null), number(data?.comparison?.totals?.landingPageViews ?? null)], ["leads", number(data?.totals.leads ?? null), number(data?.comparison?.totals?.leads ?? null)], ["applications", number(data?.totals.applications ?? null), number(data?.comparison?.totals?.applications ?? null)], ["signups", number(data?.totals.signups ?? null), number(data?.comparison?.totals?.signups ?? null)], ["purchases", number(data?.totals.purchases ?? null), number(data?.comparison?.totals?.purchases ?? null)], ["conversionRate", percent(data?.derived.conversionRate ?? null), percent(data?.comparison?.derived?.conversionRate ?? null)], ["costPerLead", currency(data?.derived.costPerLead ?? null, code), currency(data?.comparison?.derived?.costPerLead ?? null, code)], ["costPerConversion", currency(data?.derived.costPerConversion ?? null, code), currency(data?.comparison?.derived?.costPerConversion ?? null, code)], ["averageOrderValue", currency(data?.derived.averageOrderValue ?? null, code), currency(data?.comparison?.derived?.averageOrderValue ?? null, code)]];
  const lowerIsBetter = new Set(["spend", "cpc", "costPerLead", "costPerConversion"]);
  return <>{overview.isError && <div role="alert" className="rounded-md border border-danger/40 bg-danger/10 p-4"><h2 className="font-semibold">Marketing analytics could not be loaded</h2><p className="text-sm text-muted">{apiError(overview.error)}</p><GhostButton className="mt-3" onClick={() => overview.refetch()}><RefreshCw className="h-4 w-4" />Retry</GhostButton></div>}{!overview.isLoading && data && !data.hasData && <div className="rounded-md border border-dashed border-border p-6 text-center"><BarChart3 className="mx-auto h-8 w-8 text-muted" /><h2 className="mt-3 font-semibold">No marketing data is available for this period.</h2><p className="mt-1 text-sm text-muted">Connect an account, import a report, or add first-party conversion tracking.</p></div>}<section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-5" aria-label="Marketing summary">{top.map(([key, value, comparison]) => <MetricCard key={key} label={labels[key]} value={value} comparison={data?.comparison ? comparison : undefined} change={data?.comparison?.changes[key]} description={descriptions[key]} lowerIsBetter={lowerIsBetter.has(key)} loading={overview.isLoading} />)}</section><details className="rounded-lg border border-border bg-panel"><summary className="cursor-pointer p-4 font-semibold">All marketing metrics</summary><div className="grid gap-3 p-4 pt-0 sm:grid-cols-2 lg:grid-cols-4">{secondary.map(([key, value, comparison]) => <MetricCard key={key} label={labels[key]} value={value} comparison={data?.comparison ? comparison : undefined} change={data?.comparison?.changes[key]} description={descriptions[key]} lowerIsBetter={lowerIsBetter.has(key)} loading={overview.isLoading} />)}</div></details><div className="grid gap-4 xl:grid-cols-[1.7fr_1fr]"><PerformanceChart range={range} /><Funnel range={range} /></div><ChannelTable range={range} /><CampaignTable range={range} /><Card><div className="flex items-start gap-3"><AlertTriangle className="mt-0.5 h-5 w-5 text-warning" /><div><h2 className="font-semibold">Alerts and recommendations</h2><p className="mt-1 text-sm text-muted">Deterministic alerts and AI-assisted recommendations will appear only after minimum data requirements are met. Recommendations are not guarantees and cannot change campaigns or websites directly.</p></div></div></Card><CsvImport range={range} /></>;
}

export function MarketingAnalyticsPage() {
  const [range, setRange] = useState<DateRange>(initialRange); const route = window.location.pathname.replace(/^\/marketing\/?/, "") || "overview";
  const overview = useQuery<Overview>({ queryKey: ["marketing-overview", range], queryFn: () => api.get(`/marketing/overview?${params(range)}`).then((response) => response.data) });
  const tabs = ["overview", "campaigns", "channels", "conversions", "content", "attribution", "reports", "settings"];
  const title = route === "overview" ? "Performance Overview" : route.charAt(0).toUpperCase() + route.slice(1);
  return <div className="marketing-analytics space-y-4"><header className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-xs font-semibold uppercase tracking-widest text-primary">Marketing Analytics</p><h2 className="mt-1 text-2xl font-semibold">{title}</h2><p className="mt-1 max-w-2xl text-sm text-muted">Track campaign spend, traffic, conversions, and attributed revenue across organization-scoped channels.</p></div><Target className="h-8 w-8 text-primary" /></header><nav aria-label="Marketing Analytics sections" className="flex gap-2 overflow-x-auto pb-1">{tabs.map((tab) => <a key={tab} href={tab === "overview" ? "/marketing" : `/marketing/${tab}`} aria-current={route === tab ? "page" : undefined} className={`min-h-11 whitespace-nowrap rounded-md border px-3 py-2 text-sm capitalize focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-primary ${route === tab ? "border-primary bg-primary/10 text-text" : "border-border text-muted"}`}>{tab}</a>)}</nav><DateControls value={range} onChange={setRange} />{route === "overview" && <OverviewContent range={range} overview={overview} />}{route === "campaigns" && <CampaignTable range={range} />}{route === "channels" && <ChannelTable range={range} />}{route === "conversions" && <Funnel range={range} />}{route === "settings" && <Card><h2 className="font-semibold">Marketing settings</h2><p className="mt-2 text-sm text-muted">Provider connections, currency, timezone, attribution, consent, thresholds, and retention controls will be enabled through administrator-only reviewed settings. No provider credentials are configured or exposed in Phase 1.</p></Card>}{["content", "attribution", "reports"].includes(route) && <Card><LineChart className="h-6 w-6 text-primary" /><h2 className="mt-3 font-semibold">{title}</h2><p className="mt-1 text-sm text-muted">This workspace is reserved for the next reviewed marketing analytics phase. Phase 1 data remains available in Overview, Campaigns, Channels, and Conversions.</p></Card>}</div>;
}

export const marketingFormatters = { currency, number, percent, roas };
