import { useEffect, useMemo, useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Bot, ChevronLeft, Download, Monitor, Plus, Save, Smartphone, Sparkles, Trash2 } from "lucide-react";
import type { WebsiteBuilderContent } from "@control-center/shared";
import { api, apiError } from "./api";
import { Badge, Button, Card, Field, GhostButton, Skeleton } from "./ui";
import { renderWebsiteDocument, websiteBuilderFilename } from "./websiteBuilderExport";

type BuilderState = {
  project: { id: string; name: string; slug: string };
  draft: null | { id: string; revision: number; source: "manual" | "ai"; content: WebsiteBuilderContent; createdAt: string; updatedAt: string };
  history: Array<{ id: string; revision: number; source: "manual" | "ai"; createdAt: string }>;
  ai: { enabled: boolean; provider: string | null; model: string | null; automaticRequests: false };
  publication: { enabled: false; reason: string };
};

const starter = (name: string): WebsiteBuilderContent => ({
  siteName: name, tagline: `Welcome to ${name}`, description: "A clear, modern website designed to turn attention into action.", primaryCta: "Get started",
  palette: { primary: "#06b6d4", accent: "#22c55e", background: "#07131f", text: "#f8fafc" },
  sections: [
    { id: "hero", type: "hero", heading: `Meet ${name}`, body: "Describe what makes your business valuable and why visitors should care.", buttonLabel: "Get started" },
    { id: "features", type: "features", heading: "Everything you need", body: "Highlight your strongest services, products, or customer benefits here." },
    { id: "about", type: "about", heading: "Built with purpose", body: "Share the story, experience, and principles behind your work." },
    { id: "contact", type: "contact", heading: "Let’s build something great", body: "Invite visitors to take the next step.", buttonLabel: "Contact us" }
  ]
});
const areaClass = "min-h-24 w-full resize-y rounded-md border border-border bg-background px-3 py-2 text-sm outline-none focus:border-primary";

export function WebsiteBuilderPage({ projectId, navigate }: { projectId: string; navigate: (path: string) => void }) {
  const client = useQueryClient();
  const query = useQuery<BuilderState>({ queryKey: ["website-builder", projectId], queryFn: () => api.get(`/projects/${projectId}/website-builder`).then((response) => response.data), retry: false });
  const [content, setContent] = useState<WebsiteBuilderContent | null>(null);
  const [baseRevision, setBaseRevision] = useState(0);
  const [contentSource, setContentSource] = useState<"manual" | "ai">("manual");
  const [prompt, setPrompt] = useState("");
  const [device, setDevice] = useState<"desktop" | "mobile">("desktop");
  const [notice, setNotice] = useState("");
  const [initializedFor, setInitializedFor] = useState("");
  useEffect(() => { if (!query.data || initializedFor === projectId) return; setContent(query.data.draft?.content || starter(query.data.project.name)); setBaseRevision(query.data.draft?.revision || 0); setContentSource(query.data.draft?.source || "manual"); setInitializedFor(projectId); }, [initializedFor, projectId, query.data]);
  const save = useMutation({ mutationFn: () => api.post(`/projects/${projectId}/website-builder/drafts`, { baseRevision, source: contentSource, content }).then((response) => response.data), onSuccess: (data) => { setBaseRevision(data.draft.revision); setNotice(`Draft revision ${data.draft.revision} saved.`); client.invalidateQueries({ queryKey: ["website-builder", projectId] }); }, onError: (error) => setNotice(apiError(error)) });
  const generate = useMutation({ mutationFn: () => api.post(`/projects/${projectId}/website-builder/generate`, { prompt, current: content }).then((response) => response.data), onSuccess: (data) => { setContent(data.content); setContentSource("ai"); setNotice(`AI draft generated with ${data.metadata.provider}. Review and save when ready.`); }, onError: (error) => setNotice(apiError(error)) });
  const previewStyle = useMemo(() => content ? { backgroundColor: content.palette.background, color: content.palette.text } : {}, [content]);
  if (query.isLoading) return <Skeleton />;
  if (query.error) return <Card><h2 className="font-semibold">Website Builder unavailable</h2><p role="alert" className="mt-2 text-sm text-danger">{apiError(query.error)}</p><GhostButton className="mt-3" onClick={() => navigate(`/projects/${projectId}/overview`)}>Back to project</GhostButton></Card>;
  if (!query.data || !content) return <Skeleton />;
  const data = query.data;
  const update = <K extends keyof WebsiteBuilderContent>(key: K, value: WebsiteBuilderContent[K]) => setContent((current) => current ? { ...current, [key]: value } : current);
  const updateSection = (index: number, patch: Partial<WebsiteBuilderContent["sections"][number]>) => update("sections", content.sections.map((section, position) => position === index ? { ...section, ...patch } : section));
  const addSection = () => update("sections", [...content.sections, { id: `section-${Date.now()}`, type: "cta", heading: "A clear next step", body: "Give visitors one focused reason to act.", buttonLabel: "Learn more" }]);
  const removeSection = (index: number) => { if (content.sections.length > 2) update("sections", content.sections.filter((_, position) => position !== index)); };
  const download = () => { const url = URL.createObjectURL(new Blob([renderWebsiteDocument(content)], { type: "text/html;charset=utf-8" })); const anchor = document.createElement("a"); anchor.href = url; anchor.download = websiteBuilderFilename(content.siteName); anchor.click(); URL.revokeObjectURL(url); setNotice("Static HTML exported locally. No deployment was performed."); };

  return <div className="space-y-4" data-testid="website-builder">
    <Card><div className="flex flex-wrap items-start justify-between gap-3"><div><button className="mb-2 inline-flex items-center gap-1 text-xs text-muted hover:text-text" onClick={() => navigate(`/projects/${projectId}/overview`)}><ChevronLeft className="h-3.5 w-3.5" /> Project workspace</button><div className="flex items-center gap-2"><Sparkles className="h-5 w-5 text-primary" /><h2 className="text-xl font-semibold">Website Builder</h2></div><p className="mt-1 text-sm text-muted">Design and save responsive website drafts for {data.project.name}.</p></div><div className="flex flex-wrap gap-2"><Badge>Draft v{baseRevision}</Badge><Badge tone={data.ai.enabled ? "success" : "warning"}>AI {data.ai.enabled ? "ready" : "not configured"}</Badge><GhostButton onClick={download}><Download className="h-4 w-4" /> Export HTML</GhostButton><Button disabled={save.isPending} onClick={() => save.mutate()}><Save className="h-4 w-4" />{save.isPending ? "Saving…" : "Save draft"}</Button></div></div><div className="mt-3 rounded-md border border-warning/30 bg-warning/5 p-3 text-xs text-muted"><strong className="text-text">Draft-only boundary:</strong> saving, generating, or exporting here never deploys, publishes, changes DNS, or bypasses owner release approval.</div>{notice && <p role="status" className="mt-3 rounded-md border border-primary/30 bg-primary/5 p-2 text-sm">{notice}</p>}</Card>
    <div className="grid gap-4 xl:grid-cols-[minmax(300px,0.85fr)_minmax(0,1.45fr)]"><div className="space-y-4">
      <Card><div className="flex items-center gap-2"><Bot className="h-4 w-4 text-primary" /><h3 className="font-semibold">Generate with AI</h3></div><p className="mt-1 text-xs text-muted">AI runs only when you press Generate. Generated content remains unsaved until you review it.</p><textarea aria-label="Website brief" className={`${areaClass} mt-3`} value={prompt} onChange={(event) => setPrompt(event.target.value)} placeholder="Describe your audience, offer, tone, and desired call to action…" /><Button className="mt-2 w-full" disabled={!data.ai.enabled || prompt.trim().length < 12 || generate.isPending} onClick={() => generate.mutate()}><Sparkles className="h-4 w-4" />{generate.isPending ? "Generating…" : "Generate website draft"}</Button>{!data.ai.enabled && <p className="mt-2 text-xs text-warning">An administrator must enable and configure an allowlisted AI provider first. The manual builder remains fully available.</p>}</Card>
      <Card><h3 className="font-semibold">Brand and message</h3><div className="mt-3 space-y-3"><label className="block text-xs text-muted">Site name<Field value={content.siteName} maxLength={80} onChange={(event) => update("siteName", event.target.value)} /></label><label className="block text-xs text-muted">Tagline<Field value={content.tagline} maxLength={140} onChange={(event) => update("tagline", event.target.value)} /></label><label className="block text-xs text-muted">Description<textarea className={areaClass} value={content.description} maxLength={400} onChange={(event) => update("description", event.target.value)} /></label><label className="block text-xs text-muted">Primary button<Field value={content.primaryCta} maxLength={40} onChange={(event) => update("primaryCta", event.target.value)} /></label><div className="grid grid-cols-2 gap-2">{Object.entries(content.palette).map(([key, value]) => <label key={key} className="text-xs capitalize text-muted">{key}<span className="mt-1 flex items-center gap-2 rounded-md border border-border p-2"><input aria-label={`${key} color`} type="color" value={value} onChange={(event) => update("palette", { ...content.palette, [key]: event.target.value })} /><span className="font-mono text-[11px]">{value}</span></span></label>)}</div></div></Card>
      <Card><div className="flex items-center justify-between"><h3 className="font-semibold">Page sections</h3><GhostButton disabled={content.sections.length >= 12} onClick={addSection}><Plus className="h-4 w-4" /> Add</GhostButton></div><div className="mt-3 space-y-3">{content.sections.map((section, index) => <fieldset key={section.id} className="rounded-md border border-border p-3"><legend className="px-1 text-xs font-semibold uppercase text-muted">{index + 1}. {section.type}</legend><div className="space-y-2"><select aria-label={`Section ${index + 1} type`} className="h-10 w-full rounded-md border border-border bg-background px-3 text-sm" value={section.type} onChange={(event) => updateSection(index, { type: event.target.value as typeof section.type })}>{["hero", "features", "about", "cta", "contact"].map((type) => <option key={type}>{type}</option>)}</select><Field aria-label={`Section ${index + 1} heading`} value={section.heading} maxLength={120} onChange={(event) => updateSection(index, { heading: event.target.value })} /><textarea aria-label={`Section ${index + 1} body`} className={areaClass} value={section.body} maxLength={800} onChange={(event) => updateSection(index, { body: event.target.value })} /><div className="flex gap-2"><Field aria-label={`Section ${index + 1} button`} placeholder="Optional button label" value={section.buttonLabel || ""} maxLength={40} onChange={(event) => updateSection(index, { buttonLabel: event.target.value || undefined })} /><GhostButton aria-label={`Remove section ${index + 1}`} disabled={content.sections.length <= 2} onClick={() => removeSection(index)}><Trash2 className="h-4 w-4" /></GhostButton></div></div></fieldset>)}</div></Card>
    </div><div className="min-w-0 space-y-4 xl:sticky xl:top-4 xl:self-start">
      <Card><div className="mb-3 flex flex-wrap items-center justify-between gap-2"><div><h3 className="font-semibold">Responsive preview</h3><p className="text-xs text-muted">Safe component preview; no scripts or external resources.</p></div><div className="flex rounded-md border border-border p-1"><button aria-pressed={device === "desktop"} aria-label="Desktop preview" className={`rounded p-2 ${device === "desktop" ? "bg-primary text-slate-950" : "text-muted"}`} onClick={() => setDevice("desktop")}><Monitor className="h-4 w-4" /></button><button aria-pressed={device === "mobile"} aria-label="Mobile preview" className={`rounded p-2 ${device === "mobile" ? "bg-primary text-slate-950" : "text-muted"}`} onClick={() => setDevice("mobile")}><Smartphone className="h-4 w-4" /></button></div></div><div className="overflow-auto rounded-lg bg-slate-950 p-3"><article aria-label="Website preview" className={`mx-auto min-h-[620px] overflow-hidden rounded-md shadow-2xl transition-[max-width] ${device === "mobile" ? "max-w-[390px]" : "max-w-full"}`} style={previewStyle}><header className="flex items-center justify-between border-b border-white/10 px-6 py-4"><strong>{content.siteName}</strong><span className="rounded-full px-3 py-1 text-xs font-semibold" style={{ backgroundColor: content.palette.accent, color: content.palette.background }}>{content.primaryCta}</span></header>{content.sections.map((section, index) => <section key={section.id} className={`${section.type === "hero" ? "px-6 py-20 text-center" : "px-6 py-12"} ${index % 2 ? "bg-white/5" : ""}`}><div className="mx-auto max-w-2xl"><div className="mb-2 text-xs font-semibold uppercase tracking-[.2em]" style={{ color: content.palette.primary }}>{section.type}</div><h4 className={`${section.type === "hero" ? "text-4xl" : "text-2xl"} font-bold leading-tight`}>{section.heading}</h4><p className="mt-4 leading-7 opacity-80">{section.body}</p>{section.buttonLabel && <span className="mt-6 inline-block rounded-md px-4 py-2 text-sm font-semibold" style={{ backgroundColor: content.palette.primary, color: content.palette.background }}>{section.buttonLabel}</span>}</div></section>)}<footer className="border-t border-white/10 px-6 py-6 text-center text-xs opacity-60">© {new Date().getFullYear()} {content.siteName}</footer></article></div></Card>
      <Card><h3 className="font-semibold">Version history</h3>{data.history.length ? <ol className="mt-3 space-y-2 text-sm">{data.history.map((item) => <li key={item.id} className="flex items-center justify-between rounded border border-border p-2"><span>Revision {item.revision} <span className="text-muted">· {item.source}</span></span><time className="text-xs text-muted">{new Date(item.createdAt).toLocaleString()}</time></li>)}</ol> : <p className="mt-2 text-sm text-muted">No saved revisions yet. Your current starter is local until you save it.</p>}</Card>
    </div></div>
  </div>;
}
