import React from "react";
import ReactDOM from "react-dom/client";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import { AgentUpgradesPage } from "../src/AgentUpgradesPage";
import { api } from "../src/api";
import "../src/styles.css";

api.defaults.adapter = async (config) => ({ data: config.url === "/agent-upgrades/inventory" ? { summary: { total: 3, online: 2, offline: 1, upToDate: 1, upgradeAvailable: 0, upgradeRequired: 1, manualBootstrap: 1, failed: 0, rolledBack: 0 }, inventory: [{ serverId: "server-synthetic-01", name: "Staging API", slug: "staging-api", projectId: "project-synthetic-01", projectName: "Sample project", environmentKind: "staging", protected: false, online: true, lastHeartbeatAt: "2026-07-19T14:00:00.000Z", agentVersion: "1.1.0", protocolVersion: "task-v1", capabilities: ["environmentDiscovery", "agentUpgrade"], os: "linux", architecture: "x64", packageType: "tar", releaseChannel: "stable", compatibility: { state: "up_to_date", missingCapabilities: [], latestCompatibleVersion: "1.1.0", latestCompatibleReleaseId: "release-synthetic-110", requiredMinimumVersion: "1.0.0", remoteUpgradeSupported: true, manualBootstrapRequired: false } }, { serverId: "server-synthetic-02", name: "Preview worker", slug: "preview-worker", projectId: "project-synthetic-01", projectName: "Sample project", environmentKind: "preview", protected: false, online: true, lastHeartbeatAt: "2026-07-19T13:58:00.000Z", agentVersion: "1.0.0", protocolVersion: "task-v1", capabilities: ["agentUpgrade"], os: "linux", architecture: "arm64", packageType: "tar", releaseChannel: "stable", compatibility: { state: "upgrade_required", missingCapabilities: ["environmentDiscovery"], latestCompatibleVersion: "1.1.0", latestCompatibleReleaseId: "release-synthetic-110-arm64", requiredMinimumVersion: "1.0.0", remoteUpgradeSupported: true, manualBootstrapRequired: false } }, { serverId: "server-synthetic-03", name: "Legacy staging", slug: "legacy-staging", projectId: "project-synthetic-02", projectName: "Legacy sample", environmentKind: "staging", protected: false, online: false, agentVersion: "0.1.0", capabilities: ["system"], os: "linux", architecture: "x64", packageType: "tar", releaseChannel: "stable", compatibility: { state: "manual_bootstrap_required", missingCapabilities: ["environmentDiscovery"], remoteUpgradeSupported: false, manualBootstrapRequired: true } }] } : { history: [] }, status: 200, statusText: "OK", headers: {}, config });

ReactDOM.createRoot(document.getElementById("root")!).render(<React.StrictMode><QueryClientProvider client={new QueryClient({ defaultOptions: { queries: { retry: false } } })}><main className="min-h-screen bg-background p-4 text-text"><AgentUpgradesPage toast={() => undefined} /></main></QueryClientProvider></React.StrictMode>);
