import React from "react";
import ReactDOM from "react-dom/client";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import { AiAssistantPanel } from "../src/AiAssistantPanel";
import { AiSettingsCard } from "../src/AiSettingsCard";
import { SystemHealthCard } from "../src/SystemHealthCard";
import { api } from "../src/api";
import "../src/styles.css";

api.defaults.adapter = async (config) => {
  if (config.url === "/system/health") return { data: { status: "ready", api: { status: "ready" }, mongo: { status: "ready" }, agent: { status: "monitoring" }, backgroundWorkers: { status: "not_configured" }, ai: { status: "disabled", organizationState: "disabled", provider: "none", credentialPresent: false }, audit: { status: "ready" }, rateLimiting: { status: "ready" }, cache: { status: "ready" }, build: { version: "0.1.0", commit: "browser-validation", branch: "validation/discovery-hardening-linux" }, featureFlags: { aiAssistant: false, operationalIntelligence: true } }, status: 200, statusText: "OK", headers: {}, config };
  if (config.url === "/ai-assistant/status") return { data: { enabled: true, configured: true, provider: "mock", model: "deterministic-v1", roles: [{ id: "operations_analyst", label: "Operations analyst", description: "Explains current health evidence.", suggestedQuestions: ["Explain the current health evidence."], allowedScopeTypes: ["server", "application"], readOnly: true }], readOnly: true }, status: 200, statusText: "OK", headers: {}, config };
  if (config.url === "/org/ai-assistant") return { data: { globalEnabled: true, settings: { enabled: false, maximumRequestsPerUserPerHour: 20, maximumRequestsPerOrganizationPerDay: 200, maximumConcurrentRequests: 3, allowedScopeTypes: ["server", "application"], dataRetentionMode: "provider-dependent" }, allowlists: { providers: ["mock"], models: ["deterministic-v1"], modelsByProvider: { mock: ["deterministic-v1"] } }, providers: [{ id: "mock", label: "Deterministic mock", state: "ready", credentialPresent: true, modelCount: 1 }], providerStatus: { configured: true, credentialPresent: true, provider: "mock", model: "deterministic-v1" }, usage: { organizationRequestsToday: 2, organizationRequestsThisMonth: 5, tokensThisMonth: 0, lastSuccessfulRequestAt: null, lastFailureCategory: null }, readOnly: true, noActionsCanBeExecuted: true }, status: 200, statusText: "OK", headers: {}, config };
  const timestamp = new Date().toISOString();
  return { data: { result: { summary: "The server is reachable; the latest fresh evidence is healthy.", status: "healthy", confidence: "high", risk: "low", likelyCauses: [{ title: "Current operational state", score: 0.64, evidence: ["Server status: online", "Backend health: healthy"] }], recommendedSteps: [{ order: 1, title: "Verify current health", description: "Confirm the latest health timestamp before making a manual decision.", classification: "low_risk_diagnostic", evidence: ["Backend health: healthy"], actionType: "manual_diagnostic" }], evidence: [{ sourceType: "server", label: "Server status", value: "online", timestamp, freshness: "fresh", source: "servers.currentState", confidence: "high" }, { sourceType: "health_check", label: "Backend health", value: "healthy", timestamp, freshness: "fresh", source: "health_checks", confidence: "high" }, { sourceType: "deployment", label: "deployments", value: "1 records", timestamp, freshness: "fresh", source: "agent_tasks", confidence: "high" }], alternativePossibilities: ["A dependency outside collected telemetry may still be involved."], timeline: [{ timestamp, event: "Deployment succeeded", source: "deployment", confidence: "high" }], relatedIncidents: [{ id: "incident-1", summary: "deployment deploy-42", similarity: 0.72, timestamp }], limitations: ["Secrets are excluded."], executedActions: [], generatedAt: timestamp }, operational: { rejectedSections: [{ key: "ci", reason: "unavailable" }], deploymentImpact: { affectedServices: ["api"], rollbackAvailable: true }, ciAnalysis: null }, metadata: { redactions: { token: 1 }, contextCache: "miss", noActionsExecuted: true } }, status: 200, statusText: "OK", headers: {}, config };
};
const client = new QueryClient({ defaultOptions: { queries: { retry: false } } });
ReactDOM.createRoot(document.getElementById("root")!).render(<React.StrictMode><QueryClientProvider client={client}><main className="mx-auto max-w-3xl space-y-4 p-4"><SystemHealthCard /><AiSettingsCard toast={() => undefined} /><AiAssistantPanel scope={{ type: "server", id: "browser-test-server" }} /></main></QueryClientProvider></React.StrictMode>);
