import crypto from "node:crypto";
import express from "express";
import { ObjectId } from "mongodb";
import { z } from "zod";
import { agentReleaseManifestDigest, agentReleaseSchema, agentUpgradePlanDigest, approvedCompatibleReleases, evaluateAgentCompatibility, fleetRolloutDigest, fleetRolloutSchema, type AgentInventory, type AgentRelease } from "@control-center/shared";
import { audit } from "./audit.js";
import { noStore, requirePermission, requireRecentAuth } from "./auth.js";
import { collections, oid } from "./db.js";
import { createTask } from "./tasks.js";
import type { AgentRolloutDoc, ServerDoc } from "./models.js";

export const agentUpgradeRouter = express.Router();
const requiredFleetCapabilities = ["environmentDiscovery"];
const nonProductionKinds = new Set(["development", "staging", "testing", "preview", "ci"]);
function orgId(req: express.Request) { if (!req.orgId) throw new Error("Organization scope required"); return req.orgId; }
function actorId(req: express.Request) { if (!req.user?._id) throw new Error("User required"); return req.user._id; }

async function serverInventory(org: ObjectId, server: ServerDoc | null): Promise<AgentInventory> {
  if (!server?._id) throw new Error("Server not found");
  const project = await collections.projects.findOne({ orgId: org, primaryServerId: server._id, archivedAt: { $exists: false } });
  const environment = project?._id ? await collections.configurationEnvironments.find({ orgId: org, projectId: project._id }).sort({ protected: -1 }).limit(1).next() : null;
  return { serverId: server._id.toHexString(), name: server.name, slug: server.slug, projectId: project?._id?.toHexString(), projectName: project?.name, environmentKind: server.environmentKind ?? environment?.kind, protected: server.protected ?? environment?.protected ?? true, online: server.agentStatus === "online", lastHeartbeatAt: server.lastHeartbeatAt?.toISOString(), agentVersion: server.agentVersion?.match(/^(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(?:-[0-9A-Za-z-]+(?:\.[0-9A-Za-z-]+)*)?$/) ? server.agentVersion : undefined, protocolVersion: server.agentProtocolVersion, capabilities: server.agentCapabilities || [], os: server.osName, architecture: server.architecture, packageType: server.agentPackageType, releaseChannel: server.agentReleaseChannel, binarySha256: server.agentBinarySha256, currentUpgradeState: server.upgradeState };
}

async function publishedReleases(org: ObjectId) { return collections.agentReleases.find({ orgId: org, publicationStatus: "published", revoked: false }).toArray() as unknown as Promise<AgentRelease[]>; }

async function queueApprovedPlan(org: ObjectId, planId: ObjectId, approver: ObjectId) {
  const plan = await collections.agentUpgradePlans.findOne({ _id: planId, orgId: org, state: "awaiting_approval" }); if (!plan?._id) throw new Error("Upgrade plan is no longer awaiting approval"); if (plan.createdByUserId.equals(approver)) throw new Error("Upgrade planner cannot approve the same plan"); if (Date.parse(plan.manifest.expiresAt) <= Date.now()) throw new Error("Upgrade plan expired");
  const [server, release] = await Promise.all([collections.servers.findOne({ _id: plan.serverId, orgId: org }), collections.agentReleases.findOne({ id: plan.releaseId, orgId: org, publicationStatus: "published", revoked: false, manifestDigest: plan.manifest.releaseManifestDigest })]); if (!server?._id || !release) throw new Error("Server state or release approval changed"); const inventory = await serverInventory(org, server); if (inventory.protected || !inventory.environmentKind || !nonProductionKinds.has(inventory.environmentKind)) throw new Error("Server is protected, production, or unclassified"); if (server.agentVersion !== plan.manifest.expectedCurrentVersion || server.agentId !== plan.manifest.expectedAgentId || server.agentBinarySha256 !== plan.manifest.expectedCurrentBinarySha256) throw new Error("Server identity or current state changed");
  const task = await createTask({ orgId: org, server: server as typeof server & { _id: ObjectId }, type: "agent.upgrade", payload: { projects: [], httpHealthChecks: [], mongoChecks: [], agentUpgrade: plan.manifest }, idempotencyKey: `agent-upgrade:${plan._id}:${plan.planDigest}`, createdByUserId: approver, expiresAt: new Date(plan.manifest.expiresAt) }); const now = new Date(); const updated = await collections.agentUpgradePlans.updateOne({ _id: plan._id, orgId: org, state: "awaiting_approval" }, { $set: { state: "queued", approvedByUserId: approver, approvedAt: now, taskId: task._id, updatedAt: now } }); if (!updated.modifiedCount) throw new Error("Upgrade plan was already consumed"); await collections.servers.updateOne({ _id: server._id, orgId: org }, { $set: { upgradeState: "queued", updatedAt: now } }); return task;
}

agentUpgradeRouter.get("/agent-upgrades/inventory", noStore, requirePermission("status:view"), async (req, res, next) => {
  try {
    const org = orgId(req); const [servers, releases] = await Promise.all([collections.servers.find({ orgId: org, archivedAt: { $exists: false } }).toArray(), publishedReleases(org)]);
    const inventory = await Promise.all(servers.map(async (server) => { const item = await serverInventory(org, server); return { ...item, compatibility: evaluateAgentCompatibility(item, releases, requiredFleetCapabilities) }; }));
    const count = (state: string) => inventory.filter((item) => item.compatibility.state === state || item.currentUpgradeState === state).length;
    res.json({ summary: { total: inventory.length, online: inventory.filter((item) => item.online).length, offline: inventory.filter((item) => !item.online).length, upToDate: count("up_to_date"), upgradeAvailable: count("upgrade_available"), upgradeRequired: count("upgrade_required"), manualBootstrap: count("manual_bootstrap_required"), failed: count("failed"), rolledBack: count("rolled_back") }, inventory });
  } catch (error) { next(error); }
});

agentUpgradeRouter.get("/agent-releases", noStore, requirePermission("status:view"), async (req, res, next) => { try { const rows = await collections.agentReleases.find({ orgId: orgId(req) }, { projection: { createdByUserId: 0 } }).sort({ version: -1 }).toArray(); res.json({ releases: rows }); } catch (error) { next(error); } });

agentUpgradeRouter.post("/agent-releases", noStore, requireRecentAuth, requirePermission("agent:update"), async (req, res, next) => {
  try { const parsed = agentReleaseSchema.parse({ ...req.body, publicationStatus: "draft", revoked: false }); if (agentReleaseManifestDigest(parsed) !== parsed.manifestDigest) return res.status(409).json({ error: "Release manifest digest does not match immutable release metadata" }); const now = new Date(); await collections.agentReleases.insertOne({ ...parsed, orgId: orgId(req), createdByUserId: actorId(req), createdAt: now, updatedAt: now }); await audit({ orgId: orgId(req), actorType: "user", actorId: actorId(req), action: "agent.release.create", targetType: "agent_release", targetId: parsed.id, result: "success", requestId: req.requestId, metadata: { version: parsed.version, channel: parsed.channel } }); res.status(201).json({ id: parsed.id, publicationStatus: "draft" }); } catch (error) { next(error); }
});

agentUpgradeRouter.post("/agent-releases/:id/publish", noStore, requireRecentAuth, requirePermission("agent:update"), async (req, res, next) => {
  try { const confirmation = z.object({ manifestDigest: z.string().regex(/^[a-f0-9]{64}$/), confirm: z.literal(true) }).strict().parse(req.body); const now = new Date(); const result = await collections.agentReleases.findOneAndUpdate({ orgId: orgId(req), id: String(req.params.id), publicationStatus: "draft", revoked: false, manifestDigest: confirmation.manifestDigest }, { $set: { publicationStatus: "published", publishedAt: now, updatedAt: now } }, { returnDocument: "after" }); if (!result) return res.status(409).json({ error: "Draft release changed, was revoked, or digest did not match" }); res.json({ id: result.id, publicationStatus: result.publicationStatus }); } catch (error) { next(error); }
});

agentUpgradeRouter.post("/agent-releases/:id/revoke", noStore, requireRecentAuth, requirePermission("agent:update"), async (req, res, next) => {
  try { const body = z.object({ confirm: z.literal(true), reason: z.string().trim().min(4).max(500) }).strict().parse(req.body); const now = new Date(); const result = await collections.agentReleases.updateOne({ orgId: orgId(req), id: String(req.params.id), revoked: false }, { $set: { revoked: true, revokedAt: now, updatedAt: now } }); if (!result.matchedCount) return res.status(404).json({ error: "Release not found" }); await audit({ orgId: orgId(req), actorType: "user", actorId: actorId(req), action: "agent.release.revoke", targetType: "agent_release", targetId: String(req.params.id), result: "success", requestId: req.requestId, metadata: { reasonRecorded: Boolean(body.reason) } }); res.json({ revoked: true }); } catch (error) { next(error); }
});

agentUpgradeRouter.post("/agent-upgrades/plans", noStore, requireRecentAuth, requirePermission("agent:update"), async (req, res, next) => {
  try {
    const body = z.object({ serverId: z.string(), releaseId: z.string(), confirm: z.literal(true) }).strict().parse(req.body); const org = orgId(req); const [server, release] = await Promise.all([collections.servers.findOne({ _id: oid(body.serverId), orgId: org, archivedAt: { $exists: false } }), collections.agentReleases.findOne({ id: body.releaseId, orgId: org, publicationStatus: "published", revoked: false })]);
    if (!server?._id || !release) return res.status(404).json({ error: "Server or approved release not found" }); const inventory = await serverInventory(org, server); if (inventory.protected || !inventory.environmentKind || !nonProductionKinds.has(inventory.environmentKind)) return res.status(403).json({ error: "Production, protected, and unclassified servers are unavailable for remote upgrade" });
    const compatibility = evaluateAgentCompatibility(inventory, [release], requiredFleetCapabilities); if (!compatibility.remoteUpgradeSupported) return res.status(409).json({ error: "Manual bootstrap required" }); if (!inventory.agentVersion || !inventory.os || !inventory.architecture || !inventory.packageType) return res.status(409).json({ error: "Agent inventory is incomplete" }); if (approvedCompatibleReleases(inventory, [release]).length !== 1) return res.status(409).json({ error: "Approved release is incompatible with the server's current version, platform, package type, or channel" });
    const expiresAt = new Date(Date.now() + 15 * 60 * 1000); const unsigned = { schemaVersion: "agent-upgrade-v1" as const, upgradeId: new ObjectId().toHexString(), serverId: server._id.toHexString(), expectedAgentId: server.agentId, expectedCurrentVersion: inventory.agentVersion, expectedCurrentBinarySha256: inventory.binarySha256, targetVersion: release.version, releaseId: release.id, artifactSha256: release.artifactSha256, artifactSignature: release.artifactSignature, signatureKeyId: release.signatureKeyId, releaseManifestDigest: release.manifestDigest, operatingSystem: inventory.os, architecture: inventory.architecture, packageType: inventory.packageType, requiredCapabilities: release.requiredCapabilities, expiresAt: expiresAt.toISOString(), nonce: crypto.randomBytes(24).toString("base64url") }; const planDigest = agentUpgradePlanDigest(unsigned); const manifest = { ...unsigned, planDigest }; const now = new Date(); const result = await collections.agentUpgradePlans.insertOne({ orgId: org, serverId: server._id, releaseId: release.id, manifest, planDigest, expectedServerUpdatedAt: server.updatedAt, state: "awaiting_approval", createdByUserId: actorId(req), createdAt: now, updatedAt: now }); await collections.servers.updateOne({ _id: server._id, orgId: org }, { $set: { upgradeState: "awaiting_approval", updatedAt: now } });
    res.status(201).json({ id: result.insertedId, state: "awaiting_approval", planDigest, expiresAt, plan: { serverId: manifest.serverId, currentVersion: manifest.expectedCurrentVersion, targetVersion: manifest.targetVersion, releaseId: manifest.releaseId, artifactSha256: manifest.artifactSha256, signatureKeyId: manifest.signatureKeyId, requiredCapabilities: manifest.requiredCapabilities, operatingSystem: manifest.operatingSystem, architecture: manifest.architecture, packageType: manifest.packageType, rollback: "Restore previous versioned release and validate heartbeat", restart: "Independent updater restarts the fixed agent service" } });
  } catch (error) { next(error); }
});

agentUpgradeRouter.post("/agent-upgrades/plans/:id/approve", noStore, requireRecentAuth, requirePermission("agent:update"), async (req, res, next) => {
  try {
    const body = z.object({ planDigest: z.string().regex(/^[a-f0-9]{64}$/), confirm: z.literal(true) }).strict().parse(req.body); const org = orgId(req); const plan = await collections.agentUpgradePlans.findOne({ _id: oid(String(req.params.id)), orgId: org, state: "awaiting_approval", planDigest: body.planDigest }); if (!plan?._id) return res.status(404).json({ error: "Upgrade plan not found or digest changed" }); if (plan.createdByUserId.equals(actorId(req))) return res.status(409).json({ error: "Upgrade planner cannot approve the same plan" }); if (Date.parse(plan.manifest.expiresAt) <= Date.now()) return res.status(409).json({ error: "Upgrade plan expired" });
    const [server, release] = await Promise.all([collections.servers.findOne({ _id: plan.serverId, orgId: org }), collections.agentReleases.findOne({ id: plan.releaseId, orgId: org, publicationStatus: "published", revoked: false, manifestDigest: plan.manifest.releaseManifestDigest })]); if (!server?._id || !release) return res.status(409).json({ error: "Server state or release approval changed" }); const inventory = await serverInventory(org, server); if (inventory.protected || !inventory.environmentKind || !nonProductionKinds.has(inventory.environmentKind)) return res.status(403).json({ error: "Server became protected, production, or unclassified" }); if (server.agentVersion !== plan.manifest.expectedCurrentVersion || server.agentId !== plan.manifest.expectedAgentId || server.agentBinarySha256 !== plan.manifest.expectedCurrentBinarySha256) return res.status(409).json({ error: "Server identity or current state changed" });
    const task = await createTask({ orgId: org, server: server as typeof server & { _id: ObjectId }, type: "agent.upgrade", payload: { projects: [], httpHealthChecks: [], mongoChecks: [], agentUpgrade: plan.manifest }, idempotencyKey: `agent-upgrade:${plan._id}:${plan.planDigest}`, createdByUserId: actorId(req), expiresAt: new Date(plan.manifest.expiresAt) }); const now = new Date(); const updated = await collections.agentUpgradePlans.updateOne({ _id: plan._id, orgId: org, state: "awaiting_approval", planDigest: body.planDigest }, { $set: { state: "queued", approvedByUserId: actorId(req), approvedAt: now, taskId: task._id, updatedAt: now } }); if (!updated.modifiedCount) return res.status(409).json({ error: "Upgrade plan was already consumed" }); await collections.servers.updateOne({ _id: server._id, orgId: org }, { $set: { upgradeState: "queued", updatedAt: now } }); res.json({ state: "queued", taskId: task._id });
  } catch (error) { next(error); }
});

agentUpgradeRouter.get("/agent-upgrades/history/:serverId", noStore, requirePermission("status:view"), async (req, res, next) => { try { const rows = await collections.agentUpgradePlans.find({ orgId: orgId(req), serverId: oid(String(req.params.serverId)) }, { projection: { manifest: 0 } }).sort({ createdAt: -1 }).limit(100).toArray(); res.json({ history: rows }); } catch (error) { next(error); } });

agentUpgradeRouter.post("/agent-upgrades/rollouts", noStore, requireRecentAuth, requirePermission("agent:update"), async (req, res, next) => {
  try { const body = fleetRolloutSchema.parse(req.body); const org = orgId(req); const plans = await collections.agentUpgradePlans.find({ orgId: org, serverId: { $in: body.serverIds.map(oid) }, releaseId: body.releaseId, state: "awaiting_approval" }).toArray(); if (plans.length !== body.serverIds.length || plans.some((plan) => body.perServerPlanDigests[plan.serverId.toHexString()] !== plan.planDigest)) return res.status(409).json({ error: "Rollout server set or plan digests changed" }); const servers = await collections.servers.find({ orgId: org, _id: { $in: body.serverIds.map(oid) } }).toArray(); const inventories = await Promise.all(servers.map((server) => serverInventory(org, server))); if (inventories.some((item) => item.protected || !item.environmentKind || !body.allowedEnvironments.includes(item.environmentKind) || !nonProductionKinds.has(item.environmentKind))) return res.status(403).json({ error: "Protected, production, or unclassified server included" }); const rolloutDigest = fleetRolloutDigest(body); const now = new Date(); const result = await collections.agentRollouts.insertOne({ orgId: org, releaseId: body.releaseId, serverIds: body.serverIds.map(oid), planIds: plans.map((plan) => plan._id!), perServerPlanDigests: body.perServerPlanDigests, rolloutDigest, strategy: body.strategy, batchSize: body.batchSize, percentage: body.percentage, failureThreshold: body.failureThreshold, allowedEnvironments: body.allowedEnvironments, expiresAt: new Date(body.expiresAt), state: "awaiting_approval", createdByUserId: actorId(req), createdAt: now, updatedAt: now }); res.status(201).json({ id: result.insertedId, state: "awaiting_approval", rolloutDigest }); } catch (error) { next(error); }
});

agentUpgradeRouter.post("/agent-upgrades/rollouts/:id/approve", noStore, requireRecentAuth, requirePermission("agent:update"), async (req, res, next) => {
  try {
    const body = z.object({ rolloutDigest: z.string().regex(/^[a-f0-9]{64}$/), confirm: z.literal(true) }).strict().parse(req.body); const org = orgId(req); const rollout = await collections.agentRollouts.findOne({ _id: oid(String(req.params.id)), orgId: org, state: "awaiting_approval", rolloutDigest: body.rolloutDigest });
    if (!rollout?._id) return res.status(404).json({ error: "Rollout not found or digest changed" }); if (rollout.createdByUserId.equals(actorId(req))) return res.status(409).json({ error: "Rollout planner cannot approve the same rollout" }); if (rollout.expiresAt <= new Date()) return res.status(409).json({ error: "Rollout approval expired" });
    const recomputed = fleetRolloutDigest({ releaseId: rollout.releaseId, serverIds: rollout.serverIds.map((id) => id.toHexString()), perServerPlanDigests: rollout.perServerPlanDigests, strategy: rollout.strategy, batchSize: rollout.batchSize, percentage: rollout.percentage, failureThreshold: rollout.failureThreshold, allowedEnvironments: rollout.allowedEnvironments, expiresAt: rollout.expiresAt.toISOString() });
    if (recomputed !== rollout.rolloutDigest) return res.status(409).json({ error: "Stored rollout approval inputs changed" });
    const plans = await collections.agentUpgradePlans.find({ orgId: org, _id: { $in: rollout.planIds }, state: "awaiting_approval" }).sort({ serverId: 1 }).toArray(); if (plans.length !== rollout.planIds.length || plans.some((plan) => rollout.perServerPlanDigests[plan.serverId.toHexString()] !== plan.planDigest)) return res.status(409).json({ error: "Rollout plans changed" });
    const batch = rollout.strategy === "canary" || rollout.strategy === "sequential" ? 1 : rollout.strategy === "fixed_batch" ? rollout.batchSize || 1 : Math.max(1, Math.ceil(plans.length * (rollout.percentage || 1) / 100)); for (const plan of plans.slice(0, batch)) await queueApprovedPlan(org, plan._id!, actorId(req)); const now = new Date(); await collections.agentRollouts.updateOne({ _id: rollout._id, orgId: org, state: "awaiting_approval" }, { $set: { state: "running", approvedByUserId: actorId(req), approvedAt: now, updatedAt: now } }); res.json({ state: "running", queued: Math.min(batch, plans.length) });
  } catch (error) { next(error); }
});

agentUpgradeRouter.post("/agent-upgrades/rollouts/:id/advance", noStore, requireRecentAuth, requirePermission("agent:update"), async (req, res, next) => { try { const org = orgId(req); const rollout = await collections.agentRollouts.findOne({ _id: oid(String(req.params.id)), orgId: org, state: "running" }); if (!rollout?._id || !rollout.approvedByUserId) return res.status(404).json({ error: "Running rollout not found" }); const plans = await collections.agentUpgradePlans.find({ orgId: org, _id: { $in: rollout.planIds } }).sort({ serverId: 1 }).toArray(); const failed = plans.filter((plan) => ["failed", "rolled_back"].includes(plan.state)).length; if (failed > rollout.failureThreshold) { await collections.agentRollouts.updateOne({ _id: rollout._id }, { $set: { state: "paused", updatedAt: new Date() } }); return res.json({ state: "paused", reason: "failure_threshold" }); } if (plans.some((plan) => ["queued", "upgrading", "validating"].includes(plan.state))) return res.status(409).json({ error: "Current batch is still active" }); const pending = plans.filter((plan) => plan.state === "awaiting_approval"); if (!pending.length) { await collections.agentRollouts.updateOne({ _id: rollout._id }, { $set: { state: "complete", updatedAt: new Date() } }); return res.json({ state: "complete" }); } const batch = rollout.strategy === "sequential" || rollout.strategy === "canary" ? 1 : rollout.strategy === "fixed_batch" ? rollout.batchSize || 1 : Math.max(1, Math.ceil(plans.length * (rollout.percentage || 1) / 100)); for (const plan of pending.slice(0, batch)) await queueApprovedPlan(org, plan._id!, rollout.approvedByUserId); res.json({ state: "running", queued: Math.min(batch, pending.length) }); } catch (error) { next(error); } });

for (const action of ["pause", "resume", "cancel"] as const) agentUpgradeRouter.post(`/agent-upgrades/rollouts/:id/${action}`, noStore, requireRecentAuth, requirePermission("agent:update"), async (req, res, next) => {
  try {
    const org = orgId(req); const id = oid(String(req.params.id)); const desired: AgentRolloutDoc["state"] = action === "pause" ? "paused" : action === "resume" ? "running" : "cancelled"; const allowed: AgentRolloutDoc["state"][] = action === "pause" ? ["running"] : action === "resume" ? ["paused"] : ["awaiting_approval", "running", "paused"]; const rollout = await collections.agentRollouts.findOneAndUpdate({ _id: id, orgId: org, state: { $in: allowed } }, { $set: { state: desired, updatedAt: new Date() } }, { returnDocument: "after" });
    if (!rollout) return res.status(409).json({ error: "Rollout state transition rejected" });
    if (action === "cancel") { const plans = await collections.agentUpgradePlans.find({ orgId: org, _id: { $in: rollout.planIds }, state: { $in: ["awaiting_approval", "queued"] } }).toArray(); const taskIds = plans.flatMap((plan) => plan.taskId ? [plan.taskId] : []); const now = new Date(); if (taskIds.length) await collections.agentTasks.updateMany({ orgId: org, _id: { $in: taskIds }, state: "queued" }, { $set: { state: "cancelled", cancelledAt: now, completedAt: now, updatedAt: now }, $inc: { version: 1 } }); await collections.agentUpgradePlans.updateMany({ orgId: org, _id: { $in: plans.map((plan) => plan._id!) }, state: { $in: ["awaiting_approval", "queued"] } }, { $set: { state: "cancelled", updatedAt: now } }); }
    res.json({ state: desired });
  } catch (error) { next(error); }
});
