import express from "express";
import { ObjectId } from "mongodb";
import { z } from "zod";
import { audit } from "./audit.js";
import { noStore, requirePermission } from "./auth.js";
import { collections } from "./db.js";
import { CREDIT_UNIT, CreditBlockedError, DEFAULT_WARNING_THRESHOLDS, estimatePrice, periodBounds } from "./creditLedger.js";

export const creditRouter = express.Router();
const integer = z.number().int().nonnegative().max(Number.MAX_SAFE_INTEGER);
const oid = (value: string | undefined) => value && ObjectId.isValid(value) ? new ObjectId(value) : undefined;

creditRouter.get("/credits/summary", noStore, requirePermission("ai:use"), async (req, res, next) => { try {
  const orgId = req.orgId!; const [account, org, controls, policies] = await Promise.all([collections.creditAccounts.findOne({ orgId }), collections.organizations.findOne({ _id: orgId }), collections.creditEmergencyControls.findOne({ orgId }), collections.creditBudgetPolicies.find({ orgId, enabled: true }).toArray()]);
  const timezone = org?.defaultTimezone || "America/Los_Angeles"; const now = new Date(); const day = periodBounds(now, timezone, "day"), month = periodBounds(now, timezone, "month");
  const [usedToday, usedMonth] = await Promise.all([collections.creditLedger.aggregate([{ $match: { orgId, entryType: "usage", createdAt: { $gte: day.start, $lt: day.end } } }, { $group: { _id: null, value: { $sum: { $multiply: ["$creditDelta", -1] } } } }]).toArray(), collections.creditLedger.aggregate([{ $match: { orgId, entryType: "usage", createdAt: { $gte: month.start, $lt: month.end } } }, { $group: { _id: null, value: { $sum: { $multiply: ["$creditDelta", -1] } } } }]).toArray()]);
  res.json({ account: account ? { status: account.status, availableCredits: account.cachedAvailableCredits, reservedCredits: account.cachedReservedCredits, currency: account.currency, creditUnitVersion: account.creditUnitVersion } : { status: "unconfigured", availableCredits: 0, reservedCredits: 0, currency: CREDIT_UNIT.currency, creditUnitVersion: CREDIT_UNIT.version }, usedToday: usedToday[0]?.value || 0, usedThisMonth: usedMonth[0]?.value || 0, timezone, policies, aiEnabled: Boolean(account?.status === "active" && controls?.globalAiEnabled && controls?.organizationAiEnabled), controls: controls || { globalAiEnabled: false, organizationAiEnabled: false, providerEnabled: {}, modelEnabled: {}, projectEnabled: {} } });
} catch (error) { next(error); } });

creditRouter.get("/credits/ledger", noStore, requirePermission("ai:use"), async (req, res, next) => { try {
  const limit = Math.min(Number(req.query.limit) || 50, 200); const filter: any = { orgId: req.orgId! }; for (const field of ["projectId", "userId", "requestId"] as const) { const value = oid(String(req.query[field] || "")); if (value) filter[field] = value; } for (const field of ["provider", "model", "entryType"] as const) if (req.query[field]) filter[field] = String(req.query[field]); if (req.query.before) filter.createdAt = { $lt: new Date(String(req.query.before)) }; const items = await collections.creditLedger.find(filter).sort({ createdAt: -1 }).limit(limit).toArray(); res.json({ items, nextCursor: items.length === limit ? items.at(-1)?.createdAt : null });
} catch (error) { next(error); } });

creditRouter.get("/credits/usage-requests", noStore, requirePermission("ai:use"), async (req, res, next) => { try { const items = await collections.creditUsageRequests.find({ orgId: req.orgId! }).sort({ startedAt: -1 }).limit(Math.min(Number(req.query.limit) || 50, 200)).toArray(); res.json({ items }); } catch (error) { next(error); } });
creditRouter.get("/credits/policies", noStore, requirePermission("ai:use"), async (req, res, next) => { try { res.json({ items: await collections.creditBudgetPolicies.find({ orgId: req.orgId! }).sort({ createdAt: -1 }).toArray() }); } catch (error) { next(error); } });

creditRouter.post("/credits/estimate", noStore, requirePermission("ai:use"), async (req, res, next) => { try {
  const body = z.object({ provider: z.string().min(1).max(80), model: z.string().min(1).max(160), estimatedInputUnits: integer, estimatedOutputUnits: integer }).strict().parse(req.body);
  if (body.provider === "deterministic") return res.json({ ...body, estimatedCostMicros: 0, estimatedCredits: 0, currency: CREDIT_UNIT.currency, creditUnitVersion: CREDIT_UNIT.version, binding: false, paidProviderUsed: false });
  const pricing = await collections.creditPricing.find({ provider: body.provider, model: body.model, enabled: true, effectiveFrom: { $lte: new Date() }, $or: [{ effectiveTo: { $exists: false } }, { effectiveTo: { $gt: new Date() } }] }).sort({ effectiveFrom: -1 }).limit(1).next();
  if (!pricing) throw new CreditBlockedError("pricing_unavailable", "Pricing unavailable for this provider and model");
  res.json({ ...body, ...estimatePrice(body.estimatedInputUnits, body.estimatedOutputUnits, pricing), currency: pricing.currency, pricingVersion: pricing.version, creditUnitVersion: CREDIT_UNIT.version, binding: false, paidProviderUsed: true });
} catch (error) { next(error); } });

creditRouter.put("/credits/policies", noStore, requirePermission("ai:admin"), async (req, res, next) => { try {
  const body = z.object({ id: z.string().optional(), projectId: z.string().optional(), userId: z.string().optional(), provider: z.string().max(80).optional(), model: z.string().max(160).optional(), policyType: z.enum(["per_request","per_project","daily","monthly","provider_daily","provider_monthly"]), limitCredits: integer, period: z.enum(["request","project_lifetime","day","month"]), warningThresholdPercent: z.array(z.number().int().min(1).max(100)).default([...DEFAULT_WARNING_THRESHOLDS]), hardLimit: z.boolean().default(true), enabled: z.boolean().default(true) }).strict().parse(req.body); const now = new Date(); const id = body.id && ObjectId.isValid(body.id) ? new ObjectId(body.id) : new ObjectId();
  await collections.creditBudgetPolicies.updateOne({ _id: id, orgId: req.orgId! }, { $set: { ...body, _id: id, orgId: req.orgId!, projectId: oid(body.projectId), userId: oid(body.userId), updatedAt: now, createdBy: req.user!._id }, $setOnInsert: { createdAt: now } }, { upsert: true }); await audit({ orgId: req.orgId, actorType: "user", actorId: req.user!._id, action: "credit.policy.change", targetType: "credit_policy", targetId: id, result: "success", requestId: req.requestId }); res.json(await collections.creditBudgetPolicies.findOne({ _id: id, orgId: req.orgId! }));
} catch (error) { next(error); } });

creditRouter.put("/credits/emergency-controls", noStore, requirePermission("ai:admin"), async (req, res, next) => { try { const body = z.object({ globalAiEnabled: z.boolean(), organizationAiEnabled: z.boolean(), providerEnabled: z.record(z.boolean()).default({}), modelEnabled: z.record(z.boolean()).default({}), projectEnabled: z.record(z.boolean()).default({}), reason: z.string().trim().min(3).max(500) }).strict().parse(req.body); const now = new Date(); await collections.creditEmergencyControls.updateOne({ orgId: req.orgId! }, { $set: { ...body, orgId: req.orgId!, changedBy: req.user!._id, changedAt: now, updatedAt: now }, $setOnInsert: { createdAt: now } }, { upsert: true }); await audit({ orgId: req.orgId, actorType: "user", actorId: req.user!._id, action: "credit.emergency.change", targetType: "credit_controls", result: "success", requestId: req.requestId, metadata: { reason: body.reason } }); res.json(await collections.creditEmergencyControls.findOne({ orgId: req.orgId! })); } catch (error) { next(error); } });

creditRouter.post("/credits/adjustments", noStore, requirePermission("ai:admin"), async (req, res, next) => { try { const body = z.object({ direction: z.enum(["credit","debit"]), credits: integer.refine((v) => v > 0), reason: z.string().trim().min(5).max(500), idempotencyKey: z.string().min(8).max(200) }).strict().parse(req.body); const account = await collections.creditAccounts.findOne({ orgId: req.orgId! }); if (!account) throw new CreditBlockedError("account_not_found", "Credit account not configured", 404); const delta = body.direction === "credit" ? body.credits : -body.credits; const now = new Date(); const updated = await collections.creditAccounts.findOneAndUpdate({ _id: account._id, orgId: req.orgId!, ...(delta < 0 ? { cachedAvailableCredits: { $gte: body.credits } } : {}) }, { $inc: { cachedAvailableCredits: delta }, $set: { updatedAt: now } }, { returnDocument: "after" }); if (!updated) throw new CreditBlockedError("insufficient_credits", "Adjustment would make available credits negative"); await collections.creditLedger.updateOne({ orgId: req.orgId!, entryKey: `${body.idempotencyKey}:adjustment` }, { $setOnInsert: { orgId: req.orgId!, creditAccountId: account._id!, userId: req.user!._id, idempotencyKey: body.idempotencyKey, entryKey: `${body.idempotencyKey}:adjustment`, entryType: body.direction === "credit" ? "adjustment_credit" : "adjustment_debit", creditDelta: delta, reservedCreditDelta: 0, currency: account.currency, status: "posted", reason: body.reason, balanceAfter: updated.cachedAvailableCredits + updated.cachedReservedCredits, createdAt: now, createdBy: req.user!._id } }, { upsert: true }); await audit({ orgId: req.orgId, actorType: "user", actorId: req.user!._id, action: "credit.adjustment.create", targetType: "credit_account", targetId: account._id, result: "success", requestId: req.requestId, metadata: { direction: body.direction, credits: body.credits, reason: body.reason } }); res.status(201).json({ availableCredits: updated.cachedAvailableCredits, reservedCredits: updated.cachedReservedCredits }); } catch (error) { next(error); } });

creditRouter.put("/credits/pricing", noStore, requirePermission("ai:admin"), async (req, res, next) => { try { const body = z.object({ provider: z.string().min(1).max(80), model: z.string().min(1).max(160), version: z.string().min(1).max(80), inputCostMicrosPerMillion: integer, outputCostMicrosPerMillion: integer, currency: z.string().length(3).default("USD"), pricingSource: z.string().min(3).max(500), enabled: z.boolean().default(true), effectiveFrom: z.coerce.date().default(() => new Date()) }).strict().parse(req.body); await collections.creditPricing.updateOne({ provider: body.provider, model: body.model, version: body.version }, { $set: { ...body, verifiedAt: new Date(), createdBy: req.user!._id } }, { upsert: true }); await audit({ orgId: req.orgId, actorType: "user", actorId: req.user!._id, action: "credit.pricing.change", targetType: "credit_pricing", targetId: `${body.provider}/${body.model}/${body.version}`, result: "success", requestId: req.requestId }); res.json(await collections.creditPricing.findOne({ provider: body.provider, model: body.model, version: body.version })); } catch (error) { next(error); } });

creditRouter.post("/credits/reconcile", noStore, requirePermission("ai:admin"), async (req, res, next) => { try { const unresolved = await collections.creditUsageRequests.find({ orgId: req.orgId!, status: "unknown" }).toArray(); await audit({ orgId: req.orgId, actorType: "user", actorId: req.user!._id, action: "credit.reconciliation.run", targetType: "credit_usage", result: "success", requestId: req.requestId, metadata: { unresolved: unresolved.length } }); res.json({ unresolved, mismatchCount: unresolved.length, changedEntries: 0 }); } catch (error) { next(error); } });
