export type EnvironmentDiagnostic = { level: "error" | "warning" | "info"; code: string; variable?: string; message: string };
export type EnvironmentValidation = { valid: boolean; mode: string; required: string[]; optional: string[]; diagnostics: EnvironmentDiagnostic[]; ai: { enabled: boolean; provider: string | null; model: string | null; credentialPresent: boolean; state: "disabled" | "unconfigured" | "ready" | "invalid" } };

const requiredInProduction = ["MONGO_URL", "CONTROL_CENTER_SESSION_SECRET", "CONTROL_CENTER_CSRF_SECRET", "CONTROL_CENTER_ENCRYPTION_KEY", "CONTROL_CENTER_PUBLIC_URL", "CONTROL_CENTER_WEB_ORIGIN", "CONTROL_CENTER_SECURE_COOKIES", "CONTROL_CENTER_TRUST_PROXY", "CONTROL_CENTER_BOOTSTRAP_MODE"];
export const optionalEnvironmentVariables = ["PORT", "CONTROL_CENTER_DB", "CONTROL_CENTER_ALLOW_INSECURE_COOKIES", "CONTROL_CENTER_TASK_SIGNING_KEY_VERSION", "CONTROL_CENTER_AGENT_REVISION", "CONTROL_CENTER_AGENT_ARCHIVE_SHA256", "AI_ASSISTANT_ENABLED", "AI_DEFAULT_PROVIDER", "AI_DEFAULT_MODEL", "AI_ALLOWED_PROVIDERS", "AI_ALLOWED_MODELS", "AI_WORKFORCE_MODEL_MAP", "AI_API_KEY", "AI_BASE_URL", "OPENAI_API_KEY", "OPENAI_BASE_URL", "ANTHROPIC_API_KEY", "ANTHROPIC_BASE_URL", "GEMINI_API_KEY", "GEMINI_BASE_URL", "OPENROUTER_API_KEY", "OPENROUTER_BASE_URL", "AI_REQUEST_TIMEOUT_MS", "AI_MAX_CONTEXT_BYTES", "AI_MAX_OUTPUT_TOKENS", "AI_MAX_REQUESTS_PER_USER_PER_HOUR", "AI_MAX_REQUESTS_PER_ORGANIZATION_PER_DAY", "AI_MAX_CONCURRENT_REQUESTS", "BUILD_VERSION", "GIT_COMMIT", "GIT_BRANCH"];
const deprecated = new Map([["AI_PROVIDER", "AI_DEFAULT_PROVIDER"], ["AI_MODEL", "AI_DEFAULT_MODEL"]]);
const known = new Set(["NODE_ENV", ...requiredInProduction, ...optionalEnvironmentVariables, ...deprecated.keys(), "CONTROL_CENTER_RUN_DB_TESTS", "CONTROL_CENTER_RUN_PRIVILEGED_FS_TESTS", "MONGO_URL_TEST", "CI_EXPECTED_TESTS"]);
const present = (env: NodeJS.ProcessEnv, name: string) => Boolean(env[name]?.trim());
const list = (value = "") => value.split(",").map((item) => item.trim()).filter(Boolean);

export function validateEnvironment(env: NodeJS.ProcessEnv = process.env): EnvironmentValidation {
  const diagnostics: EnvironmentDiagnostic[] = []; const production = env.NODE_ENV === "production"; const required = production ? requiredInProduction : [];
  for (const variable of required) if (!present(env, variable)) diagnostics.push({ level: "error", code: "missing_required", variable, message: `${variable} is required for production/staging startup.` });
  for (const [oldName, replacement] of deprecated) if (present(env, oldName)) diagnostics.push({ level: "warning", code: "deprecated_variable", variable: oldName, message: `${oldName} is deprecated; use ${replacement}.` });
  for (const name of Object.keys(env).filter((name) => /^(CONTROL_CENTER_|AI_|OPENAI_|ANTHROPIC_|GEMINI_|OPENROUTER_)/.test(name) && !known.has(name)).sort()) diagnostics.push({ level: "warning", code: "unknown_variable", variable: name, message: `${name} is not recognized by OpsWorkbench.` });
  for (const [legacy, current] of deprecated) if (present(env, legacy) && present(env, current) && env[legacy] !== env[current]) diagnostics.push({ level: "error", code: "conflicting_variables", variable: legacy, message: `${legacy} conflicts with ${current}.` });
  const agentRevisionPresent = present(env, "CONTROL_CENTER_AGENT_REVISION"); const agentDigestPresent = present(env, "CONTROL_CENTER_AGENT_ARCHIVE_SHA256");
  if (agentRevisionPresent !== agentDigestPresent) diagnostics.push({ level: "error", code: "incomplete_agent_release_identity", message: "The agent revision and archive SHA-256 must be configured together." });
  if (agentRevisionPresent && !/^[0-9a-f]{40}$/.test(env.CONTROL_CENTER_AGENT_REVISION!)) diagnostics.push({ level: "error", code: "invalid_agent_release_identity", variable: "CONTROL_CENTER_AGENT_REVISION", message: "The configured agent revision must be an exact lowercase Git commit." });
  if (agentDigestPresent && !/^[0-9a-f]{64}$/.test(env.CONTROL_CENTER_AGENT_ARCHIVE_SHA256!)) diagnostics.push({ level: "error", code: "invalid_agent_release_identity", variable: "CONTROL_CENTER_AGENT_ARCHIVE_SHA256", message: "The configured agent archive SHA-256 is invalid." });
  if (production && env.CONTROL_CENTER_SECURE_COOKIES !== "true") diagnostics.push({ level: "error", code: "unsafe_default", variable: "CONTROL_CENTER_SECURE_COOKIES", message: "Secure cookies must be enabled in production/staging." });
  if (production && env.CONTROL_CENTER_ALLOW_INSECURE_COOKIES === "true") diagnostics.push({ level: "error", code: "unsafe_default", variable: "CONTROL_CENTER_ALLOW_INSECURE_COOKIES", message: "Insecure cookies cannot be enabled in production/staging." });
  if (production && env.CONTROL_CENTER_BOOTSTRAP_MODE === "manual") diagnostics.push({ level: "warning", code: "bootstrap_open", variable: "CONTROL_CENTER_BOOTSTRAP_MODE", message: "Manual bootstrap must be disabled immediately after the first administrator is created." });
  for (const name of ["CONTROL_CENTER_SESSION_SECRET", "CONTROL_CENTER_CSRF_SECRET"]) if (production && present(env, name) && (env[name]!.length < 32 || /change-me|default|example/i.test(env[name]!))) diagnostics.push({ level: "error", code: "unsafe_secret", variable: name, message: `${name} must be a non-default value of at least 32 characters.` });
  const enabled = env.AI_ASSISTANT_ENABLED === "true"; const provider = env.AI_DEFAULT_PROVIDER || env.AI_PROVIDER || ""; const model = env.AI_DEFAULT_MODEL || env.AI_MODEL || ""; const allowedProviders = list(env.AI_ALLOWED_PROVIDERS || provider); const allowedModels = list(env.AI_ALLOWED_MODELS || model);
  const credentialVariable = ({ openai: "OPENAI_API_KEY", anthropic: "ANTHROPIC_API_KEY", gemini: "GEMINI_API_KEY", openrouter: "OPENROUTER_API_KEY" } as Record<string, string>)[provider];
  const credentialPresent = provider === "mock" || Boolean(credentialVariable && (present(env, credentialVariable) || present(env, "AI_API_KEY")));
  let aiState: EnvironmentValidation["ai"]["state"] = "disabled";
  if (enabled) { aiState = provider && model && credentialPresent ? "ready" : "unconfigured"; if (!provider || !model) diagnostics.push({ level: "error", code: "invalid_provider_configuration", message: "AI is enabled but provider and model are not both configured." }); if (provider && !allowedProviders.includes(provider)) diagnostics.push({ level: "error", code: "invalid_provider_configuration", variable: "AI_DEFAULT_PROVIDER", message: "The selected AI provider is not allowlisted." }); if (model && !allowedModels.includes(model)) diagnostics.push({ level: "error", code: "invalid_provider_configuration", variable: "AI_DEFAULT_MODEL", message: "The selected AI model is not allowlisted." }); if (provider && !["openai", "anthropic", "gemini", "openrouter", "mock"].includes(provider)) diagnostics.push({ level: "error", code: "invalid_provider_configuration", variable: "AI_DEFAULT_PROVIDER", message: "The selected AI provider is unsupported." }); if (provider && !credentialPresent) diagnostics.push({ level: "error", code: "invalid_provider_configuration", message: `The ${provider} provider credential is absent.` }); if (diagnostics.some((item) => item.code === "invalid_provider_configuration")) aiState = "invalid"; }
  else if (provider || model || credentialPresent) diagnostics.push({ level: "info", code: "ai_disabled_configuration_present", message: "AI configuration is present but the global assistant flag is disabled; no provider requests will occur automatically." });
  return { valid: !diagnostics.some((item) => item.level === "error"), mode: env.NODE_ENV || "development", required, optional: optionalEnvironmentVariables, diagnostics, ai: { enabled, provider: provider || null, model: model || null, credentialPresent, state: aiState } };
}

export function assertValidEnvironment(env: NodeJS.ProcessEnv = process.env) { const result = validateEnvironment(env); if (!result.valid) throw new Error(`Environment validation failed: ${result.diagnostics.filter((item) => item.level === "error").map((item) => item.message).join(" ")}`); return result; }
