import type { ObjectId } from "mongodb";
import type { AuditAction, AuditResult, Role } from "@control-center/shared";

export type BaseDoc = { _id?: ObjectId; orgId: ObjectId; createdAt: Date; updatedAt: Date };

export type AiOrganizationSettings = { enabled: boolean; provider?: string; model?: string; monthlyRequestLimit?: number; monthlyTokenLimit?: number; maximumRequestsPerUserPerHour: number; maximumRequestsPerOrganizationPerDay: number; maximumConcurrentRequests: number; allowedScopeTypes: Array<"server" | "application">; dataRetentionMode: "provider-dependent"; providerDataRetentionAcknowledgedAt?: Date; providerDataRetentionAcknowledgedBy?: ObjectId; updatedAt: Date; updatedBy: ObjectId };
export type OrganizationDoc = { _id?: ObjectId; name: string; slug: string; defaultTimezone?: string; status?: "active" | "suspended"; aiAssistant?: AiOrganizationSettings; createdAt: Date; updatedAt: Date };
export type UserDoc = BaseDoc & { email: string; name: string; role: Role; passwordHash: string; disabledAt?: Date; inviteIssuedAt?: Date; mustChangePassword?: boolean };
export type SessionDoc = BaseDoc & { userId: ObjectId; csrfTokenHash: string; authenticatedAt: Date; expiresAt: Date; lastSeenAt: Date };
export type EnrollmentUsage = { usedAt: Date; serverId: ObjectId; agentId: string; hostname: string };
export type EnrollmentDoc = BaseDoc & { tokenHash: string; name: string; description?: string; expiresAt?: Date; maxUses?: number; uses: number; usage: EnrollmentUsage[]; usedAt?: Date; usedByAgentId?: ObjectId; createdByUserId: ObjectId; serverId?: ObjectId; revokedAt?: Date };
export type ServerDoc = BaseDoc & { name: string; slug?: string; primaryUrl?: string; notes?: string; tags?: string[]; detectedPublicIps?: string[]; publicSiteStatus?: "reachable" | "unreachable" | "redirecting" | "tls_error" | "dns_error" | "unknown"; publicSiteHttpStatus?: number; publicSiteCheckedAt?: Date; enrollmentStatus?: "pending" | "connected" | "failed" | "cancelled" | "revoked"; agentStatus?: "never_connected" | "online" | "degraded" | "offline" | "revoked"; hostname: string; machineId?: string; agentInstallationId?: string; primaryIp?: string; privateIp?: string; osName?: string; osVersion?: string; kernelVersion?: string; architecture?: string; cpuModel?: string; cpuCoreCount?: number; memoryBytes?: number; diskBytes?: number; enrolledAt?: Date; firstHeartbeatAt?: Date; agentId: string; agentSecretHash: string; credentialVersion: number; revokedAt?: Date; archivedAt?: Date; lastHeartbeatAt?: Date; status: "online" | "offline" | "revoked"; agentVersion?: string; allowlistedRoots?: string[]; metadata?: Record<string, string>; currentState?: { metrics?: unknown; docker?: unknown[]; compose?: unknown[]; git?: unknown[]; discovery?: unknown; httpHealth?: unknown[]; mongo?: unknown[]; collectedAt?: Date } };
export type ProjectDoc = BaseDoc & { name: string; slug: string; primaryServerId: ObjectId; detachedServerId?: ObjectId; repoPath?: string; composePath?: string; githubRepository?: string; branch?: string; adapter?: "docker-compose"; serviceNames?: string[]; archivedAt?: Date; healthCheckIds: ObjectId[]; mongoCheckIds: ObjectId[] };
export type HealthCheckDoc = BaseDoc & { projectId: ObjectId; serverId: ObjectId; name: string; url: string; timeoutMs: number; expectedStatus?: number; intervalSeconds?: number; enabled: boolean; archivedAt?: Date; lastResult?: unknown };
export type MongoCheckDoc = BaseDoc & { projectId: ObjectId; serverId: ObjectId; name: string; databaseNameHint?: string; encryptedConnectionString?: string; secretReference?: string; secretLocation: "agent" | "api-encrypted"; enabled: boolean; archivedAt?: Date; lastResult?: unknown };
export type TelemetryDoc = BaseDoc & { serverId: ObjectId; collectedAt: Date; agentVersion: string; metrics?: unknown; docker?: unknown[]; compose?: unknown[]; git?: unknown[]; discovery?: unknown; httpHealth?: unknown[]; mongo?: unknown[]; expiresAt: Date };
export type AgentNonceDoc = BaseDoc & { agentId: string; nonce: string; expiresAt: Date };
export type AgentTaskDoc = BaseDoc & { serverId: ObjectId; projectId?: ObjectId; agentId: string; type: string; state: "queued" | "claimed" | "running" | "succeeded" | "failed" | "expired" | "cancelled"; payload: unknown; idempotencyKey: string; nonce: string; signingKeyVersion: string; version: number; createdByUserId?: ObjectId; availableAt: Date; expiresAt: Date; claimedAt?: Date; startedAt?: Date; completedAt?: Date; cancelledAt?: Date; cancellationRequestedAt?: Date; result?: unknown; resultSummary?: string; errorCategory?: string; progress?: number; historyExpiresAt: Date; updatedAt: Date };
export type AgentTaskResultDoc = BaseDoc & { taskId: ObjectId; serverId: ObjectId; projectId?: ObjectId; agentId: string; state: string; result: unknown; completedAt: Date; expiresAt: Date };
export type AuditEventDoc = { _id?: ObjectId; orgId?: ObjectId; actorType: "user" | "agent" | "system" | "anonymous"; actorId?: ObjectId | string; action: AuditAction; targetType?: string; targetId?: ObjectId | string; result: AuditResult; requestId: string; metadata?: Record<string, string | number | boolean | null>; createdAt: Date };
export type AiUsageDoc = { _id?: ObjectId; orgId: ObjectId; userId: ObjectId; provider: string; model: string; scopeType: "server" | "application"; contextBytes: number; inputTokens?: number; outputTokens?: number; durationMs?: number; outcome: "pending" | "success" | "failure"; failureCategory?: string; concurrencySlot?: number; createdAt: Date; expiresAt?: Date };
