import { db, collections } from "./db.js";
import { validateEnvironment, type EnvironmentValidation } from "./environmentValidation.js";
import { aiAssistantConfig, providerReadiness } from "./aiAssistant.js";
import { operationalContextCacheStatus } from "./aiContextBuilder.js";

const startedAt = new Date(); const startupWarnings: string[] = [];
export function initializeRuntimeReadiness(validation: EnvironmentValidation) { startupWarnings.splice(0, startupWarnings.length, ...validation.diagnostics.filter((item) => item.level !== "info").map((item) => item.message)); }
async function databaseState() { try { const ping = await db.command({ ping: 1 }); return { status: ping.ok === 1 ? "ready" : "degraded", connected: ping.ok === 1 }; } catch { return { status: "unavailable", connected: false }; } }
export async function runtimeHealth() {
  const environment = validateEnvironment(); const database = await databaseState(); const config = aiAssistantConfig(); const ai = providerReadiness(config);
  let auditStatus = "unavailable"; let indexCount = 0; let organizationCount = 0; let aiEnabledOrganizations = 0; try { await collections.auditEvents.findOne({}, { projection: { _id: 1 } }); auditStatus = "ready"; indexCount = (await collections.auditEvents.indexes()).length; organizationCount = await collections.organizations.countDocuments(); aiEnabledOrganizations = await collections.organizations.countDocuments({ "aiAssistant.enabled": true }); } catch { /* summarized only */ }
  return { status: database.connected && environment.valid ? "ready" : "degraded", timestamp: new Date().toISOString(), uptimeSeconds: Math.floor((Date.now() - startedAt.getTime()) / 1000), api: { status: "ready" }, mongo: database, agent: { status: database.connected ? "ready" : "unknown", heartbeatMonitoring: true }, backgroundWorkers: { status: "not_configured", workers: [] }, ai: { status: ai.state, globalEnabled: config.enabled, organizationState: aiEnabledOrganizations === 0 ? "disabled" : aiEnabledOrganizations === organizationCount ? "enabled" : "mixed", enabledOrganizations: aiEnabledOrganizations, provider: ai.provider, model: ai.model, credentialPresent: ai.credentialPresent, externalRequestsAutomatic: false }, audit: { status: auditStatus, indexCount }, rateLimiting: { status: "ready", globalRequestsPerMinute: 180 }, cache: operationalContextCacheStatus(), build: { version: process.env.BUILD_VERSION || "development", commit: process.env.GIT_COMMIT || "unknown", branch: process.env.GIT_BRANCH || "unknown", node: process.version }, featureFlags: { aiAssistant: config.enabled, operationalIntelligence: true }, environment: { valid: environment.valid, mode: environment.mode, errors: environment.diagnostics.filter((item) => item.level === "error").length, warnings: environment.diagnostics.filter((item) => item.level === "warning").length } };
}
export async function internalDiagnostics() { const health = await runtimeHealth(); const environment = validateEnvironment(); return { generatedAt: new Date().toISOString(), environment: { valid: environment.valid, mode: environment.mode, diagnostics: environment.diagnostics }, featureFlags: health.featureFlags, database: health.mongo, cache: health.cache, providerReadiness: health.ai, permissions: { model: "role-based", organizationScoped: true, aiUsePermission: "ai:use", aiAdminPermission: "ai:admin" }, recentStartupWarnings: startupWarnings.slice(-50), dependencies: { node: process.version, mongodb: "6.x", express: "4.x", zod: "3.x" }, audit: health.audit, rateLimiting: health.rateLimiting };
}
