import assert from "node:assert/strict";
import crypto from "node:crypto";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import test from "node:test";
import { agentReleaseManifestDigest, agentUpgradePlanDigest, type AgentRelease } from "@control-center/shared";
import { executeAgentUpgrade, type UpdaterHooks, type UpdaterPolicy } from "../src/updater.js";

// Junctions exercise the same atomic directory-link behavior without requiring
// Windows developer mode; production Linux continues to use directory symlinks.
if (process.platform === "win32") {
  const originalSymlinkSync = fs.symlinkSync.bind(fs);
  Object.defineProperty(fs, "symlinkSync", { value: ((target: fs.PathLike, link: fs.PathLike) => originalSymlinkSync(target, link, "junction")), configurable: true });
}

function fixture() {
  const root = fs.mkdtempSync(path.join(os.tmpdir(), "opsworkbench-updater-")); const policy: UpdaterPolicy = { root: path.join(root, "opt"), releases: path.join(root, "opt", "releases"), current: path.join(root, "opt", "current"), config: path.join(root, "etc"), agentConfig: path.join(root, "etc", "agent.json"), state: path.join(root, "state"), backups: path.join(root, "backups"), service: "opsworkbench-agent.service" }; for (const directory of [policy.releases, policy.config, policy.state, policy.backups]) fs.mkdirSync(directory, { recursive: true }); const previous = path.join(policy.releases, "0.1.0"); fs.mkdirSync(path.join(previous, "control-center", "apps", "agent", "dist"), { recursive: true }); fs.writeFileSync(path.join(previous, "control-center", "apps", "agent", "dist", "agent.js"), "previous"); fs.symlinkSync(previous, policy.current, "dir"); fs.writeFileSync(policy.agentConfig, JSON.stringify({ agentVersion: "0.1.0", agentSecret: "synthetic-never-report" }), { mode: 0o600 });
  const artifact = Buffer.from("signed-fixture-artifact"); const keys = crypto.generateKeyPairSync("ed25519"); const signature = crypto.sign(null, artifact, keys.privateKey).toString("base64"); const releaseBase = { id: "release-020", version: "0.2.0", protocolVersion: "task-v1", minimumSourceVersion: "0.1.0", supportedOperatingSystems: ["linux"], supportedArchitectures: ["x64"], packageType: "tar" as const, channel: "stable" as const, artifactUrl: "https://releases.example.test/agent-0.2.0.tar.gz", artifactSha256: crypto.createHash("sha256").update(artifact).digest("hex"), artifactSizeBytes: artifact.length, artifactSignature: signature, signatureKeyId: "test-ed25519", requiredCapabilities: ["environmentDiscovery", "agentUpgrade"], upgradeFrom: ["0.1.0"], rollbackTo: ["0.1.0"], classification: "mandatory" as const }; const manifestDigest = agentReleaseManifestDigest(releaseBase); const release: AgentRelease = { ...releaseBase, manifestDigest, manifestSignature: crypto.sign(null, Buffer.from(manifestDigest, "hex"), keys.privateKey).toString("base64"), publicationStatus: "published", revoked: false };
  const unsigned = { schemaVersion: "agent-upgrade-v1" as const, upgradeId: "upgrade-123456", serverId: "server-123456", expectedAgentId: "agent-123456", expectedCurrentVersion: "0.1.0", targetVersion: "0.2.0", releaseId: release.id, artifactSha256: release.artifactSha256, artifactSignature: release.artifactSignature, signatureKeyId: release.signatureKeyId, releaseManifestDigest: release.manifestDigest, operatingSystem: "linux", architecture: "x64", packageType: "tar" as const, requiredCapabilities: release.requiredCapabilities, expiresAt: new Date(Date.now() + 60_000).toISOString(), nonce: "nonce-1234567890123456" }; const manifest = { ...unsigned, planDigest: agentUpgradePlanDigest(unsigned) }; const context = { policy, identity: { serverId: unsigned.serverId, agentId: unsigned.expectedAgentId, currentVersion: "0.1.0", os: "linux", architecture: "x64", packageType: "tar" as const }, releases: [release], trustedKeys: { [release.signatureKeyId]: keys.publicKey.export({ type: "spki", format: "pem" }).toString() } };
  const hooks: UpdaterHooks = { download: async () => artifact, extract: async (_archive, destination) => { const entry = path.join(destination, "control-center", "apps", "agent", "dist"); fs.mkdirSync(entry, { recursive: true }); fs.writeFileSync(path.join(entry, "agent.js"), "target"); }, restart: async () => true, heartbeat: async () => true, freeBytes: () => 1_000_000 };
  return { root, policy, artifact, release, manifest, context, hooks };
}

test("independent updater verifies, switches atomically, and preserves known-good backup", async () => { const item = fixture(); const result = await executeAgentUpgrade(item.manifest, item.context, item.hooks); assert.equal(result.phase, "complete"); assert.equal(path.basename(fs.realpathSync(item.policy.current)), "0.2.0"); assert.ok(fs.readdirSync(item.policy.backups).some((name) => name.includes("0.1.0"))); const config = JSON.parse(fs.readFileSync(item.policy.agentConfig, "utf8")); assert.equal(config.agentVersion, "0.2.0"); assert.equal(config.agentSecret, "synthetic-never-report"); assert.doesNotMatch(JSON.stringify(result), /synthetic-never-report/); });
test("digest, signature, partial download, disk, architecture, and revoked release fail closed", async () => { for (const mutate of [(x: ReturnType<typeof fixture>) => x.hooks.download = async () => Buffer.from("bad"), (x: ReturnType<typeof fixture>) => x.release.artifactSignature = Buffer.alloc(64).toString("base64"), (x: ReturnType<typeof fixture>) => x.hooks.download = async () => x.artifact.subarray(0, 2), (x: ReturnType<typeof fixture>) => x.hooks.freeBytes = () => 1, (x: ReturnType<typeof fixture>) => x.context.identity.architecture = "arm64", (x: ReturnType<typeof fixture>) => x.release.revoked = true]) { const item = fixture(); mutate(item); await assert.rejects(() => executeAgentUpgrade(item.manifest, item.context, item.hooks)); assert.equal(path.basename(fs.realpathSync(item.policy.current)), "0.1.0"); } });
test("restart or heartbeat failure rolls back and reports rollback health", async () => { for (const hook of ["restart", "heartbeat"] as const) { const item = fixture(); let calls = 0; if (hook === "restart") item.hooks.restart = async () => ++calls > 1; else item.hooks.heartbeat = async () => ++calls > 1; const result = await executeAgentUpgrade(item.manifest, item.context, item.hooks); assert.equal(result.phase, "rolled_back"); assert.equal(path.basename(fs.realpathSync(item.policy.current)), "0.1.0"); assert.equal(JSON.parse(fs.readFileSync(item.policy.agentConfig, "utf8")).agentVersion, "0.1.0"); } });
test("rollback failure is explicit and concurrent or duplicate upgrades are rejected", async () => { const rollback = fixture(); rollback.hooks.restart = async () => false; const failed = await executeAgentUpgrade(rollback.manifest, rollback.context, rollback.hooks); assert.equal(failed.phase, "rollback_failed"); const concurrent = fixture(); fs.writeFileSync(path.join(concurrent.policy.state, "upgrade.lock"), "held", { mode: 0o600 }); await assert.rejects(() => executeAgentUpgrade(concurrent.manifest, concurrent.context, concurrent.hooks)); const duplicate = fixture(); fs.mkdirSync(path.join(duplicate.policy.releases, "0.2.0")); await assert.rejects(() => executeAgentUpgrade(duplicate.manifest, duplicate.context, duplicate.hooks)); });
