import fs from "node:fs";
import path from "node:path";
import os from "node:os";
import { execFile } from "node:child_process";
import { promisify } from "node:util";
import { executeAgentUpgrade, updaterPolicy } from "./updater.js";
const exec = promisify(execFile);

async function extract(archive: string, destination: string, packageType: "tar" | "deb" | "rpm") { if (packageType !== "tar") throw new Error("Package installer is not enabled by updater policy"); const listed = (await exec("tar", ["-tzf", archive], { maxBuffer: 2 * 1024 * 1024 })).stdout.split(/\r?\n/).filter(Boolean); if (!listed.length || listed.some((entry) => entry.startsWith("/") || entry.split("/").includes(".."))) throw new Error("Archive path rejected"); await exec("tar", ["-xzf", archive, "-C", destination, "--no-same-owner", "--no-same-permissions"]); }
async function restart(service: string) { try { await exec("systemctl", ["restart", service]); return true; } catch { return false; } }
async function heartbeat(version: string, capabilities: string[], timeoutMs: number) { const deadline = Date.now() + timeoutMs; const file = path.join(updaterPolicy.state, "agent", "heartbeat.json"); while (Date.now() < deadline) { try { const value = JSON.parse(fs.readFileSync(file, "utf8")); if (value.agentVersion === version && capabilities.every((item) => value.capabilities?.includes(item)) && value.discoveryComplete === true) return true; } catch { /* retry */ } await new Promise((resolve) => setTimeout(resolve, 2000)); } return false; }

const inbox = path.join(updaterPolicy.state, "updater-inbox"); const results = path.join(updaterPolicy.state, "updater-results"); const agentConfig = JSON.parse(fs.readFileSync(updaterPolicy.agentConfig, "utf8")); const identity = { serverId: agentConfig.serverId, agentId: agentConfig.agentId, currentVersion: agentConfig.agentVersion, currentBinarySha256: agentConfig.binarySha256, os: os.platform(), architecture: os.arch(), packageType: agentConfig.packageType || "tar" }; const releases = JSON.parse(fs.readFileSync(path.join(updaterPolicy.config, "release-catalog.json"), "utf8")); const trustedKeys = JSON.parse(fs.readFileSync(path.join(updaterPolicy.config, "updater-trust.json"), "utf8")); fs.mkdirSync(inbox, { recursive: true, mode: 0o730 }); fs.mkdirSync(results, { recursive: true, mode: 0o750 });
for (const name of fs.readdirSync(inbox).filter((item) => /^[A-Za-z0-9._:-]+\.json$/.test(item)).sort()) { const file = path.join(inbox, name); let upgradeId = path.basename(name, ".json"); try { const manifest = JSON.parse(fs.readFileSync(file, "utf8")); if (typeof manifest.upgradeId === "string" && /^[A-Za-z0-9._:-]{1,160}$/.test(manifest.upgradeId)) upgradeId = manifest.upgradeId; const result = await executeAgentUpgrade(manifest, { identity, releases, trustedKeys }, { download: async (url) => { const response = await fetch(url, { redirect: "error", signal: AbortSignal.timeout(60_000) }); if (!response.ok) throw new Error("Artifact download failed"); return Buffer.from(await response.arrayBuffer()); }, extract, restart, heartbeat }); fs.writeFileSync(path.join(results, `${upgradeId}.result.json`), `${JSON.stringify(result)}\n`, { mode: 0o640, flag: "wx" }); fs.unlinkSync(file); } catch { try { fs.writeFileSync(path.join(results, `${upgradeId}.result.json`), `${JSON.stringify({ phase: "failed", upgradeId, errorCategory: "unknown" })}\n`, { mode: 0o640, flag: "wx" }); fs.unlinkSync(file); } catch { /* leave manifest for operator-safe retry */ } process.exitCode = 1; } }
