import crypto from "node:crypto";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { agentReleaseManifestDigest, agentReleaseSchema, agentUpgradeManifestSchema, agentUpgradePlanDigest, type AgentRelease } from "@control-center/shared";

export const updaterPolicy = Object.freeze({ root: "/opt/opsworkbench-agent", releases: "/opt/opsworkbench-agent/releases", current: "/opt/opsworkbench-agent/current", config: "/etc/opsworkbench-agent", agentConfig: "/etc/opsworkbench-agent/agent.json", state: "/var/lib/opsworkbench-agent", backups: "/var/backups/opsworkbench-agent", service: "opsworkbench-agent.service" });
export type UpdaterPolicy = { root: string; releases: string; current: string; config: string; agentConfig: string; state: string; backups: string; service: string };
export type UpdaterHooks = { download: (url: string) => Promise<Buffer>; extract: (archive: string, destination: string, packageType: AgentRelease["packageType"]) => Promise<void>; restart: (service: string) => Promise<boolean>; heartbeat: (targetVersion: string, capabilities: string[], timeoutMs: number) => Promise<boolean>; freeBytes?: (directory: string) => number; now?: () => Date };
export type UpdaterContext = { policy?: UpdaterPolicy; identity: { serverId: string; agentId: string; currentVersion: string; currentBinarySha256?: string; os: string; architecture: string; packageType: AgentRelease["packageType"] }; releases: AgentRelease[]; trustedKeys: Record<string, string> };

function safeReleaseDirectory(root: string, version: string) { const target = path.resolve(root, version); if (path.dirname(target) !== path.resolve(root)) throw new Error("Release path rejected"); return target; }
function acquireLock(file: string) { fs.mkdirSync(path.dirname(file), { recursive: true, mode: 0o700 }); return fs.openSync(file, "wx", 0o600); }
function atomicSymlink(target: string, link: string) { const temporary = `${link}.pending`; try { fs.unlinkSync(temporary); } catch { /* absent */ } fs.symlinkSync(target, temporary, process.platform === "win32" ? "junction" : "dir"); if (process.platform === "win32") { try { fs.unlinkSync(link); } catch { /* absent */ } } fs.renameSync(temporary, link); }
function verifySignature(artifact: Buffer, signature: string, publicKey: string) { if (!crypto.verify(null, artifact, publicKey, Buffer.from(signature, "base64"))) throw new Error("Artifact signature verification failed"); }
function verifyPackageStructure(directory: string) { const pending = [directory]; let entries = 0; while (pending.length) { const current = pending.pop()!; for (const child of fs.readdirSync(current)) { entries += 1; if (entries > 20_000) throw new Error("Agent package contains too many entries"); const candidate = path.join(current, child); const stat = fs.lstatSync(candidate); if (stat.isSymbolicLink() || (!stat.isFile() && !stat.isDirectory())) throw new Error("Agent package contains a link or special file"); if (stat.isDirectory()) pending.push(candidate); } } const entry = path.join(directory, "control-center", "apps", "agent", "dist", "agent.js"); const stat = fs.lstatSync(entry); if (!stat.isFile() || stat.isSymbolicLink()) throw new Error("Agent package structure is invalid"); }
function writeAgentConfig(file: string, content: string, stat: fs.Stats) { const temporary = `${file}.upgrade-pending`; const fd = fs.openSync(temporary, "wx", 0o600); try { fs.writeFileSync(fd, content, "utf8"); fs.fsyncSync(fd); fs.fchmodSync(fd, stat.mode); if (process.platform !== "win32") fs.fchownSync(fd, stat.uid, stat.gid); } finally { fs.closeSync(fd); } fs.renameSync(temporary, file); }

export async function executeAgentUpgrade(raw: unknown, context: UpdaterContext, hooks: UpdaterHooks) {
  const manifest = agentUpgradeManifestSchema.parse(raw); const policy = context.policy || updaterPolicy; const now = (hooks.now || (() => new Date()))();
  const { planDigest: _digest, ...unsigned } = manifest; if (agentUpgradePlanDigest(unsigned) !== manifest.planDigest) throw new Error("Upgrade plan digest mismatch");
  if (Date.parse(manifest.expiresAt) <= now.getTime()) throw new Error("Upgrade manifest expired");
  if (manifest.serverId !== context.identity.serverId || manifest.expectedAgentId !== context.identity.agentId) throw new Error("Server identity mismatch");
  if (manifest.expectedCurrentVersion !== context.identity.currentVersion || (manifest.expectedCurrentBinarySha256 && manifest.expectedCurrentBinarySha256 !== context.identity.currentBinarySha256)) throw new Error("Expected current agent state changed");
  if (manifest.operatingSystem !== context.identity.os || manifest.architecture !== context.identity.architecture || manifest.packageType !== context.identity.packageType) throw new Error("Operating system, architecture, or package type mismatch");
  const release = context.releases.map((item) => agentReleaseSchema.parse(item)).find((item) => item.id === manifest.releaseId && item.publicationStatus === "published" && !item.revoked); if (!release) throw new Error("Approved release is missing or revoked");
  if (release.version !== manifest.targetVersion || release.artifactSha256 !== manifest.artifactSha256 || release.artifactSignature !== manifest.artifactSignature || release.manifestDigest !== manifest.releaseManifestDigest || release.signatureKeyId !== manifest.signatureKeyId) throw new Error("Release catalog no longer matches the plan");
  const publicKey = context.trustedKeys[release.signatureKeyId]; if (!publicKey) throw new Error("Release signing key is not trusted"); if (agentReleaseManifestDigest(release) !== release.manifestDigest || !crypto.verify(null, Buffer.from(release.manifestDigest, "hex"), publicKey, Buffer.from(release.manifestSignature, "base64"))) throw new Error("Release manifest signature verification failed");
  fs.mkdirSync(policy.releases, { recursive: true, mode: 0o755 }); fs.mkdirSync(policy.backups, { recursive: true, mode: 0o700 }); fs.mkdirSync(policy.state, { recursive: true, mode: 0o700 });
  const lockPath = path.join(policy.state, "upgrade.lock"); const consumedDirectory = path.join(policy.state, "consumed-upgrades"); let lock: number | undefined; let staging: string | undefined; let previous: string | undefined; let switched = false; let originalConfig: string | undefined; let configStat: fs.Stats | undefined;
  try {
    lock = acquireLock(lockPath); fs.mkdirSync(consumedDirectory, { recursive: true, mode: 0o700 }); const consumed = path.join(consumedDirectory, `${manifest.upgradeId}-${manifest.nonce}.used`); const consumedFd = fs.openSync(consumed, "wx", 0o600); fs.closeSync(consumedFd); staging = fs.mkdtempSync(path.join(policy.state, ".upgrade-")); const archive = path.join(staging, "artifact"); const unpacked = path.join(staging, "release"); const free = (hooks.freeBytes || ((directory) => { const stat = fs.statfsSync(directory); return Number(stat.bavail) * Number(stat.bsize); }))(policy.state); if (free < release.artifactSizeBytes * 3) throw new Error("Insufficient disk space for safe upgrade and rollback");
    const artifact = await hooks.download(release.artifactUrl); if (artifact.length !== release.artifactSizeBytes) throw new Error("Artifact download was partial or oversized"); if (crypto.createHash("sha256").update(artifact).digest("hex") !== release.artifactSha256) throw new Error("Artifact digest verification failed"); verifySignature(artifact, release.artifactSignature, publicKey); fs.writeFileSync(archive, artifact, { mode: 0o600, flag: "wx" }); fs.mkdirSync(unpacked, { mode: 0o700 }); await hooks.extract(archive, unpacked, release.packageType); verifyPackageStructure(unpacked);
    const target = safeReleaseDirectory(policy.releases, release.version); if (fs.existsSync(target)) throw new Error("Target release already exists"); fs.renameSync(unpacked, target); previous = fs.existsSync(policy.current) ? fs.realpathSync(policy.current) : undefined; if (!previous) throw new Error("Known-good current release is unavailable"); const backup = path.join(policy.backups, `${manifest.upgradeId}-${path.basename(previous)}`); fs.cpSync(previous, backup, { recursive: true, errorOnExist: true }); configStat = fs.lstatSync(policy.agentConfig); if (!configStat.isFile() || configStat.isSymbolicLink() || configStat.nlink !== 1) throw new Error("Agent configuration file is unsafe"); originalConfig = fs.readFileSync(policy.agentConfig, "utf8"); fs.writeFileSync(path.join(policy.backups, `${manifest.upgradeId}.agent.json`), originalConfig, { mode: 0o600, flag: "wx" }); const nextConfig = JSON.parse(originalConfig); nextConfig.agentVersion = release.version; nextConfig.binarySha256 = release.artifactSha256; writeAgentConfig(policy.agentConfig, `${JSON.stringify(nextConfig, null, 2)}\n`, configStat); atomicSymlink(target, policy.current); switched = true;
    if (!await hooks.restart(policy.service)) throw new Error("Agent service restart failed"); if (!await hooks.heartbeat(release.version, release.requiredCapabilities, 120_000)) throw new Error("Target heartbeat, capabilities, or discovery validation failed"); return { phase: "complete" as const, upgradeId: manifest.upgradeId, targetVersion: release.version };
  } catch (error) {
    if (originalConfig && configStat) writeAgentConfig(policy.agentConfig, originalConfig, configStat); if (switched && previous) { atomicSymlink(previous, policy.current); const restarted = await hooks.restart(policy.service).catch(() => false); const heartbeat = restarted && await hooks.heartbeat(context.identity.currentVersion, [], 120_000).catch(() => false); return { phase: heartbeat ? "rolled_back" as const : "rollback_failed" as const, upgradeId: manifest.upgradeId, errorCategory: error instanceof Error && /digest|signature|architecture|disk|download|package|restart|heartbeat|identity|expired|concurrent/i.test(error.message) ? "validation" : "unknown" }; }
    throw error;
  } finally { if (staging) fs.rmSync(staging, { recursive: true, force: true }); if (lock !== undefined) { fs.closeSync(lock); try { fs.unlinkSync(lockPath); } catch { /* already removed */ } } }
}

export function defaultIdentity() { return { os: os.platform(), architecture: os.arch() }; }
